## FOODIE-FI SQL CHALLENGE
This is a sql project created by [Danny Ma](https://www.linkedin.com/in/datawithdanny/) to help individuals emerging into the data scene. From my view, it helps establish the foundational knowledge of sql while testing and developing logical problem skills.
I have chosen to do it in Python because it highlights how you can create a database on your system to allow for continuous use.

To get access to this and other of Danny's projects - [8 Week SQL Challenge](https://8weeksqlchallenge.com/).

Before getting started, I would also recommend installing "ipython-sql". This allows you use the 'jupyter magic' function to interact with your relational database.

### Importing Libraries

In [1]:
import sqlite3 as sql
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

### Creating Database, Table & Inserting Values into Table

In [2]:
conn = sql.connect('foodie-fi.db')
c = conn.cursor()

def create_table():
    c.execute('CREATE TABLE IF NOT EXISTS plans (plan_id INT,plan_name TEXT,price REAL)')
    c.execute('CREATE TABLE IF NOT EXISTS subscription (customer_id INT,plan_id INT,start_date TEXT)')
    

              
def data_entry():    
    c.execute("INSERT INTO plans VALUES ('0', 'trial', '0')")
    c.execute("INSERT INTO plans VALUES ('1', 'basic monthly', '9.90')")
    c.execute("INSERT INTO plans VALUES ('2', 'pro monthly', '19.90')")
    c.execute("INSERT INTO plans VALUES ('3', 'pro annual', '199')")
    c.execute("INSERT INTO plans VALUES ('4', 'churn', null)")


    
    
    c.execute("INSERT INTO subscription VALUES ('1', '0', '2020-08-01') ")
    c.execute("INSERT INTO subscription VALUES ('1', '1', '2020-08-08') ")
    c.execute("INSERT INTO subscription VALUES ('2', '0', '2020-09-20') ")
    c.execute("INSERT INTO subscription VALUES ('2', '3', '2020-09-27') ")
    c.execute("INSERT INTO subscription VALUES ('3', '0', '2020-01-13') ")
    c.execute("INSERT INTO subscription VALUES ('3', '1', '2020-01-20') ")
    c.execute("INSERT INTO subscription VALUES ('4', '0', '2020-01-17') ")
    c.execute("INSERT INTO subscription VALUES ('4', '1', '2020-01-24') ")
    c.execute("INSERT INTO subscription VALUES ('4', '4', '2020-04-21') ")
    c.execute("INSERT INTO subscription VALUES ('5', '0', '2020-08-03') ")
    c.execute("INSERT INTO subscription VALUES ('5', '1', '2020-08-10') ")
    c.execute("INSERT INTO subscription VALUES ('6', '0', '2020-12-23') ")
    c.execute("INSERT INTO subscription VALUES ('6', '1', '2020-12-30') ")
    c.execute("INSERT INTO subscription VALUES ('6', '4', '2021-02-26') ")
    c.execute("INSERT INTO subscription VALUES ('7', '0', '2020-02-05') ")
    c.execute("INSERT INTO subscription VALUES ('7', '1', '2020-02-12') ")
    c.execute("INSERT INTO subscription VALUES ('7', '2', '2020-05-22') ")
    c.execute("INSERT INTO subscription VALUES ('8', '0', '2020-06-11') ")
    c.execute("INSERT INTO subscription VALUES ('8', '1', '2020-06-18') ")
    c.execute("INSERT INTO subscription VALUES ('8', '2', '2020-08-03') ")
    c.execute("INSERT INTO subscription VALUES ('9', '0', '2020-12-07') ")
    c.execute("INSERT INTO subscription VALUES ('9', '3', '2020-12-14') ")
    c.execute("INSERT INTO subscription VALUES ('10', '0', '2020-09-19') ")
    c.execute("INSERT INTO subscription VALUES ('10', '2', '2020-09-26') ")
    c.execute("INSERT INTO subscription VALUES ('11', '0', '2020-11-19') ")
    c.execute("INSERT INTO subscription VALUES ('11', '4', '2020-11-26') ")
    c.execute("INSERT INTO subscription VALUES ('12', '0', '2020-09-22') ")
    c.execute("INSERT INTO subscription VALUES ('12', '1', '2020-09-29') ")
    c.execute("INSERT INTO subscription VALUES ('13', '0', '2020-12-15') ")
    c.execute("INSERT INTO subscription VALUES ('13', '1', '2020-12-22') ")
    c.execute("INSERT INTO subscription VALUES ('13', '2', '2021-03-29') ")
    c.execute("INSERT INTO subscription VALUES ('14', '0', '2020-09-22') ")
    c.execute("INSERT INTO subscription VALUES ('14', '1', '2020-09-29') ")
    c.execute("INSERT INTO subscription VALUES ('15', '0', '2020-03-17') ")
    c.execute("INSERT INTO subscription VALUES ('15', '2', '2020-03-24') ")
    c.execute("INSERT INTO subscription VALUES ('15', '4', '2020-04-29') ")
    c.execute("INSERT INTO subscription VALUES ('16', '0', '2020-05-31') ")
    c.execute("INSERT INTO subscription VALUES ('16', '1', '2020-06-07') ")
    c.execute("INSERT INTO subscription VALUES ('16', '3', '2020-10-21') ")
    c.execute("INSERT INTO subscription VALUES ('17', '0', '2020-07-27') ")
    c.execute("INSERT INTO subscription VALUES ('17', '1', '2020-08-03') ")
    c.execute("INSERT INTO subscription VALUES ('17', '3', '2020-12-11') ")
    c.execute("INSERT INTO subscription VALUES ('18', '0', '2020-07-06') ")
    c.execute("INSERT INTO subscription VALUES ('18', '2', '2020-07-13') ")
    c.execute("INSERT INTO subscription VALUES ('19', '0', '2020-06-22') ")
    c.execute("INSERT INTO subscription VALUES ('19', '2', '2020-06-29') ")
    c.execute("INSERT INTO subscription VALUES ('19', '3', '2020-08-29') ")
    c.execute("INSERT INTO subscription VALUES ('20', '0', '2020-04-08') ")
    c.execute("INSERT INTO subscription VALUES ('20', '1', '2020-04-15') ")
    c.execute("INSERT INTO subscription VALUES ('20', '3', '2020-06-05') ")
    c.execute("INSERT INTO subscription VALUES ('21', '0', '2020-02-04') ")
    c.execute("INSERT INTO subscription VALUES ('21', '1', '2020-02-11') ")
    c.execute("INSERT INTO subscription VALUES ('21', '2', '2020-06-03') ")
    c.execute("INSERT INTO subscription VALUES ('21', '4', '2020-09-27') ")
    c.execute("INSERT INTO subscription VALUES ('22', '0', '2020-01-10') ")
    c.execute("INSERT INTO subscription VALUES ('22', '2', '2020-01-17') ")
    c.execute("INSERT INTO subscription VALUES ('23', '0', '2020-05-13') ")
    c.execute("INSERT INTO subscription VALUES ('23', '3', '2020-05-20') ")
    c.execute("INSERT INTO subscription VALUES ('24', '0', '2020-11-10') ")
    c.execute("INSERT INTO subscription VALUES ('24', '2', '2020-11-17') ")
    c.execute("INSERT INTO subscription VALUES ('24', '3', '2021-04-17') ")
    c.execute("INSERT INTO subscription VALUES ('25', '0', '2020-05-10') ")
    c.execute("INSERT INTO subscription VALUES ('25', '1', '2020-05-17') ")
    c.execute("INSERT INTO subscription VALUES ('25', '2', '2020-06-16') ")
    c.execute("INSERT INTO subscription VALUES ('26', '0', '2020-12-08') ")
    c.execute("INSERT INTO subscription VALUES ('26', '2', '2020-12-15') ")
    c.execute("INSERT INTO subscription VALUES ('27', '0', '2020-08-24') ")
    c.execute("INSERT INTO subscription VALUES ('27', '2', '2020-08-31') ")
    c.execute("INSERT INTO subscription VALUES ('28', '0', '2020-06-30') ")
    c.execute("INSERT INTO subscription VALUES ('28', '3', '2020-07-07') ")
    c.execute("INSERT INTO subscription VALUES ('29', '0', '2020-01-23') ")
    c.execute("INSERT INTO subscription VALUES ('29', '2', '2020-01-30') ")
    c.execute("INSERT INTO subscription VALUES ('30', '0', '2020-04-29') ")
    c.execute("INSERT INTO subscription VALUES ('30', '1', '2020-05-06') ")
    c.execute("INSERT INTO subscription VALUES ('31', '0', '2020-06-22') ")
    c.execute("INSERT INTO subscription VALUES ('31', '2', '2020-06-29') ")
    c.execute("INSERT INTO subscription VALUES ('31', '3', '2020-11-29') ")
    c.execute("INSERT INTO subscription VALUES ('32', '0', '2020-06-12') ")
    c.execute("INSERT INTO subscription VALUES ('32', '1', '2020-06-19') ")
    c.execute("INSERT INTO subscription VALUES ('32', '2', '2020-07-18') ")
    c.execute("INSERT INTO subscription VALUES ('33', '0', '2020-09-03') ")
    c.execute("INSERT INTO subscription VALUES ('33', '2', '2020-09-10') ")
    c.execute("INSERT INTO subscription VALUES ('33', '4', '2021-02-05') ")
    c.execute("INSERT INTO subscription VALUES ('34', '0', '2020-12-20') ")
    c.execute("INSERT INTO subscription VALUES ('34', '1', '2020-12-27') ")
    c.execute("INSERT INTO subscription VALUES ('34', '2', '2021-03-26') ")
    c.execute("INSERT INTO subscription VALUES ('35', '0', '2020-09-03') ")
    c.execute("INSERT INTO subscription VALUES ('35', '2', '2020-09-10') ")
    c.execute("INSERT INTO subscription VALUES ('36', '0', '2020-02-25') ")
    c.execute("INSERT INTO subscription VALUES ('36', '2', '2020-03-03') ")
    c.execute("INSERT INTO subscription VALUES ('37', '0', '2020-08-05') ")
    c.execute("INSERT INTO subscription VALUES ('37', '1', '2020-08-12') ")
    c.execute("INSERT INTO subscription VALUES ('37', '2', '2020-11-11') ")
    c.execute("INSERT INTO subscription VALUES ('38', '0', '2020-10-02') ")
    c.execute("INSERT INTO subscription VALUES ('38', '2', '2020-10-09') ")
    c.execute("INSERT INTO subscription VALUES ('38', '3', '2020-11-09') ")
    c.execute("INSERT INTO subscription VALUES ('39', '0', '2020-05-28') ")
    c.execute("INSERT INTO subscription VALUES ('39', '1', '2020-06-04') ")
    c.execute("INSERT INTO subscription VALUES ('39', '2', '2020-08-25') ")
    c.execute("INSERT INTO subscription VALUES ('39', '4', '2020-09-10') ")
    c.execute("INSERT INTO subscription VALUES ('40', '0', '2020-01-22') ")
    c.execute("INSERT INTO subscription VALUES ('40', '1', '2020-01-29') ")
    c.execute("INSERT INTO subscription VALUES ('40', '2', '2020-03-25') ")
    c.execute("INSERT INTO subscription VALUES ('41', '0', '2020-05-16') ")
    c.execute("INSERT INTO subscription VALUES ('41', '2', '2020-05-23') ")
    c.execute("INSERT INTO subscription VALUES ('42', '0', '2020-10-27') ")
    c.execute("INSERT INTO subscription VALUES ('42', '1', '2020-11-03') ")
    c.execute("INSERT INTO subscription VALUES ('42', '2', '2021-04-28') ")
    c.execute("INSERT INTO subscription VALUES ('43', '0', '2020-08-13') ")
    c.execute("INSERT INTO subscription VALUES ('43', '1', '2020-08-20') ")
    c.execute("INSERT INTO subscription VALUES ('43', '2', '2020-12-18') ")
    c.execute("INSERT INTO subscription VALUES ('44', '0', '2020-03-17') ")
    c.execute("INSERT INTO subscription VALUES ('44', '3', '2020-03-24') ")
    c.execute("INSERT INTO subscription VALUES ('45', '0', '2020-02-11') ")
    c.execute("INSERT INTO subscription VALUES ('45', '1', '2020-02-18') ")
    c.execute("INSERT INTO subscription VALUES ('45', '2', '2020-08-12') ")
    c.execute("INSERT INTO subscription VALUES ('46', '0', '2020-04-19') ")
    c.execute("INSERT INTO subscription VALUES ('46', '1', '2020-04-26') ")
    c.execute("INSERT INTO subscription VALUES ('46', '2', '2020-07-06') ")
    c.execute("INSERT INTO subscription VALUES ('46', '3', '2020-08-06') ")
    c.execute("INSERT INTO subscription VALUES ('47', '0', '2020-06-06') ")
    c.execute("INSERT INTO subscription VALUES ('47', '1', '2020-06-13') ")
    c.execute("INSERT INTO subscription VALUES ('47', '3', '2020-10-26') ")
    c.execute("INSERT INTO subscription VALUES ('48', '0', '2020-01-11') ")
    c.execute("INSERT INTO subscription VALUES ('48', '1', '2020-01-18') ")
    c.execute("INSERT INTO subscription VALUES ('48', '4', '2020-06-01') ")
    c.execute("INSERT INTO subscription VALUES ('49', '0', '2020-04-24') ")
    c.execute("INSERT INTO subscription VALUES ('49', '2', '2020-05-01') ")
    c.execute("INSERT INTO subscription VALUES ('49', '3', '2020-08-01') ")
    c.execute("INSERT INTO subscription VALUES ('50', '0', '2020-07-21') ")
    c.execute("INSERT INTO subscription VALUES ('50', '2', '2020-07-28') ")
    c.execute("INSERT INTO subscription VALUES ('51', '0', '2020-01-19') ")
    c.execute("INSERT INTO subscription VALUES ('51', '1', '2020-01-26') ")
    c.execute("INSERT INTO subscription VALUES ('51', '3', '2020-03-09') ")
    c.execute("INSERT INTO subscription VALUES ('51', '4', '2021-03-09') ")
    c.execute("INSERT INTO subscription VALUES ('52', '0', '2020-05-31') ")
    c.execute("INSERT INTO subscription VALUES ('52', '1', '2020-06-07') ")
    c.execute("INSERT INTO subscription VALUES ('52', '4', '2020-07-05') ")
    c.execute("INSERT INTO subscription VALUES ('53', '0', '2020-01-18') ")
    c.execute("INSERT INTO subscription VALUES ('53', '1', '2020-01-25') ")
    c.execute("INSERT INTO subscription VALUES ('54', '0', '2020-05-23') ")
    c.execute("INSERT INTO subscription VALUES ('54', '2', '2020-05-30') ")
    c.execute("INSERT INTO subscription VALUES ('55', '0', '2020-10-22') ")
    c.execute("INSERT INTO subscription VALUES ('55', '1', '2020-10-29') ")
    c.execute("INSERT INTO subscription VALUES ('55', '3', '2021-03-01') ")
    c.execute("INSERT INTO subscription VALUES ('56', '0', '2020-01-03') ")
    c.execute("INSERT INTO subscription VALUES ('56', '3', '2020-01-10') ")
    c.execute("INSERT INTO subscription VALUES ('57', '0', '2020-03-03') ")
    c.execute("INSERT INTO subscription VALUES ('57', '2', '2020-03-10') ")
    c.execute("INSERT INTO subscription VALUES ('58', '0', '2020-07-04') ")
    c.execute("INSERT INTO subscription VALUES ('58', '1', '2020-07-11') ")
    c.execute("INSERT INTO subscription VALUES ('58', '3', '2020-09-24') ")
    c.execute("INSERT INTO subscription VALUES ('59', '0', '2020-10-30') ")
    c.execute("INSERT INTO subscription VALUES ('59', '1', '2020-11-06') ")
    c.execute("INSERT INTO subscription VALUES ('59', '4', '2021-04-29') ")
    c.execute("INSERT INTO subscription VALUES ('60', '0', '2020-06-17') ")
    c.execute("INSERT INTO subscription VALUES ('60', '1', '2020-06-24') ")
    c.execute("INSERT INTO subscription VALUES ('61', '0', '2020-08-31') ")
    c.execute("INSERT INTO subscription VALUES ('61', '1', '2020-09-07') ")
    c.execute("INSERT INTO subscription VALUES ('61', '3', '2021-02-13') ")
    c.execute("INSERT INTO subscription VALUES ('62', '0', '2020-10-12') ")
    c.execute("INSERT INTO subscription VALUES ('62', '1', '2020-10-19') ")
    c.execute("INSERT INTO subscription VALUES ('62', '2', '2021-01-02') ")
    c.execute("INSERT INTO subscription VALUES ('62', '4', '2021-02-23') ")
    c.execute("INSERT INTO subscription VALUES ('63', '0', '2020-05-28') ")
    c.execute("INSERT INTO subscription VALUES ('63', '1', '2020-06-04') ")
    c.execute("INSERT INTO subscription VALUES ('63', '4', '2020-06-18') ")
    c.execute("INSERT INTO subscription VALUES ('64', '0', '2020-03-08') ")
    c.execute("INSERT INTO subscription VALUES ('64', '1', '2020-03-15') ")
    c.execute("INSERT INTO subscription VALUES ('64', '2', '2020-04-03') ")
    c.execute("INSERT INTO subscription VALUES ('64', '4', '2020-04-27') ")
    c.execute("INSERT INTO subscription VALUES ('65', '0', '2020-05-12') ")
    c.execute("INSERT INTO subscription VALUES ('65', '1', '2020-05-19') ")
    c.execute("INSERT INTO subscription VALUES ('65', '2', '2020-10-09') ")
    c.execute("INSERT INTO subscription VALUES ('66', '0', '2020-07-30') ")
    c.execute("INSERT INTO subscription VALUES ('66', '1', '2020-08-06') ")
    c.execute("INSERT INTO subscription VALUES ('66', '3', '2020-10-04') ")
    c.execute("INSERT INTO subscription VALUES ('67', '0', '2020-08-14') ")
    c.execute("INSERT INTO subscription VALUES ('67', '2', '2020-08-21') ")
    c.execute("INSERT INTO subscription VALUES ('68', '0', '2020-04-10') ")
    c.execute("INSERT INTO subscription VALUES ('68', '3', '2020-04-17') ")
    c.execute("INSERT INTO subscription VALUES ('69', '0', '2020-03-07') ")
    c.execute("INSERT INTO subscription VALUES ('69', '1', '2020-03-14') ")
    c.execute("INSERT INTO subscription VALUES ('69', '2', '2020-04-14') ")
    c.execute("INSERT INTO subscription VALUES ('70', '0', '2020-07-06') ")
    c.execute("INSERT INTO subscription VALUES ('70', '1', '2020-07-13') ")
    c.execute("INSERT INTO subscription VALUES ('70', '2', '2021-01-06') ")
    c.execute("INSERT INTO subscription VALUES ('71', '0', '2020-07-23') ")
    c.execute("INSERT INTO subscription VALUES ('71', '2', '2020-07-30') ")
    c.execute("INSERT INTO subscription VALUES ('71', '4', '2020-12-08') ")
    c.execute("INSERT INTO subscription VALUES ('72', '0', '2020-12-10') ")
    c.execute("INSERT INTO subscription VALUES ('72', '2', '2020-12-17') ")
    c.execute("INSERT INTO subscription VALUES ('72', '4', '2021-02-01') ")
    c.execute("INSERT INTO subscription VALUES ('73', '0', '2020-03-24') ")
    c.execute("INSERT INTO subscription VALUES ('73', '1', '2020-03-31') ")
    c.execute("INSERT INTO subscription VALUES ('73', '2', '2020-05-13') ")
    c.execute("INSERT INTO subscription VALUES ('73', '3', '2020-10-13') ")
    c.execute("INSERT INTO subscription VALUES ('74', '0', '2020-05-24') ")
    c.execute("INSERT INTO subscription VALUES ('74', '1', '2020-05-31') ")
    c.execute("INSERT INTO subscription VALUES ('74', '3', '2020-10-01') ")
    c.execute("INSERT INTO subscription VALUES ('75', '0', '2020-07-14') ")
    c.execute("INSERT INTO subscription VALUES ('75', '1', '2020-07-21') ")
    c.execute("INSERT INTO subscription VALUES ('75', '2', '2020-11-19') ")
    c.execute("INSERT INTO subscription VALUES ('76', '0', '2020-08-31') ")
    c.execute("INSERT INTO subscription VALUES ('76', '3', '2020-09-07') ")
    c.execute("INSERT INTO subscription VALUES ('77', '0', '2020-04-18') ")
    c.execute("INSERT INTO subscription VALUES ('77', '2', '2020-04-25') ")
    c.execute("INSERT INTO subscription VALUES ('77', '3', '2020-10-25') ")
    c.execute("INSERT INTO subscription VALUES ('78', '0', '2020-09-03') ")
    c.execute("INSERT INTO subscription VALUES ('78', '2', '2020-09-10') ")
    c.execute("INSERT INTO subscription VALUES ('78', '4', '2021-02-19') ")
    c.execute("INSERT INTO subscription VALUES ('79', '0', '2020-07-30') ")
    c.execute("INSERT INTO subscription VALUES ('79', '2', '2020-08-06') ")
    c.execute("INSERT INTO subscription VALUES ('80', '0', '2020-09-23') ")
    c.execute("INSERT INTO subscription VALUES ('80', '2', '2020-09-30') ")
    c.execute("INSERT INTO subscription VALUES ('80', '4', '2021-01-17') ")
    c.execute("INSERT INTO subscription VALUES ('81', '0', '2020-05-29') ")
    c.execute("INSERT INTO subscription VALUES ('81', '2', '2020-06-05') ")
    c.execute("INSERT INTO subscription VALUES ('81', '4', '2020-10-20') ")
    c.execute("INSERT INTO subscription VALUES ('82', '0', '2020-05-02') ")
    c.execute("INSERT INTO subscription VALUES ('82', '1', '2020-05-09') ")
    c.execute("INSERT INTO subscription VALUES ('83', '0', '2020-05-18') ")
    c.execute("INSERT INTO subscription VALUES ('83', '1', '2020-05-25') ")
    c.execute("INSERT INTO subscription VALUES ('83', '2', '2020-10-29') ")
    c.execute("INSERT INTO subscription VALUES ('83', '3', '2021-04-29') ")
    c.execute("INSERT INTO subscription VALUES ('84', '0', '2020-06-14') ")
    c.execute("INSERT INTO subscription VALUES ('84', '1', '2020-06-21') ")
    c.execute("INSERT INTO subscription VALUES ('84', '4', '2020-07-07') ")
    c.execute("INSERT INTO subscription VALUES ('85', '0', '2020-08-13') ")
    c.execute("INSERT INTO subscription VALUES ('85', '1', '2020-08-20') ")
    c.execute("INSERT INTO subscription VALUES ('86', '0', '2020-07-10') ")
    c.execute("INSERT INTO subscription VALUES ('86', '3', '2020-07-17') ")
    c.execute("INSERT INTO subscription VALUES ('87', '0', '2020-08-08') ")
    c.execute("INSERT INTO subscription VALUES ('87', '2', '2020-08-15') ")
    c.execute("INSERT INTO subscription VALUES ('87', '3', '2020-09-15') ")
    c.execute("INSERT INTO subscription VALUES ('88', '0', '2020-12-30') ")
    c.execute("INSERT INTO subscription VALUES ('88', '2', '2021-01-06') ")
    c.execute("INSERT INTO subscription VALUES ('89', '0', '2020-03-05') ")
    c.execute("INSERT INTO subscription VALUES ('89', '2', '2020-03-12') ")
    c.execute("INSERT INTO subscription VALUES ('89', '4', '2020-09-02') ")
    c.execute("INSERT INTO subscription VALUES ('90', '0', '2020-11-25') ")
    c.execute("INSERT INTO subscription VALUES ('90', '1', '2020-12-02') ")
    c.execute("INSERT INTO subscription VALUES ('90', '2', '2021-03-28') ")
    c.execute("INSERT INTO subscription VALUES ('90', '3', '2021-04-28') ")
    c.execute("INSERT INTO subscription VALUES ('91', '0', '2020-09-08') ")
    c.execute("INSERT INTO subscription VALUES ('91', '2', '2020-09-15') ")
    c.execute("INSERT INTO subscription VALUES ('91', '4', '2021-03-04') ")
    c.execute("INSERT INTO subscription VALUES ('92', '0', '2020-11-02') ")
    c.execute("INSERT INTO subscription VALUES ('92', '1', '2020-11-09') ")
    c.execute("INSERT INTO subscription VALUES ('93', '0', '2020-03-14') ")
    c.execute("INSERT INTO subscription VALUES ('93', '2', '2020-03-21') ")
    c.execute("INSERT INTO subscription VALUES ('93', '4', '2020-08-30') ")
    c.execute("INSERT INTO subscription VALUES ('94', '0', '2020-12-09') ")
    c.execute("INSERT INTO subscription VALUES ('94', '2', '2020-12-16') ")
    c.execute("INSERT INTO subscription VALUES ('95', '0', '2020-11-02') ")
    c.execute("INSERT INTO subscription VALUES ('95', '1', '2020-11-09') ")
    c.execute("INSERT INTO subscription VALUES ('95', '2', '2021-03-16') ")
    c.execute("INSERT INTO subscription VALUES ('96', '0', '2020-08-22') ")
    c.execute("INSERT INTO subscription VALUES ('96', '1', '2020-08-29') ")
    c.execute("INSERT INTO subscription VALUES ('96', '3', '2021-01-23') ")
    c.execute("INSERT INTO subscription VALUES ('97', '0', '2020-10-29') ")
    c.execute("INSERT INTO subscription VALUES ('97', '1', '2020-11-05') ")
    c.execute("INSERT INTO subscription VALUES ('98', '0', '2020-01-05') ")
    c.execute("INSERT INTO subscription VALUES ('98', '1', '2020-01-12') ")
    c.execute("INSERT INTO subscription VALUES ('98', '2', '2020-01-22') ")
    c.execute("INSERT INTO subscription VALUES ('98', '4', '2020-04-05') ")
    c.execute("INSERT INTO subscription VALUES ('99', '0', '2020-12-05') ")
    c.execute("INSERT INTO subscription VALUES ('99', '4', '2020-12-12') ")
    c.execute("INSERT INTO subscription VALUES ('100', '0', '2020-06-02')")
    c.execute("INSERT INTO subscription VALUES ('100', '1', '2020-06-09')")
    c.execute("INSERT INTO subscription VALUES ('100', '2', '2020-09-11')")
    c.execute("INSERT INTO subscription VALUES ('101', '0', '2020-06-08')")
    c.execute("INSERT INTO subscription VALUES ('101', '1', '2020-06-15')")
    c.execute("INSERT INTO subscription VALUES ('101', '3', '2020-07-20')")
    c.execute("INSERT INTO subscription VALUES ('102', '0', '2020-06-02')")
    c.execute("INSERT INTO subscription VALUES ('102', '1', '2020-06-09')")
    c.execute("INSERT INTO subscription VALUES ('102', '2', '2020-06-18')")
    c.execute("INSERT INTO subscription VALUES ('102', '4', '2020-12-01')")
    c.execute("INSERT INTO subscription VALUES ('103', '0', '2020-07-24')")
    c.execute("INSERT INTO subscription VALUES ('103', '2', '2020-07-31')")
    c.execute("INSERT INTO subscription VALUES ('103', '4', '2020-10-28')")
    c.execute("INSERT INTO subscription VALUES ('104', '0', '2020-03-29')")
    c.execute("INSERT INTO subscription VALUES ('104', '2', '2020-04-05')")
    c.execute("INSERT INTO subscription VALUES ('105', '0', '2020-09-20')")
    c.execute("INSERT INTO subscription VALUES ('105', '1', '2020-09-27')")
    c.execute("INSERT INTO subscription VALUES ('105', '3', '2020-10-22')")
    c.execute("INSERT INTO subscription VALUES ('106', '0', '2020-08-02')")
    c.execute("INSERT INTO subscription VALUES ('106', '3', '2020-08-09')")
    c.execute("INSERT INTO subscription VALUES ('107', '0', '2020-01-12')")
    c.execute("INSERT INTO subscription VALUES ('107', '1', '2020-01-19')")
    c.execute("INSERT INTO subscription VALUES ('107', '2', '2020-03-23')")
    c.execute("INSERT INTO subscription VALUES ('108', '0', '2020-09-10')")
    c.execute("INSERT INTO subscription VALUES ('108', '4', '2020-09-17')")
    c.execute("INSERT INTO subscription VALUES ('109', '0', '2020-10-12')")
    c.execute("INSERT INTO subscription VALUES ('109', '1', '2020-10-19')")
    c.execute("INSERT INTO subscription VALUES ('109', '2', '2021-03-20')")
    c.execute("INSERT INTO subscription VALUES ('110', '0', '2020-05-12')")
    c.execute("INSERT INTO subscription VALUES ('110', '2', '2020-05-19')")
    c.execute("INSERT INTO subscription VALUES ('111', '0', '2020-08-25')")
    c.execute("INSERT INTO subscription VALUES ('111', '3', '2020-09-01')")
    c.execute("INSERT INTO subscription VALUES ('112', '0', '2020-10-20')")
    c.execute("INSERT INTO subscription VALUES ('112', '2', '2020-10-27')")
    c.execute("INSERT INTO subscription VALUES ('112', '4', '2021-01-08')")
    c.execute("INSERT INTO subscription VALUES ('113', '0', '2020-04-10')")
    c.execute("INSERT INTO subscription VALUES ('113', '1', '2020-04-17')")
    c.execute("INSERT INTO subscription VALUES ('113', '2', '2020-09-13')")
    c.execute("INSERT INTO subscription VALUES ('113', '4', '2020-11-01')")
    c.execute("INSERT INTO subscription VALUES ('114', '0', '2020-06-05')")
    c.execute("INSERT INTO subscription VALUES ('114', '1', '2020-06-12')")
    c.execute("INSERT INTO subscription VALUES ('114', '3', '2020-09-13')")
    c.execute("INSERT INTO subscription VALUES ('115', '0', '2020-08-14')")
    c.execute("INSERT INTO subscription VALUES ('115', '3', '2020-08-21')")
    c.execute("INSERT INTO subscription VALUES ('116', '0', '2020-05-23')")
    c.execute("INSERT INTO subscription VALUES ('116', '1', '2020-05-30')")
    c.execute("INSERT INTO subscription VALUES ('116', '4', '2020-09-15')")
    c.execute("INSERT INTO subscription VALUES ('117', '0', '2020-05-22')")
    c.execute("INSERT INTO subscription VALUES ('117', '1', '2020-05-29')")
    c.execute("INSERT INTO subscription VALUES ('117', '3', '2020-11-14')")
    c.execute("INSERT INTO subscription VALUES ('118', '0', '2020-01-24')")
    c.execute("INSERT INTO subscription VALUES ('118', '1', '2020-01-31')")
    c.execute("INSERT INTO subscription VALUES ('118', '4', '2020-06-30')")
    c.execute("INSERT INTO subscription VALUES ('119', '0', '2020-11-09')")
    c.execute("INSERT INTO subscription VALUES ('119', '1', '2020-11-16')")
    c.execute("INSERT INTO subscription VALUES ('119', '3', '2021-02-27')")
    c.execute("INSERT INTO subscription VALUES ('120', '0', '2020-05-14')")
    c.execute("INSERT INTO subscription VALUES ('120', '2', '2020-05-21')")
    c.execute("INSERT INTO subscription VALUES ('120', '3', '2020-09-21')")
    c.execute("INSERT INTO subscription VALUES ('121', '0', '2020-06-18')")
    c.execute("INSERT INTO subscription VALUES ('121', '1', '2020-06-25')")
    c.execute("INSERT INTO subscription VALUES ('121', '3', '2020-10-07')")
    c.execute("INSERT INTO subscription VALUES ('122', '0', '2020-03-30')")
    c.execute("INSERT INTO subscription VALUES ('122', '4', '2020-04-06')")
    c.execute("INSERT INTO subscription VALUES ('123', '0', '2020-03-12')")
    c.execute("INSERT INTO subscription VALUES ('123', '1', '2020-03-19')")
    c.execute("INSERT INTO subscription VALUES ('123', '4', '2020-05-15')")
    c.execute("INSERT INTO subscription VALUES ('124', '0', '2020-03-17')")
    c.execute("INSERT INTO subscription VALUES ('124', '1', '2020-03-24')")
    c.execute("INSERT INTO subscription VALUES ('124', '3', '2020-06-20')")
    c.execute("INSERT INTO subscription VALUES ('125', '0', '2020-08-07')")
    c.execute("INSERT INTO subscription VALUES ('125', '1', '2020-08-14')")
    c.execute("INSERT INTO subscription VALUES ('125', '4', '2020-12-03')")
    c.execute("INSERT INTO subscription VALUES ('126', '0', '2020-09-15')")
    c.execute("INSERT INTO subscription VALUES ('126', '1', '2020-09-22')")
    c.execute("INSERT INTO subscription VALUES ('127', '0', '2020-05-23')")
    c.execute("INSERT INTO subscription VALUES ('127', '2', '2020-05-30')")
    c.execute("INSERT INTO subscription VALUES ('127', '4', '2020-08-11')")
    c.execute("INSERT INTO subscription VALUES ('128', '0', '2020-01-19')")
    c.execute("INSERT INTO subscription VALUES ('128', '4', '2020-01-26')")
    c.execute("INSERT INTO subscription VALUES ('129', '0', '2020-07-23')")
    c.execute("INSERT INTO subscription VALUES ('129', '1', '2020-07-30')")
    c.execute("INSERT INTO subscription VALUES ('130', '0', '2020-09-22')")
    c.execute("INSERT INTO subscription VALUES ('130', '2', '2020-09-29')")
    c.execute("INSERT INTO subscription VALUES ('131', '0', '2020-10-16')")
    c.execute("INSERT INTO subscription VALUES ('131', '3', '2020-10-23')")
    c.execute("INSERT INTO subscription VALUES ('132', '0', '2020-10-18')")
    c.execute("INSERT INTO subscription VALUES ('132', '1', '2020-10-25')")
    c.execute("INSERT INTO subscription VALUES ('132', '4', '2021-01-07')")
    c.execute("INSERT INTO subscription VALUES ('133', '0', '2020-03-29')")
    c.execute("INSERT INTO subscription VALUES ('133', '1', '2020-04-05')")
    c.execute("INSERT INTO subscription VALUES ('133', '3', '2020-07-11')")
    c.execute("INSERT INTO subscription VALUES ('134', '0', '2020-07-02')")
    c.execute("INSERT INTO subscription VALUES ('134', '2', '2020-07-09')")
    c.execute("INSERT INTO subscription VALUES ('135', '0', '2020-12-23')")
    c.execute("INSERT INTO subscription VALUES ('135', '4', '2020-12-30')")
    c.execute("INSERT INTO subscription VALUES ('136', '0', '2020-08-16')")
    c.execute("INSERT INTO subscription VALUES ('136', '4', '2020-08-23')")
    c.execute("INSERT INTO subscription VALUES ('137', '0', '2020-08-12')")
    c.execute("INSERT INTO subscription VALUES ('137', '2', '2020-08-19')")
    c.execute("INSERT INTO subscription VALUES ('138', '0', '2020-10-26')")
    c.execute("INSERT INTO subscription VALUES ('138', '1', '2020-11-02')")
    c.execute("INSERT INTO subscription VALUES ('138', '2', '2020-12-25')")
    c.execute("INSERT INTO subscription VALUES ('138', '3', '2021-01-25')")
    c.execute("INSERT INTO subscription VALUES ('139', '0', '2020-07-17')")
    c.execute("INSERT INTO subscription VALUES ('139', '2', '2020-07-24')")
    c.execute("INSERT INTO subscription VALUES ('140', '0', '2020-12-25')")
    c.execute("INSERT INTO subscription VALUES ('140', '1', '2021-01-01')")
    c.execute("INSERT INTO subscription VALUES ('141', '0', '2020-04-19')")
    c.execute("INSERT INTO subscription VALUES ('141', '1', '2020-04-26')")
    c.execute("INSERT INTO subscription VALUES ('141', '3', '2020-10-18')")
    c.execute("INSERT INTO subscription VALUES ('142', '0', '2020-05-30')")
    c.execute("INSERT INTO subscription VALUES ('142', '2', '2020-06-06')")
    c.execute("INSERT INTO subscription VALUES ('143', '0', '2020-12-20')")
    c.execute("INSERT INTO subscription VALUES ('143', '1', '2020-12-27')")
    c.execute("INSERT INTO subscription VALUES ('143', '4', '2021-03-03')")
    c.execute("INSERT INTO subscription VALUES ('144', '0', '2020-09-04')")
    c.execute("INSERT INTO subscription VALUES ('144', '1', '2020-09-11')")
    c.execute("INSERT INTO subscription VALUES ('144', '2', '2021-02-09')")
    c.execute("INSERT INTO subscription VALUES ('145', '0', '2020-01-17')")
    c.execute("INSERT INTO subscription VALUES ('145', '2', '2020-01-24')")
    c.execute("INSERT INTO subscription VALUES ('146', '0', '2020-07-05')")
    c.execute("INSERT INTO subscription VALUES ('146', '1', '2020-07-12')")
    c.execute("INSERT INTO subscription VALUES ('146', '2', '2020-10-28')")
    c.execute("INSERT INTO subscription VALUES ('146', '4', '2020-12-18')")
    c.execute("INSERT INTO subscription VALUES ('147', '0', '2020-12-18')")
    c.execute("INSERT INTO subscription VALUES ('147', '2', '2020-12-25')")
    c.execute("INSERT INTO subscription VALUES ('148', '0', '2020-03-12')")
    c.execute("INSERT INTO subscription VALUES ('148', '2', '2020-03-19')")
    c.execute("INSERT INTO subscription VALUES ('149', '0', '2020-12-19')")
    c.execute("INSERT INTO subscription VALUES ('149', '1', '2020-12-26')")
    c.execute("INSERT INTO subscription VALUES ('150', '0', '2020-02-05')")
    c.execute("INSERT INTO subscription VALUES ('150', '2', '2020-02-12')")
    c.execute("INSERT INTO subscription VALUES ('151', '0', '2020-09-07')")
    c.execute("INSERT INTO subscription VALUES ('151', '1', '2020-09-14')")
    c.execute("INSERT INTO subscription VALUES ('151', '2', '2020-09-17')")
    c.execute("INSERT INTO subscription VALUES ('152', '0', '2020-10-14')")
    c.execute("INSERT INTO subscription VALUES ('152', '1', '2020-10-21')")
    c.execute("INSERT INTO subscription VALUES ('152', '2', '2021-03-08')")
    c.execute("INSERT INTO subscription VALUES ('153', '0', '2020-11-28')")
    c.execute("INSERT INTO subscription VALUES ('153', '2', '2020-12-05')")
    c.execute("INSERT INTO subscription VALUES ('154', '0', '2020-03-18')")
    c.execute("INSERT INTO subscription VALUES ('154', '1', '2020-03-25')")
    c.execute("INSERT INTO subscription VALUES ('154', '2', '2020-05-01')")
    c.execute("INSERT INTO subscription VALUES ('155', '0', '2020-09-13')")
    c.execute("INSERT INTO subscription VALUES ('155', '4', '2020-09-20')")
    c.execute("INSERT INTO subscription VALUES ('156', '0', '2020-01-19')")
    c.execute("INSERT INTO subscription VALUES ('156', '4', '2020-01-26')")
    c.execute("INSERT INTO subscription VALUES ('157', '0', '2020-04-23')")
    c.execute("INSERT INTO subscription VALUES ('157', '1', '2020-04-30')")
    c.execute("INSERT INTO subscription VALUES ('157', '3', '2020-05-11')")
    c.execute("INSERT INTO subscription VALUES ('158', '0', '2020-03-02')")
    c.execute("INSERT INTO subscription VALUES ('158', '1', '2020-03-09')")
    c.execute("INSERT INTO subscription VALUES ('158', '2', '2020-05-09')")
    c.execute("INSERT INTO subscription VALUES ('159', '0', '2020-09-09')")
    c.execute("INSERT INTO subscription VALUES ('159', '2', '2020-09-16')")
    c.execute("INSERT INTO subscription VALUES ('160', '0', '2020-11-16')")
    c.execute("INSERT INTO subscription VALUES ('160', '1', '2020-11-23')")
    c.execute("INSERT INTO subscription VALUES ('161', '0', '2020-12-17')")
    c.execute("INSERT INTO subscription VALUES ('161', '4', '2020-12-24')")
    c.execute("INSERT INTO subscription VALUES ('162', '0', '2020-02-23')")
    c.execute("INSERT INTO subscription VALUES ('162', '4', '2020-03-01')")
    c.execute("INSERT INTO subscription VALUES ('163', '0', '2020-12-23')")
    c.execute("INSERT INTO subscription VALUES ('163', '2', '2020-12-30')")
    c.execute("INSERT INTO subscription VALUES ('164', '0', '2020-11-27')")
    c.execute("INSERT INTO subscription VALUES ('164', '2', '2020-12-04')")
    c.execute("INSERT INTO subscription VALUES ('164', '4', '2020-12-24')")
    c.execute("INSERT INTO subscription VALUES ('165', '0', '2020-10-05')")
    c.execute("INSERT INTO subscription VALUES ('165', '1', '2020-10-12')")
    c.execute("INSERT INTO subscription VALUES ('165', '3', '2020-11-08')")
    c.execute("INSERT INTO subscription VALUES ('166', '0', '2020-07-03')")
    c.execute("INSERT INTO subscription VALUES ('166', '1', '2020-07-10')")
    c.execute("INSERT INTO subscription VALUES ('166', '4', '2020-09-22')")
    c.execute("INSERT INTO subscription VALUES ('167', '0', '2020-05-07')")
    c.execute("INSERT INTO subscription VALUES ('167', '2', '2020-05-14')")
    c.execute("INSERT INTO subscription VALUES ('168', '0', '2020-03-07')")
    c.execute("INSERT INTO subscription VALUES ('168', '2', '2020-03-14')")
    c.execute("INSERT INTO subscription VALUES ('169', '0', '2020-04-07')")
    c.execute("INSERT INTO subscription VALUES ('169', '4', '2020-04-14')")
    c.execute("INSERT INTO subscription VALUES ('170', '0', '2020-04-18')")
    c.execute("INSERT INTO subscription VALUES ('170', '1', '2020-04-25')")
    c.execute("INSERT INTO subscription VALUES ('170', '2', '2020-08-28')")
    c.execute("INSERT INTO subscription VALUES ('170', '3', '2020-12-28')")
    c.execute("INSERT INTO subscription VALUES ('171', '0', '2020-11-28')")
    c.execute("INSERT INTO subscription VALUES ('171', '2', '2020-12-05')")
    c.execute("INSERT INTO subscription VALUES ('172', '0', '2020-12-05')")
    c.execute("INSERT INTO subscription VALUES ('172', '1', '2020-12-12')")
    c.execute("INSERT INTO subscription VALUES ('172', '4', '2021-02-15')")
    c.execute("INSERT INTO subscription VALUES ('173', '0', '2020-06-24')")
    c.execute("INSERT INTO subscription VALUES ('173', '2', '2020-07-01')")
    c.execute("INSERT INTO subscription VALUES ('174', '0', '2020-02-01')")
    c.execute("INSERT INTO subscription VALUES ('174', '1', '2020-02-08')")
    c.execute("INSERT INTO subscription VALUES ('174', '3', '2020-07-10')")
    c.execute("INSERT INTO subscription VALUES ('175', '0', '2020-08-15')")
    c.execute("INSERT INTO subscription VALUES ('175', '2', '2020-08-22')")
    c.execute("INSERT INTO subscription VALUES ('175', '4', '2020-11-23')")
    c.execute("INSERT INTO subscription VALUES ('176', '0', '2020-09-13')")
    c.execute("INSERT INTO subscription VALUES ('176', '1', '2020-09-20')")
    c.execute("INSERT INTO subscription VALUES ('177', '0', '2020-05-01')")
    c.execute("INSERT INTO subscription VALUES ('177', '2', '2020-05-08')")
    c.execute("INSERT INTO subscription VALUES ('177', '4', '2020-09-09')")
    c.execute("INSERT INTO subscription VALUES ('178', '0', '2020-02-22')")
    c.execute("INSERT INTO subscription VALUES ('178', '4', '2020-02-29')")
    c.execute("INSERT INTO subscription VALUES ('179', '0', '2020-06-13')")
    c.execute("INSERT INTO subscription VALUES ('179', '2', '2020-06-20')")
    c.execute("INSERT INTO subscription VALUES ('179', '4', '2020-09-25')")
    c.execute("INSERT INTO subscription VALUES ('180', '0', '2020-10-31')")
    c.execute("INSERT INTO subscription VALUES ('180', '1', '2020-11-07')")
    c.execute("INSERT INTO subscription VALUES ('180', '2', '2021-01-17')")
    c.execute("INSERT INTO subscription VALUES ('181', '0', '2020-02-11')")
    c.execute("INSERT INTO subscription VALUES ('181', '2', '2020-02-18')")
    c.execute("INSERT INTO subscription VALUES ('182', '0', '2020-09-26')")
    c.execute("INSERT INTO subscription VALUES ('182', '1', '2020-10-03')")
    c.execute("INSERT INTO subscription VALUES ('182', '4', '2021-02-25')")
    c.execute("INSERT INTO subscription VALUES ('183', '0', '2020-09-25')")
    c.execute("INSERT INTO subscription VALUES ('183', '2', '2020-10-02')")
    c.execute("INSERT INTO subscription VALUES ('184', '0', '2020-02-16')")
    c.execute("INSERT INTO subscription VALUES ('184', '1', '2020-02-23')")
    c.execute("INSERT INTO subscription VALUES ('185', '0', '2020-12-03')")
    c.execute("INSERT INTO subscription VALUES ('185', '2', '2020-12-10')")
    c.execute("INSERT INTO subscription VALUES ('186', '0', '2020-09-30')")
    c.execute("INSERT INTO subscription VALUES ('186', '2', '2020-10-07')")
    c.execute("INSERT INTO subscription VALUES ('186', '4', '2021-02-05')")
    c.execute("INSERT INTO subscription VALUES ('187', '0', '2020-09-19')")
    c.execute("INSERT INTO subscription VALUES ('187', '3', '2020-09-26')")
    c.execute("INSERT INTO subscription VALUES ('188', '0', '2020-02-22')")
    c.execute("INSERT INTO subscription VALUES ('188', '1', '2020-02-29')")
    c.execute("INSERT INTO subscription VALUES ('189', '0', '2020-12-09')")
    c.execute("INSERT INTO subscription VALUES ('189', '2', '2020-12-16')")
    c.execute("INSERT INTO subscription VALUES ('190', '0', '2020-04-20')")
    c.execute("INSERT INTO subscription VALUES ('190', '1', '2020-04-27')")
    c.execute("INSERT INTO subscription VALUES ('190', '3', '2020-09-04')")
    c.execute("INSERT INTO subscription VALUES ('191', '0', '2020-01-02')")
    c.execute("INSERT INTO subscription VALUES ('191', '2', '2020-01-09')")
    c.execute("INSERT INTO subscription VALUES ('192', '0', '2020-07-29')")
    c.execute("INSERT INTO subscription VALUES ('192', '1', '2020-08-05')")
    c.execute("INSERT INTO subscription VALUES ('193', '0', '2020-05-19')")
    c.execute("INSERT INTO subscription VALUES ('193', '1', '2020-05-26')")
    c.execute("INSERT INTO subscription VALUES ('193', '2', '2020-09-21')")
    c.execute("INSERT INTO subscription VALUES ('193', '3', '2020-10-21')")
    c.execute("INSERT INTO subscription VALUES ('194', '0', '2020-11-20')")
    c.execute("INSERT INTO subscription VALUES ('194', '2', '2020-11-27')")
    c.execute("INSERT INTO subscription VALUES ('194', '4', '2021-01-13')")
    c.execute("INSERT INTO subscription VALUES ('195', '0', '2020-02-08')")
    c.execute("INSERT INTO subscription VALUES ('195', '2', '2020-02-15')")
    c.execute("INSERT INTO subscription VALUES ('195', '3', '2020-06-15')")
    c.execute("INSERT INTO subscription VALUES ('196', '0', '2020-03-09')")
    c.execute("INSERT INTO subscription VALUES ('196', '2', '2020-03-16')")
    c.execute("INSERT INTO subscription VALUES ('197', '0', '2020-05-17')")
    c.execute("INSERT INTO subscription VALUES ('197', '2', '2020-05-24')")
    c.execute("INSERT INTO subscription VALUES ('197', '4', '2020-07-01')")
    c.execute("INSERT INTO subscription VALUES ('198', '0', '2020-11-11')")
    c.execute("INSERT INTO subscription VALUES ('198', '1', '2020-11-18')")
    c.execute("INSERT INTO subscription VALUES ('198', '4', '2021-03-16')")
    c.execute("INSERT INTO subscription VALUES ('199', '0', '2020-12-09')")
    c.execute("INSERT INTO subscription VALUES ('199', '2', '2020-12-16')")
    c.execute("INSERT INTO subscription VALUES ('200', '0', '2020-04-05')")
    c.execute("INSERT INTO subscription VALUES ('200', '2', '2020-04-12')")
    c.execute("INSERT INTO subscription VALUES ('201', '0', '2020-03-07')")
    c.execute("INSERT INTO subscription VALUES ('201', '1', '2020-03-14')")
    c.execute("INSERT INTO subscription VALUES ('202', '0', '2020-07-01')")
    c.execute("INSERT INTO subscription VALUES ('202', '2', '2020-07-08')")
    c.execute("INSERT INTO subscription VALUES ('203', '0', '2020-08-24')")
    c.execute("INSERT INTO subscription VALUES ('203', '1', '2020-08-31')")
    c.execute("INSERT INTO subscription VALUES ('203', '3', '2020-09-19')")
    c.execute("INSERT INTO subscription VALUES ('204', '0', '2020-06-10')")
    c.execute("INSERT INTO subscription VALUES ('204', '1', '2020-06-17')")
    c.execute("INSERT INTO subscription VALUES ('204', '4', '2020-10-05')")
    c.execute("INSERT INTO subscription VALUES ('205', '0', '2020-11-02')")
    c.execute("INSERT INTO subscription VALUES ('205', '1', '2020-11-09')")
    c.execute("INSERT INTO subscription VALUES ('205', '3', '2021-03-13')")
    c.execute("INSERT INTO subscription VALUES ('206', '0', '2020-03-17')")
    c.execute("INSERT INTO subscription VALUES ('206', '1', '2020-03-24')")
    c.execute("INSERT INTO subscription VALUES ('206', '3', '2020-09-02')")
    c.execute("INSERT INTO subscription VALUES ('207', '0', '2020-05-20')")
    c.execute("INSERT INTO subscription VALUES ('207', '1', '2020-05-27')")
    c.execute("INSERT INTO subscription VALUES ('208', '0', '2020-06-12')")
    c.execute("INSERT INTO subscription VALUES ('208', '2', '2020-06-19')")
    c.execute("INSERT INTO subscription VALUES ('208', '3', '2020-09-19')")
    c.execute("INSERT INTO subscription VALUES ('209', '0', '2020-08-13')")
    c.execute("INSERT INTO subscription VALUES ('209', '2', '2020-08-20')")
    c.execute("INSERT INTO subscription VALUES ('210', '0', '2020-02-09')")
    c.execute("INSERT INTO subscription VALUES ('210', '2', '2020-02-16')")
    c.execute("INSERT INTO subscription VALUES ('210', '4', '2020-06-21')")
    c.execute("INSERT INTO subscription VALUES ('211', '0', '2020-10-10')")
    c.execute("INSERT INTO subscription VALUES ('211', '1', '2020-10-17')")
    c.execute("INSERT INTO subscription VALUES ('211', '3', '2020-10-18')")
    c.execute("INSERT INTO subscription VALUES ('212', '0', '2020-03-02')")
    c.execute("INSERT INTO subscription VALUES ('212', '1', '2020-03-09')")
    c.execute("INSERT INTO subscription VALUES ('213', '0', '2020-08-07')")
    c.execute("INSERT INTO subscription VALUES ('213', '3', '2020-08-14')")
    c.execute("INSERT INTO subscription VALUES ('214', '0', '2020-02-03')")
    c.execute("INSERT INTO subscription VALUES ('214', '1', '2020-02-10')")
    c.execute("INSERT INTO subscription VALUES ('214', '2', '2020-05-07')")
    c.execute("INSERT INTO subscription VALUES ('214', '4', '2020-08-21')")
    c.execute("INSERT INTO subscription VALUES ('215', '0', '2020-04-16')")
    c.execute("INSERT INTO subscription VALUES ('215', '2', '2020-04-23')")
    c.execute("INSERT INTO subscription VALUES ('215', '3', '2020-07-23')")
    c.execute("INSERT INTO subscription VALUES ('216', '0', '2020-08-26')")
    c.execute("INSERT INTO subscription VALUES ('216', '2', '2020-09-02')")
    c.execute("INSERT INTO subscription VALUES ('217', '0', '2020-12-06')")
    c.execute("INSERT INTO subscription VALUES ('217', '2', '2020-12-13')")
    c.execute("INSERT INTO subscription VALUES ('218', '0', '2020-12-02')")
    c.execute("INSERT INTO subscription VALUES ('218', '1', '2020-12-09')")
    c.execute("INSERT INTO subscription VALUES ('218', '4', '2021-04-24')")
    c.execute("INSERT INTO subscription VALUES ('219', '0', '2020-10-22')")
    c.execute("INSERT INTO subscription VALUES ('219', '2', '2020-10-29')")
    c.execute("INSERT INTO subscription VALUES ('219', '3', '2021-04-29')")
    c.execute("INSERT INTO subscription VALUES ('220', '0', '2020-06-08')")
    c.execute("INSERT INTO subscription VALUES ('220', '4', '2020-06-15')")
    c.execute("INSERT INTO subscription VALUES ('221', '0', '2020-09-27')")
    c.execute("INSERT INTO subscription VALUES ('221', '1', '2020-10-04')")
    c.execute("INSERT INTO subscription VALUES ('221', '3', '2021-03-29')")
    c.execute("INSERT INTO subscription VALUES ('222', '0', '2020-08-29')")
    c.execute("INSERT INTO subscription VALUES ('222', '1', '2020-09-05')")
    c.execute("INSERT INTO subscription VALUES ('222', '4', '2020-12-25')")
    c.execute("INSERT INTO subscription VALUES ('223', '0', '2020-08-01')")
    c.execute("INSERT INTO subscription VALUES ('223', '1', '2020-08-08')")
    c.execute("INSERT INTO subscription VALUES ('223', '3', '2021-01-31')")
    c.execute("INSERT INTO subscription VALUES ('224', '0', '2020-01-26')")
    c.execute("INSERT INTO subscription VALUES ('224', '2', '2020-02-02')")
    c.execute("INSERT INTO subscription VALUES ('224', '3', '2020-05-02')")
    c.execute("INSERT INTO subscription VALUES ('225', '0', '2020-12-27')")
    c.execute("INSERT INTO subscription VALUES ('225', '4', '2021-01-03')")
    c.execute("INSERT INTO subscription VALUES ('226', '0', '2020-11-01')")
    c.execute("INSERT INTO subscription VALUES ('226', '1', '2020-11-08')")
    c.execute("INSERT INTO subscription VALUES ('226', '2', '2020-11-24')")
    c.execute("INSERT INTO subscription VALUES ('227', '0', '2020-03-02')")
    c.execute("INSERT INTO subscription VALUES ('227', '2', '2020-03-09')")
    c.execute("INSERT INTO subscription VALUES ('227', '3', '2020-08-09')")
    c.execute("INSERT INTO subscription VALUES ('228', '0', '2020-10-02')")
    c.execute("INSERT INTO subscription VALUES ('228', '2', '2020-10-09')")
    c.execute("INSERT INTO subscription VALUES ('228', '3', '2021-02-09')")
    c.execute("INSERT INTO subscription VALUES ('229', '0', '2020-07-24')")
    c.execute("INSERT INTO subscription VALUES ('229', '1', '2020-07-31')")
    c.execute("INSERT INTO subscription VALUES ('229', '4', '2021-01-24')")
    c.execute("INSERT INTO subscription VALUES ('230', '0', '2020-04-08')")
    c.execute("INSERT INTO subscription VALUES ('230', '4', '2020-04-15')")
    c.execute("INSERT INTO subscription VALUES ('231', '0', '2020-05-13')")
    c.execute("INSERT INTO subscription VALUES ('231', '1', '2020-05-20')")
    c.execute("INSERT INTO subscription VALUES ('231', '2', '2020-07-09')")
    c.execute("INSERT INTO subscription VALUES ('232', '0', '2020-08-26')")
    c.execute("INSERT INTO subscription VALUES ('232', '1', '2020-09-02')")
    c.execute("INSERT INTO subscription VALUES ('232', '2', '2021-02-03')")
    c.execute("INSERT INTO subscription VALUES ('233', '0', '2020-07-31')")
    c.execute("INSERT INTO subscription VALUES ('233', '1', '2020-08-07')")
    c.execute("INSERT INTO subscription VALUES ('233', '3', '2020-10-29')")
    c.execute("INSERT INTO subscription VALUES ('234', '0', '2020-01-19')")
    c.execute("INSERT INTO subscription VALUES ('234', '2', '2020-01-26')")
    c.execute("INSERT INTO subscription VALUES ('235', '0', '2020-08-20')")
    c.execute("INSERT INTO subscription VALUES ('235', '1', '2020-08-27')")
    c.execute("INSERT INTO subscription VALUES ('235', '2', '2020-10-17')")
    c.execute("INSERT INTO subscription VALUES ('236', '0', '2020-06-22')")
    c.execute("INSERT INTO subscription VALUES ('236', '1', '2020-06-29')")
    c.execute("INSERT INTO subscription VALUES ('237', '0', '2020-11-07')")
    c.execute("INSERT INTO subscription VALUES ('237', '1', '2020-11-14')")
    c.execute("INSERT INTO subscription VALUES ('237', '2', '2021-03-24')")
    c.execute("INSERT INTO subscription VALUES ('238', '0', '2020-10-27')")
    c.execute("INSERT INTO subscription VALUES ('238', '1', '2020-11-03')")
    c.execute("INSERT INTO subscription VALUES ('238', '3', '2020-12-23')")
    c.execute("INSERT INTO subscription VALUES ('239', '0', '2020-08-15')")
    c.execute("INSERT INTO subscription VALUES ('239', '1', '2020-08-22')")
    c.execute("INSERT INTO subscription VALUES ('239', '4', '2020-10-20')")
    c.execute("INSERT INTO subscription VALUES ('240', '0', '2020-01-14')")
    c.execute("INSERT INTO subscription VALUES ('240', '1', '2020-01-21')")
    c.execute("INSERT INTO subscription VALUES ('240', '3', '2020-03-03')")
    c.execute("INSERT INTO subscription VALUES ('240', '4', '2021-03-03')")
    c.execute("INSERT INTO subscription VALUES ('241', '0', '2020-10-03')")
    c.execute("INSERT INTO subscription VALUES ('241', '1', '2020-10-10')")
    c.execute("INSERT INTO subscription VALUES ('241', '3', '2020-11-11')")
    c.execute("INSERT INTO subscription VALUES ('242', '0', '2020-10-19')")
    c.execute("INSERT INTO subscription VALUES ('242', '2', '2020-10-26')")
    c.execute("INSERT INTO subscription VALUES ('243', '0', '2020-09-04')")
    c.execute("INSERT INTO subscription VALUES ('243', '1', '2020-09-11')")
    c.execute("INSERT INTO subscription VALUES ('244', '0', '2020-03-04')")
    c.execute("INSERT INTO subscription VALUES ('244', '2', '2020-03-11')")
    c.execute("INSERT INTO subscription VALUES ('245', '0', '2020-03-28')")
    c.execute("INSERT INTO subscription VALUES ('245', '4', '2020-04-04')")
    c.execute("INSERT INTO subscription VALUES ('246', '0', '2020-01-27')")
    c.execute("INSERT INTO subscription VALUES ('246', '1', '2020-02-03')")
    c.execute("INSERT INTO subscription VALUES ('247', '0', '2020-07-07')")
    c.execute("INSERT INTO subscription VALUES ('247', '1', '2020-07-14')")
    c.execute("INSERT INTO subscription VALUES ('247', '2', '2020-08-20')")
    c.execute("INSERT INTO subscription VALUES ('248', '0', '2020-11-09')")
    c.execute("INSERT INTO subscription VALUES ('248', '1', '2020-11-16')")
    c.execute("INSERT INTO subscription VALUES ('249', '0', '2020-02-18')")
    c.execute("INSERT INTO subscription VALUES ('249', '2', '2020-02-25')")
    c.execute("INSERT INTO subscription VALUES ('250', '0', '2020-06-15')")
    c.execute("INSERT INTO subscription VALUES ('250', '2', '2020-06-22')")
    c.execute("INSERT INTO subscription VALUES ('250', '3', '2020-09-22')")
    c.execute("INSERT INTO subscription VALUES ('251', '0', '2020-03-09')")
    c.execute("INSERT INTO subscription VALUES ('251', '4', '2020-03-16')")
    c.execute("INSERT INTO subscription VALUES ('252', '0', '2020-11-08')")
    c.execute("INSERT INTO subscription VALUES ('252', '1', '2020-11-15')")
    c.execute("INSERT INTO subscription VALUES ('252', '2', '2020-12-23')")
    c.execute("INSERT INTO subscription VALUES ('253', '0', '2020-05-15')")
    c.execute("INSERT INTO subscription VALUES ('253', '2', '2020-05-22')")
    c.execute("INSERT INTO subscription VALUES ('253', '4', '2020-10-12')")
    c.execute("INSERT INTO subscription VALUES ('254', '0', '2020-07-23')")
    c.execute("INSERT INTO subscription VALUES ('254', '4', '2020-07-30')")
    c.execute("INSERT INTO subscription VALUES ('255', '0', '2020-03-29')")
    c.execute("INSERT INTO subscription VALUES ('255', '2', '2020-04-05')")
    c.execute("INSERT INTO subscription VALUES ('255', '3', '2020-10-05')")
    c.execute("INSERT INTO subscription VALUES ('256', '0', '2020-07-13')")
    c.execute("INSERT INTO subscription VALUES ('256', '1', '2020-07-20')")
    c.execute("INSERT INTO subscription VALUES ('256', '2', '2020-11-23')")
    c.execute("INSERT INTO subscription VALUES ('257', '0', '2020-01-15')")
    c.execute("INSERT INTO subscription VALUES ('257', '2', '2020-01-22')")
    c.execute("INSERT INTO subscription VALUES ('257', '3', '2020-04-22')")
    c.execute("INSERT INTO subscription VALUES ('257', '4', '2021-04-22')")
    c.execute("INSERT INTO subscription VALUES ('258', '0', '2020-06-19')")
    c.execute("INSERT INTO subscription VALUES ('258', '1', '2020-06-26')")
    c.execute("INSERT INTO subscription VALUES ('258', '3', '2020-07-06')")
    c.execute("INSERT INTO subscription VALUES ('259', '0', '2020-11-09')")
    c.execute("INSERT INTO subscription VALUES ('259', '1', '2020-11-16')")
    c.execute("INSERT INTO subscription VALUES ('259', '2', '2021-02-13')")
    c.execute("INSERT INTO subscription VALUES ('260', '0', '2020-09-21')")
    c.execute("INSERT INTO subscription VALUES ('260', '2', '2020-09-28')")
    c.execute("INSERT INTO subscription VALUES ('261', '0', '2020-03-12')")
    c.execute("INSERT INTO subscription VALUES ('261', '2', '2020-03-19')")
    c.execute("INSERT INTO subscription VALUES ('261', '3', '2020-05-19')")
    c.execute("INSERT INTO subscription VALUES ('262', '0', '2020-05-14')")
    c.execute("INSERT INTO subscription VALUES ('262', '1', '2020-05-21')")
    c.execute("INSERT INTO subscription VALUES ('263', '0', '2020-07-10')")
    c.execute("INSERT INTO subscription VALUES ('263', '2', '2020-07-17')")
    c.execute("INSERT INTO subscription VALUES ('263', '4', '2020-07-20')")
    c.execute("INSERT INTO subscription VALUES ('264', '0', '2020-09-12')")
    c.execute("INSERT INTO subscription VALUES ('264', '2', '2020-09-19')")
    c.execute("INSERT INTO subscription VALUES ('264', '4', '2020-12-07')")
    c.execute("INSERT INTO subscription VALUES ('265', '0', '2020-06-13')")
    c.execute("INSERT INTO subscription VALUES ('265', '1', '2020-06-20')")
    c.execute("INSERT INTO subscription VALUES ('265', '4', '2020-07-14')")
    c.execute("INSERT INTO subscription VALUES ('266', '0', '2020-07-20')")
    c.execute("INSERT INTO subscription VALUES ('266', '1', '2020-07-27')")
    c.execute("INSERT INTO subscription VALUES ('266', '3', '2020-12-04')")
    c.execute("INSERT INTO subscription VALUES ('267', '0', '2020-09-19')")
    c.execute("INSERT INTO subscription VALUES ('267', '1', '2020-09-26')")
    c.execute("INSERT INTO subscription VALUES ('267', '3', '2020-10-10')")
    c.execute("INSERT INTO subscription VALUES ('268', '0', '2020-10-07')")
    c.execute("INSERT INTO subscription VALUES ('268', '1', '2020-10-14')")
    c.execute("INSERT INTO subscription VALUES ('268', '4', '2020-11-07')")
    c.execute("INSERT INTO subscription VALUES ('269', '0', '2020-07-29')")
    c.execute("INSERT INTO subscription VALUES ('269', '1', '2020-08-05')")
    c.execute("INSERT INTO subscription VALUES ('269', '2', '2020-12-06')")
    c.execute("INSERT INTO subscription VALUES ('270', '0', '2020-07-05')")
    c.execute("INSERT INTO subscription VALUES ('270', '2', '2020-07-12')")
    c.execute("INSERT INTO subscription VALUES ('270', '3', '2021-01-12')")
    c.execute("INSERT INTO subscription VALUES ('271', '0', '2020-08-29')")
    c.execute("INSERT INTO subscription VALUES ('271', '2', '2020-09-05')")
    c.execute("INSERT INTO subscription VALUES ('272', '0', '2020-12-19')")
    c.execute("INSERT INTO subscription VALUES ('272', '1', '2020-12-26')")
    c.execute("INSERT INTO subscription VALUES ('272', '3', '2021-01-17')")
    c.execute("INSERT INTO subscription VALUES ('273', '0', '2020-02-14')")
    c.execute("INSERT INTO subscription VALUES ('273', '1', '2020-02-21')")
    c.execute("INSERT INTO subscription VALUES ('274', '0', '2020-03-01')")
    c.execute("INSERT INTO subscription VALUES ('274', '1', '2020-03-08')")
    c.execute("INSERT INTO subscription VALUES ('275', '0', '2020-04-27')")
    c.execute("INSERT INTO subscription VALUES ('275', '1', '2020-05-04')")
    c.execute("INSERT INTO subscription VALUES ('275', '4', '2020-09-09')")
    c.execute("INSERT INTO subscription VALUES ('276', '0', '2020-12-25')")
    c.execute("INSERT INTO subscription VALUES ('276', '2', '2021-01-01')")
    c.execute("INSERT INTO subscription VALUES ('276', '3', '2021-03-01')")
    c.execute("INSERT INTO subscription VALUES ('277', '0', '2020-08-06')")
    c.execute("INSERT INTO subscription VALUES ('277', '1', '2020-08-13')")
    c.execute("INSERT INTO subscription VALUES ('278', '0', '2020-08-01')")
    c.execute("INSERT INTO subscription VALUES ('278', '2', '2020-08-08')")
    c.execute("INSERT INTO subscription VALUES ('278', '3', '2020-11-08')")
    c.execute("INSERT INTO subscription VALUES ('279', '0', '2020-03-31')")
    c.execute("INSERT INTO subscription VALUES ('279', '3', '2020-04-07')")
    c.execute("INSERT INTO subscription VALUES ('280', '0', '2020-06-17')")
    c.execute("INSERT INTO subscription VALUES ('280', '1', '2020-06-24')")
    c.execute("INSERT INTO subscription VALUES ('280', '2', '2020-10-28')")
    c.execute("INSERT INTO subscription VALUES ('280', '4', '2021-02-23')")
    c.execute("INSERT INTO subscription VALUES ('281', '0', '2020-01-01')")
    c.execute("INSERT INTO subscription VALUES ('281', '1', '2020-01-08')")
    c.execute("INSERT INTO subscription VALUES ('282', '0', '2020-06-21')")
    c.execute("INSERT INTO subscription VALUES ('282', '2', '2020-06-28')")
    c.execute("INSERT INTO subscription VALUES ('283', '0', '2020-06-11')")
    c.execute("INSERT INTO subscription VALUES ('283', '1', '2020-06-18')")
    c.execute("INSERT INTO subscription VALUES ('283', '2', '2020-09-11')")
    c.execute("INSERT INTO subscription VALUES ('283', '3', '2020-12-11')")
    c.execute("INSERT INTO subscription VALUES ('284', '0', '2020-07-27')")
    c.execute("INSERT INTO subscription VALUES ('284', '2', '2020-08-03')")
    c.execute("INSERT INTO subscription VALUES ('284', '4', '2020-11-18')")
    c.execute("INSERT INTO subscription VALUES ('285', '0', '2020-07-06')")
    c.execute("INSERT INTO subscription VALUES ('285', '4', '2020-07-13')")
    c.execute("INSERT INTO subscription VALUES ('286', '0', '2020-03-23')")
    c.execute("INSERT INTO subscription VALUES ('286', '2', '2020-03-30')")
    c.execute("INSERT INTO subscription VALUES ('287', '0', '2020-08-23')")
    c.execute("INSERT INTO subscription VALUES ('287', '1', '2020-08-30')")
    c.execute("INSERT INTO subscription VALUES ('287', '3', '2020-12-09')")
    c.execute("INSERT INTO subscription VALUES ('288', '0', '2020-11-28')")
    c.execute("INSERT INTO subscription VALUES ('288', '1', '2020-12-05')")
    c.execute("INSERT INTO subscription VALUES ('288', '4', '2020-12-06')")
    c.execute("INSERT INTO subscription VALUES ('289', '0', '2020-01-08')")
    c.execute("INSERT INTO subscription VALUES ('289', '2', '2020-01-15')")
    c.execute("INSERT INTO subscription VALUES ('290', '0', '2020-01-10')")
    c.execute("INSERT INTO subscription VALUES ('290', '1', '2020-01-17')")
    c.execute("INSERT INTO subscription VALUES ('291', '0', '2020-03-03')")
    c.execute("INSERT INTO subscription VALUES ('291', '1', '2020-03-10')")
    c.execute("INSERT INTO subscription VALUES ('291', '3', '2020-08-16')")
    c.execute("INSERT INTO subscription VALUES ('292', '0', '2020-08-14')")
    c.execute("INSERT INTO subscription VALUES ('292', '1', '2020-08-21')")
    c.execute("INSERT INTO subscription VALUES ('292', '3', '2020-10-18')")
    c.execute("INSERT INTO subscription VALUES ('293', '0', '2020-10-30')")
    c.execute("INSERT INTO subscription VALUES ('293', '1', '2020-11-06')")
    c.execute("INSERT INTO subscription VALUES ('293', '2', '2021-03-15')")
    c.execute("INSERT INTO subscription VALUES ('293', '4', '2021-03-18')")
    c.execute("INSERT INTO subscription VALUES ('294', '0', '2020-01-19')")
    c.execute("INSERT INTO subscription VALUES ('294', '4', '2020-01-26')")
    c.execute("INSERT INTO subscription VALUES ('295', '0', '2020-06-01')")
    c.execute("INSERT INTO subscription VALUES ('295', '1', '2020-06-08')")
    c.execute("INSERT INTO subscription VALUES ('295', '2', '2020-08-17')")
    c.execute("INSERT INTO subscription VALUES ('296', '0', '2020-10-17')")
    c.execute("INSERT INTO subscription VALUES ('296', '4', '2020-10-24')")
    c.execute("INSERT INTO subscription VALUES ('297', '0', '2020-08-13')")
    c.execute("INSERT INTO subscription VALUES ('297', '2', '2020-08-20')")
    c.execute("INSERT INTO subscription VALUES ('297', '3', '2020-12-20')")
    c.execute("INSERT INTO subscription VALUES ('298', '0', '2020-10-26')")
    c.execute("INSERT INTO subscription VALUES ('298', '1', '2020-11-02')")
    c.execute("INSERT INTO subscription VALUES ('298', '2', '2020-12-13')")
    c.execute("INSERT INTO subscription VALUES ('299', '0', '2020-09-13')")
    c.execute("INSERT INTO subscription VALUES ('299', '1', '2020-09-20')")
    c.execute("INSERT INTO subscription VALUES ('299', '2', '2020-10-28')")
    c.execute("INSERT INTO subscription VALUES ('299', '3', '2021-01-28')")
    c.execute("INSERT INTO subscription VALUES ('300', '0', '2020-04-06')")
    c.execute("INSERT INTO subscription VALUES ('300', '1', '2020-04-13')")
    c.execute("INSERT INTO subscription VALUES ('300', '3', '2020-10-04')")
    c.execute("INSERT INTO subscription VALUES ('301', '0', '2020-05-07')")
    c.execute("INSERT INTO subscription VALUES ('301', '1', '2020-05-14')")
    c.execute("INSERT INTO subscription VALUES ('301', '2', '2020-10-30')")
    c.execute("INSERT INTO subscription VALUES ('301', '3', '2021-01-30')")
    c.execute("INSERT INTO subscription VALUES ('302', '0', '2020-01-09')")
    c.execute("INSERT INTO subscription VALUES ('302', '2', '2020-01-16')")
    c.execute("INSERT INTO subscription VALUES ('302', '4', '2020-01-22')")
    c.execute("INSERT INTO subscription VALUES ('303', '0', '2020-02-13')")
    c.execute("INSERT INTO subscription VALUES ('303', '1', '2020-02-20')")
    c.execute("INSERT INTO subscription VALUES ('303', '4', '2020-06-15')")
    c.execute("INSERT INTO subscription VALUES ('304', '0', '2020-12-28')")
    c.execute("INSERT INTO subscription VALUES ('304', '1', '2021-01-04')")
    c.execute("INSERT INTO subscription VALUES ('304', '4', '2021-01-27')")
    c.execute("INSERT INTO subscription VALUES ('305', '0', '2020-11-16')")
    c.execute("INSERT INTO subscription VALUES ('305', '1', '2020-11-23')")
    c.execute("INSERT INTO subscription VALUES ('306', '0', '2020-09-09')")
    c.execute("INSERT INTO subscription VALUES ('306', '2', '2020-09-16')")
    c.execute("INSERT INTO subscription VALUES ('307', '0', '2020-04-01')")
    c.execute("INSERT INTO subscription VALUES ('307', '1', '2020-04-08')")
    c.execute("INSERT INTO subscription VALUES ('307', '2', '2020-09-27')")
    c.execute("INSERT INTO subscription VALUES ('307', '3', '2020-10-27')")
    c.execute("INSERT INTO subscription VALUES ('308', '0', '2020-04-12')")
    c.execute("INSERT INTO subscription VALUES ('308', '1', '2020-04-19')")
    c.execute("INSERT INTO subscription VALUES ('308', '4', '2020-07-22')")
    c.execute("INSERT INTO subscription VALUES ('309', '0', '2020-12-08')")
    c.execute("INSERT INTO subscription VALUES ('309', '2', '2020-12-15')")
    c.execute("INSERT INTO subscription VALUES ('310', '0', '2020-08-01')")
    c.execute("INSERT INTO subscription VALUES ('310', '1', '2020-08-08')")
    c.execute("INSERT INTO subscription VALUES ('310', '3', '2021-01-05')")
    c.execute("INSERT INTO subscription VALUES ('311', '0', '2020-12-03')")
    c.execute("INSERT INTO subscription VALUES ('311', '1', '2020-12-10')")
    c.execute("INSERT INTO subscription VALUES ('311', '4', '2021-03-01')")
    c.execute("INSERT INTO subscription VALUES ('312', '0', '2020-01-09')")
    c.execute("INSERT INTO subscription VALUES ('312', '1', '2020-01-16')")
    c.execute("INSERT INTO subscription VALUES ('312', '2', '2020-04-19')")
    c.execute("INSERT INTO subscription VALUES ('313', '0', '2020-01-15')")
    c.execute("INSERT INTO subscription VALUES ('313', '1', '2020-01-22')")
    c.execute("INSERT INTO subscription VALUES ('313', '3', '2020-06-29')")
    c.execute("INSERT INTO subscription VALUES ('314', '0', '2020-11-11')")
    c.execute("INSERT INTO subscription VALUES ('314', '4', '2020-11-18')")
    c.execute("INSERT INTO subscription VALUES ('315', '0', '2020-12-13')")
    c.execute("INSERT INTO subscription VALUES ('315', '1', '2020-12-20')")
    c.execute("INSERT INTO subscription VALUES ('315', '2', '2020-12-21')")
    c.execute("INSERT INTO subscription VALUES ('316', '0', '2020-03-31')")
    c.execute("INSERT INTO subscription VALUES ('316', '2', '2020-04-07')")
    c.execute("INSERT INTO subscription VALUES ('317', '0', '2020-10-11')")
    c.execute("INSERT INTO subscription VALUES ('317', '4', '2020-10-18')")
    c.execute("INSERT INTO subscription VALUES ('318', '0', '2020-06-20')")
    c.execute("INSERT INTO subscription VALUES ('318', '1', '2020-06-27')")
    c.execute("INSERT INTO subscription VALUES ('318', '2', '2020-09-30')")
    c.execute("INSERT INTO subscription VALUES ('318', '3', '2020-11-30')")
    c.execute("INSERT INTO subscription VALUES ('319', '0', '2020-10-25')")
    c.execute("INSERT INTO subscription VALUES ('319', '2', '2020-11-01')")
    c.execute("INSERT INTO subscription VALUES ('320', '0', '2020-09-27')")
    c.execute("INSERT INTO subscription VALUES ('320', '2', '2020-10-04')")
    c.execute("INSERT INTO subscription VALUES ('320', '3', '2021-04-04')")
    c.execute("INSERT INTO subscription VALUES ('321', '0', '2020-03-06')")
    c.execute("INSERT INTO subscription VALUES ('321', '2', '2020-03-13')")
    c.execute("INSERT INTO subscription VALUES ('322', '0', '2020-12-19')")
    c.execute("INSERT INTO subscription VALUES ('322', '3', '2020-12-26')")
    c.execute("INSERT INTO subscription VALUES ('323', '0', '2020-10-20')")
    c.execute("INSERT INTO subscription VALUES ('323', '1', '2020-10-27')")
    c.execute("INSERT INTO subscription VALUES ('323', '2', '2021-04-14')")
    c.execute("INSERT INTO subscription VALUES ('324', '0', '2020-05-07')")
    c.execute("INSERT INTO subscription VALUES ('324', '1', '2020-05-14')")
    c.execute("INSERT INTO subscription VALUES ('324', '4', '2020-07-26')")
    c.execute("INSERT INTO subscription VALUES ('325', '0', '2020-05-18')")
    c.execute("INSERT INTO subscription VALUES ('325', '4', '2020-05-25')")
    c.execute("INSERT INTO subscription VALUES ('326', '0', '2020-11-20')")
    c.execute("INSERT INTO subscription VALUES ('326', '3', '2020-11-27')")
    c.execute("INSERT INTO subscription VALUES ('327', '0', '2020-04-14')")
    c.execute("INSERT INTO subscription VALUES ('327', '1', '2020-04-21')")
    c.execute("INSERT INTO subscription VALUES ('327', '2', '2020-08-17')")
    c.execute("INSERT INTO subscription VALUES ('328', '0', '2020-10-06')")
    c.execute("INSERT INTO subscription VALUES ('328', '1', '2020-10-13')")
    c.execute("INSERT INTO subscription VALUES ('328', '2', '2021-02-02')")
    c.execute("INSERT INTO subscription VALUES ('329', '0', '2020-04-26')")
    c.execute("INSERT INTO subscription VALUES ('329', '4', '2020-05-03')")
    c.execute("INSERT INTO subscription VALUES ('330', '0', '2020-01-20')")
    c.execute("INSERT INTO subscription VALUES ('330', '4', '2020-01-27')")
    c.execute("INSERT INTO subscription VALUES ('331', '0', '2020-04-12')")
    c.execute("INSERT INTO subscription VALUES ('331', '1', '2020-04-19')")
    c.execute("INSERT INTO subscription VALUES ('331', '4', '2020-09-14')")
    c.execute("INSERT INTO subscription VALUES ('332', '0', '2020-10-11')")
    c.execute("INSERT INTO subscription VALUES ('332', '1', '2020-10-18')")
    c.execute("INSERT INTO subscription VALUES ('332', '2', '2020-11-17')")
    c.execute("INSERT INTO subscription VALUES ('333', '0', '2020-01-19')")
    c.execute("INSERT INTO subscription VALUES ('333', '2', '2020-01-26')")
    c.execute("INSERT INTO subscription VALUES ('333', '4', '2020-06-15')")
    c.execute("INSERT INTO subscription VALUES ('334', '0', '2020-08-07')")
    c.execute("INSERT INTO subscription VALUES ('334', '1', '2020-08-14')")
    c.execute("INSERT INTO subscription VALUES ('334', '2', '2021-02-09')")
    c.execute("INSERT INTO subscription VALUES ('335', '0', '2020-09-25')")
    c.execute("INSERT INTO subscription VALUES ('335', '1', '2020-10-02')")
    c.execute("INSERT INTO subscription VALUES ('336', '0', '2020-06-23')")
    c.execute("INSERT INTO subscription VALUES ('336', '1', '2020-06-30')")
    c.execute("INSERT INTO subscription VALUES ('336', '2', '2020-07-22')")
    c.execute("INSERT INTO subscription VALUES ('337', '0', '2020-11-16')")
    c.execute("INSERT INTO subscription VALUES ('337', '1', '2020-11-23')")
    c.execute("INSERT INTO subscription VALUES ('338', '0', '2020-12-12')")
    c.execute("INSERT INTO subscription VALUES ('338', '1', '2020-12-19')")
    c.execute("INSERT INTO subscription VALUES ('339', '0', '2020-05-06')")
    c.execute("INSERT INTO subscription VALUES ('339', '1', '2020-05-13')")
    c.execute("INSERT INTO subscription VALUES ('340', '0', '2020-06-27')")
    c.execute("INSERT INTO subscription VALUES ('340', '1', '2020-07-04')")
    c.execute("INSERT INTO subscription VALUES ('340', '2', '2020-07-19')")
    c.execute("INSERT INTO subscription VALUES ('341', '0', '2020-10-17')")
    c.execute("INSERT INTO subscription VALUES ('341', '1', '2020-10-24')")
    c.execute("INSERT INTO subscription VALUES ('341', '2', '2021-01-30')")
    c.execute("INSERT INTO subscription VALUES ('342', '0', '2020-06-21')")
    c.execute("INSERT INTO subscription VALUES ('342', '1', '2020-06-28')")
    c.execute("INSERT INTO subscription VALUES ('342', '4', '2020-08-19')")
    c.execute("INSERT INTO subscription VALUES ('343', '0', '2020-02-02')")
    c.execute("INSERT INTO subscription VALUES ('343', '1', '2020-02-09')")
    c.execute("INSERT INTO subscription VALUES ('344', '0', '2020-09-22')")
    c.execute("INSERT INTO subscription VALUES ('344', '2', '2020-09-29')")
    c.execute("INSERT INTO subscription VALUES ('344', '4', '2021-02-15')")
    c.execute("INSERT INTO subscription VALUES ('345', '0', '2020-04-17')")
    c.execute("INSERT INTO subscription VALUES ('345', '1', '2020-04-24')")
    c.execute("INSERT INTO subscription VALUES ('345', '2', '2020-06-07')")
    c.execute("INSERT INTO subscription VALUES ('345', '3', '2020-08-07')")
    c.execute("INSERT INTO subscription VALUES ('346', '0', '2020-11-13')")
    c.execute("INSERT INTO subscription VALUES ('346', '2', '2020-11-20')")
    c.execute("INSERT INTO subscription VALUES ('346', '3', '2021-04-20')")
    c.execute("INSERT INTO subscription VALUES ('347', '0', '2020-05-30')")
    c.execute("INSERT INTO subscription VALUES ('347', '1', '2020-06-06')")
    c.execute("INSERT INTO subscription VALUES ('347', '3', '2020-07-14')")
    c.execute("INSERT INTO subscription VALUES ('348', '0', '2020-09-14')")
    c.execute("INSERT INTO subscription VALUES ('348', '1', '2020-09-21')")
    c.execute("INSERT INTO subscription VALUES ('348', '4', '2020-09-28')")
    c.execute("INSERT INTO subscription VALUES ('349', '0', '2020-06-16')")
    c.execute("INSERT INTO subscription VALUES ('349', '1', '2020-06-23')")
    c.execute("INSERT INTO subscription VALUES ('349', '3', '2020-08-22')")
    c.execute("INSERT INTO subscription VALUES ('350', '0', '2020-04-25')")
    c.execute("INSERT INTO subscription VALUES ('350', '1', '2020-05-02')")
    c.execute("INSERT INTO subscription VALUES ('351', '0', '2020-05-24')")
    c.execute("INSERT INTO subscription VALUES ('351', '1', '2020-05-31')")
    c.execute("INSERT INTO subscription VALUES ('351', '2', '2020-07-06')")
    c.execute("INSERT INTO subscription VALUES ('352', '0', '2020-09-21')")
    c.execute("INSERT INTO subscription VALUES ('352', '1', '2020-09-28')")
    c.execute("INSERT INTO subscription VALUES ('352', '2', '2021-03-06')")
    c.execute("INSERT INTO subscription VALUES ('353', '0', '2020-11-29')")
    c.execute("INSERT INTO subscription VALUES ('353', '3', '2020-12-06')")
    c.execute("INSERT INTO subscription VALUES ('354', '0', '2020-03-19')")
    c.execute("INSERT INTO subscription VALUES ('354', '4', '2020-03-26')")
    c.execute("INSERT INTO subscription VALUES ('355', '0', '2020-10-27')")
    c.execute("INSERT INTO subscription VALUES ('355', '2', '2020-11-03')")
    c.execute("INSERT INTO subscription VALUES ('356', '0', '2020-04-09')")
    c.execute("INSERT INTO subscription VALUES ('356', '1', '2020-04-16')")
    c.execute("INSERT INTO subscription VALUES ('356', '3', '2020-07-02')")
    c.execute("INSERT INTO subscription VALUES ('357', '0', '2020-10-07')")
    c.execute("INSERT INTO subscription VALUES ('357', '2', '2020-10-14')")
    c.execute("INSERT INTO subscription VALUES ('357', '3', '2021-01-14')")
    c.execute("INSERT INTO subscription VALUES ('358', '0', '2020-02-25')")
    c.execute("INSERT INTO subscription VALUES ('358', '2', '2020-03-03')")
    c.execute("INSERT INTO subscription VALUES ('358', '4', '2020-04-02')")
    c.execute("INSERT INTO subscription VALUES ('359', '0', '2020-08-14')")
    c.execute("INSERT INTO subscription VALUES ('359', '1', '2020-08-21')")
    c.execute("INSERT INTO subscription VALUES ('359', '2', '2020-12-11')")
    c.execute("INSERT INTO subscription VALUES ('360', '0', '2020-08-27')")
    c.execute("INSERT INTO subscription VALUES ('360', '2', '2020-09-03')")
    c.execute("INSERT INTO subscription VALUES ('360', '3', '2021-02-03')")
    c.execute("INSERT INTO subscription VALUES ('361', '0', '2020-10-10')")
    c.execute("INSERT INTO subscription VALUES ('361', '4', '2020-10-17')")
    c.execute("INSERT INTO subscription VALUES ('362', '0', '2020-06-05')")
    c.execute("INSERT INTO subscription VALUES ('362', '1', '2020-06-12')")
    c.execute("INSERT INTO subscription VALUES ('362', '3', '2020-08-21')")
    c.execute("INSERT INTO subscription VALUES ('363', '0', '2020-05-06')")
    c.execute("INSERT INTO subscription VALUES ('363', '1', '2020-05-13')")
    c.execute("INSERT INTO subscription VALUES ('363', '3', '2020-07-10')")
    c.execute("INSERT INTO subscription VALUES ('364', '0', '2020-05-02')")
    c.execute("INSERT INTO subscription VALUES ('364', '2', '2020-05-09')")
    c.execute("INSERT INTO subscription VALUES ('364', '4', '2020-09-15')")
    c.execute("INSERT INTO subscription VALUES ('365', '0', '2020-06-09')")
    c.execute("INSERT INTO subscription VALUES ('365', '2', '2020-06-16')")
    c.execute("INSERT INTO subscription VALUES ('365', '3', '2020-12-16')")
    c.execute("INSERT INTO subscription VALUES ('366', '0', '2020-07-18')")
    c.execute("INSERT INTO subscription VALUES ('366', '1', '2020-07-25')")
    c.execute("INSERT INTO subscription VALUES ('367', '0', '2020-02-25')")
    c.execute("INSERT INTO subscription VALUES ('367', '1', '2020-03-03')")
    c.execute("INSERT INTO subscription VALUES ('367', '2', '2020-08-01')")
    c.execute("INSERT INTO subscription VALUES ('368', '0', '2020-10-23')")
    c.execute("INSERT INTO subscription VALUES ('368', '1', '2020-10-30')")
    c.execute("INSERT INTO subscription VALUES ('368', '2', '2021-04-02')")
    c.execute("INSERT INTO subscription VALUES ('369', '0', '2020-09-11')")
    c.execute("INSERT INTO subscription VALUES ('369', '1', '2020-09-18')")
    c.execute("INSERT INTO subscription VALUES ('369', '4', '2020-11-09')")
    c.execute("INSERT INTO subscription VALUES ('370', '0', '2020-03-08')")
    c.execute("INSERT INTO subscription VALUES ('370', '1', '2020-03-15')")
    c.execute("INSERT INTO subscription VALUES ('370', '2', '2020-08-27')")
    c.execute("INSERT INTO subscription VALUES ('370', '3', '2020-10-27')")
    c.execute("INSERT INTO subscription VALUES ('371', '0', '2020-05-06')")
    c.execute("INSERT INTO subscription VALUES ('371', '2', '2020-05-13')")
    c.execute("INSERT INTO subscription VALUES ('372', '0', '2020-05-04')")
    c.execute("INSERT INTO subscription VALUES ('372', '1', '2020-05-11')")
    c.execute("INSERT INTO subscription VALUES ('372', '3', '2020-08-08')")
    c.execute("INSERT INTO subscription VALUES ('373', '0', '2020-10-20')")
    c.execute("INSERT INTO subscription VALUES ('373', '1', '2020-10-27')")
    c.execute("INSERT INTO subscription VALUES ('373', '2', '2020-11-03')")
    c.execute("INSERT INTO subscription VALUES ('374', '0', '2020-05-18')")
    c.execute("INSERT INTO subscription VALUES ('374', '1', '2020-05-25')")
    c.execute("INSERT INTO subscription VALUES ('374', '2', '2020-06-15')")
    c.execute("INSERT INTO subscription VALUES ('374', '4', '2020-09-21')")
    c.execute("INSERT INTO subscription VALUES ('375', '0', '2020-01-01')")
    c.execute("INSERT INTO subscription VALUES ('375', '2', '2020-01-08')")
    c.execute("INSERT INTO subscription VALUES ('375', '3', '2020-07-08')")
    c.execute("INSERT INTO subscription VALUES ('376', '0', '2020-10-19')")
    c.execute("INSERT INTO subscription VALUES ('376', '2', '2020-10-26')")
    c.execute("INSERT INTO subscription VALUES ('376', '4', '2021-03-17')")
    c.execute("INSERT INTO subscription VALUES ('377', '0', '2020-02-11')")
    c.execute("INSERT INTO subscription VALUES ('377', '1', '2020-02-18')")
    c.execute("INSERT INTO subscription VALUES ('377', '2', '2020-03-17')")
    c.execute("INSERT INTO subscription VALUES ('378', '0', '2020-04-28')")
    c.execute("INSERT INTO subscription VALUES ('378', '2', '2020-05-05')")
    c.execute("INSERT INTO subscription VALUES ('379', '0', '2020-02-05')")
    c.execute("INSERT INTO subscription VALUES ('379', '2', '2020-02-12')")
    c.execute("INSERT INTO subscription VALUES ('379', '4', '2020-05-05')")
    c.execute("INSERT INTO subscription VALUES ('380', '0', '2020-08-01')")
    c.execute("INSERT INTO subscription VALUES ('380', '1', '2020-08-08')")
    c.execute("INSERT INTO subscription VALUES ('380', '2', '2020-11-29')")
    c.execute("INSERT INTO subscription VALUES ('380', '3', '2021-02-28')")
    c.execute("INSERT INTO subscription VALUES ('381', '0', '2020-07-21')")
    c.execute("INSERT INTO subscription VALUES ('381', '1', '2020-07-28')")
    c.execute("INSERT INTO subscription VALUES ('381', '2', '2020-08-22')")
    c.execute("INSERT INTO subscription VALUES ('382', '0', '2020-02-20')")
    c.execute("INSERT INTO subscription VALUES ('382', '1', '2020-02-27')")
    c.execute("INSERT INTO subscription VALUES ('383', '0', '2020-01-30')")
    c.execute("INSERT INTO subscription VALUES ('383', '2', '2020-02-06')")
    c.execute("INSERT INTO subscription VALUES ('383', '3', '2020-08-06')")
    c.execute("INSERT INTO subscription VALUES ('384', '0', '2020-07-26')")
    c.execute("INSERT INTO subscription VALUES ('384', '2', '2020-08-02')")
    c.execute("INSERT INTO subscription VALUES ('384', '4', '2020-08-23')")
    c.execute("INSERT INTO subscription VALUES ('385', '0', '2020-07-25')")
    c.execute("INSERT INTO subscription VALUES ('385', '2', '2020-08-01')")
    c.execute("INSERT INTO subscription VALUES ('386', '0', '2020-09-15')")
    c.execute("INSERT INTO subscription VALUES ('386', '1', '2020-09-22')")
    c.execute("INSERT INTO subscription VALUES ('387', '0', '2020-02-17')")
    c.execute("INSERT INTO subscription VALUES ('387', '1', '2020-02-24')")
    c.execute("INSERT INTO subscription VALUES ('388', '0', '2020-11-09')")
    c.execute("INSERT INTO subscription VALUES ('388', '4', '2020-11-16')")
    c.execute("INSERT INTO subscription VALUES ('389', '0', '2020-01-04')")
    c.execute("INSERT INTO subscription VALUES ('389', '1', '2020-01-11')")
    c.execute("INSERT INTO subscription VALUES ('389', '2', '2020-06-15')")
    c.execute("INSERT INTO subscription VALUES ('389', '4', '2020-10-27')")
    c.execute("INSERT INTO subscription VALUES ('390', '0', '2020-12-11')")
    c.execute("INSERT INTO subscription VALUES ('390', '2', '2020-12-18')")
    c.execute("INSERT INTO subscription VALUES ('391', '0', '2020-06-29')")
    c.execute("INSERT INTO subscription VALUES ('391', '2', '2020-07-06')")
    c.execute("INSERT INTO subscription VALUES ('391', '3', '2020-09-06')")
    c.execute("INSERT INTO subscription VALUES ('392', '0', '2020-05-31')")
    c.execute("INSERT INTO subscription VALUES ('392', '2', '2020-06-07')")
    c.execute("INSERT INTO subscription VALUES ('393', '0', '2020-04-11')")
    c.execute("INSERT INTO subscription VALUES ('393', '1', '2020-04-18')")
    c.execute("INSERT INTO subscription VALUES ('393', '2', '2020-05-05')")
    c.execute("INSERT INTO subscription VALUES ('394', '0', '2020-08-17')")
    c.execute("INSERT INTO subscription VALUES ('394', '1', '2020-08-24')")
    c.execute("INSERT INTO subscription VALUES ('394', '4', '2021-01-24')")
    c.execute("INSERT INTO subscription VALUES ('395', '0', '2020-03-31')")
    c.execute("INSERT INTO subscription VALUES ('395', '3', '2020-04-07')")
    c.execute("INSERT INTO subscription VALUES ('395', '4', '2021-04-07')")
    c.execute("INSERT INTO subscription VALUES ('396', '0', '2020-09-25')")
    c.execute("INSERT INTO subscription VALUES ('396', '1', '2020-10-02')")
    c.execute("INSERT INTO subscription VALUES ('397', '0', '2020-01-13')")
    c.execute("INSERT INTO subscription VALUES ('397', '2', '2020-01-20')")
    c.execute("INSERT INTO subscription VALUES ('398', '0', '2020-07-17')")
    c.execute("INSERT INTO subscription VALUES ('398', '1', '2020-07-24')")
    c.execute("INSERT INTO subscription VALUES ('398', '2', '2020-10-02')")
    c.execute("INSERT INTO subscription VALUES ('398', '4', '2021-02-27')")
    c.execute("INSERT INTO subscription VALUES ('399', '0', '2020-03-03')")
    c.execute("INSERT INTO subscription VALUES ('399', '1', '2020-03-10')")
    c.execute("INSERT INTO subscription VALUES ('399', '2', '2020-05-24')")
    c.execute("INSERT INTO subscription VALUES ('400', '0', '2020-04-27')")
    c.execute("INSERT INTO subscription VALUES ('400', '1', '2020-05-04')")
    c.execute("INSERT INTO subscription VALUES ('401', '0', '2020-04-14')")
    c.execute("INSERT INTO subscription VALUES ('401', '2', '2020-04-21')")
    c.execute("INSERT INTO subscription VALUES ('401', '4', '2020-05-22')")
    c.execute("INSERT INTO subscription VALUES ('402', '0', '2020-06-17')")
    c.execute("INSERT INTO subscription VALUES ('402', '2', '2020-06-24')")
    c.execute("INSERT INTO subscription VALUES ('402', '3', '2020-10-24')")
    c.execute("INSERT INTO subscription VALUES ('403', '0', '2020-05-15')")
    c.execute("INSERT INTO subscription VALUES ('403', '2', '2020-05-22')")
    c.execute("INSERT INTO subscription VALUES ('404', '0', '2020-03-29')")
    c.execute("INSERT INTO subscription VALUES ('404', '2', '2020-04-05')")
    c.execute("INSERT INTO subscription VALUES ('405', '0', '2020-03-02')")
    c.execute("INSERT INTO subscription VALUES ('405', '4', '2020-03-09')")
    c.execute("INSERT INTO subscription VALUES ('406', '0', '2020-10-17')")
    c.execute("INSERT INTO subscription VALUES ('406', '2', '2020-10-24')")
    c.execute("INSERT INTO subscription VALUES ('407', '0', '2020-11-03')")
    c.execute("INSERT INTO subscription VALUES ('407', '1', '2020-11-10')")
    c.execute("INSERT INTO subscription VALUES ('407', '2', '2021-04-12')")
    c.execute("INSERT INTO subscription VALUES ('408', '0', '2020-01-30')")
    c.execute("INSERT INTO subscription VALUES ('408', '2', '2020-02-06')")
    c.execute("INSERT INTO subscription VALUES ('409', '0', '2020-09-02')")
    c.execute("INSERT INTO subscription VALUES ('409', '1', '2020-09-09')")
    c.execute("INSERT INTO subscription VALUES ('409', '2', '2021-01-29')")
    c.execute("INSERT INTO subscription VALUES ('410', '0', '2020-01-27')")
    c.execute("INSERT INTO subscription VALUES ('410', '1', '2020-02-03')")
    c.execute("INSERT INTO subscription VALUES ('411', '0', '2020-03-16')")
    c.execute("INSERT INTO subscription VALUES ('411', '1', '2020-03-23')")
    c.execute("INSERT INTO subscription VALUES ('411', '2', '2020-08-15')")
    c.execute("INSERT INTO subscription VALUES ('412', '0', '2020-06-09')")
    c.execute("INSERT INTO subscription VALUES ('412', '1', '2020-06-16')")
    c.execute("INSERT INTO subscription VALUES ('412', '3', '2020-10-23')")
    c.execute("INSERT INTO subscription VALUES ('413', '0', '2020-08-27')")
    c.execute("INSERT INTO subscription VALUES ('413', '1', '2020-09-03')")
    c.execute("INSERT INTO subscription VALUES ('413', '2', '2020-12-21')")
    c.execute("INSERT INTO subscription VALUES ('414', '0', '2020-10-09')")
    c.execute("INSERT INTO subscription VALUES ('414', '2', '2020-10-16')")
    c.execute("INSERT INTO subscription VALUES ('415', '0', '2020-10-30')")
    c.execute("INSERT INTO subscription VALUES ('415', '2', '2020-11-06')")
    c.execute("INSERT INTO subscription VALUES ('415', '3', '2021-02-06')")
    c.execute("INSERT INTO subscription VALUES ('416', '0', '2020-08-07')")
    c.execute("INSERT INTO subscription VALUES ('416', '2', '2020-08-14')")
    c.execute("INSERT INTO subscription VALUES ('416', '3', '2021-02-14')")
    c.execute("INSERT INTO subscription VALUES ('417', '0', '2020-01-28')")
    c.execute("INSERT INTO subscription VALUES ('417', '2', '2020-02-04')")
    c.execute("INSERT INTO subscription VALUES ('417', '4', '2020-03-02')")
    c.execute("INSERT INTO subscription VALUES ('418', '0', '2020-10-07')")
    c.execute("INSERT INTO subscription VALUES ('418', '1', '2020-10-14')")
    c.execute("INSERT INTO subscription VALUES ('418', '4', '2020-11-22')")
    c.execute("INSERT INTO subscription VALUES ('419', '0', '2020-03-17')")
    c.execute("INSERT INTO subscription VALUES ('419', '2', '2020-03-24')")
    c.execute("INSERT INTO subscription VALUES ('420', '0', '2020-05-27')")
    c.execute("INSERT INTO subscription VALUES ('420', '1', '2020-06-03')")
    c.execute("INSERT INTO subscription VALUES ('421', '0', '2020-03-23')")
    c.execute("INSERT INTO subscription VALUES ('421', '2', '2020-03-30')")
    c.execute("INSERT INTO subscription VALUES ('422', '0', '2020-12-26')")
    c.execute("INSERT INTO subscription VALUES ('422', '2', '2021-01-02')")
    c.execute("INSERT INTO subscription VALUES ('423', '0', '2020-10-06')")
    c.execute("INSERT INTO subscription VALUES ('423', '2', '2020-10-13')")
    c.execute("INSERT INTO subscription VALUES ('424', '0', '2020-12-15')")
    c.execute("INSERT INTO subscription VALUES ('424', '1', '2020-12-22')")
    c.execute("INSERT INTO subscription VALUES ('424', '4', '2021-04-28')")
    c.execute("INSERT INTO subscription VALUES ('425', '0', '2020-04-04')")
    c.execute("INSERT INTO subscription VALUES ('425', '2', '2020-04-11')")
    c.execute("INSERT INTO subscription VALUES ('425', '4', '2020-05-25')")
    c.execute("INSERT INTO subscription VALUES ('426', '0', '2020-10-10')")
    c.execute("INSERT INTO subscription VALUES ('426', '1', '2020-10-17')")
    c.execute("INSERT INTO subscription VALUES ('426', '2', '2021-02-23')")
    c.execute("INSERT INTO subscription VALUES ('427', '0', '2020-05-31')")
    c.execute("INSERT INTO subscription VALUES ('427', '2', '2020-06-07')")
    c.execute("INSERT INTO subscription VALUES ('427', '4', '2020-06-23')")
    c.execute("INSERT INTO subscription VALUES ('428', '0', '2020-10-25')")
    c.execute("INSERT INTO subscription VALUES ('428', '4', '2020-11-01')")
    c.execute("INSERT INTO subscription VALUES ('429', '0', '2020-02-05')")
    c.execute("INSERT INTO subscription VALUES ('429', '2', '2020-02-12')")
    c.execute("INSERT INTO subscription VALUES ('429', '4', '2020-07-30')")
    c.execute("INSERT INTO subscription VALUES ('430', '0', '2020-03-13')")
    c.execute("INSERT INTO subscription VALUES ('430', '1', '2020-03-20')")
    c.execute("INSERT INTO subscription VALUES ('430', '2', '2020-08-05')")
    c.execute("INSERT INTO subscription VALUES ('431', '0', '2020-12-27')")
    c.execute("INSERT INTO subscription VALUES ('431', '1', '2021-01-03')")
    c.execute("INSERT INTO subscription VALUES ('431', '4', '2021-03-14')")
    c.execute("INSERT INTO subscription VALUES ('432', '0', '2020-03-19')")
    c.execute("INSERT INTO subscription VALUES ('432', '1', '2020-03-26')")
    c.execute("INSERT INTO subscription VALUES ('432', '3', '2020-05-22')")
    c.execute("INSERT INTO subscription VALUES ('433', '0', '2020-10-04')")
    c.execute("INSERT INTO subscription VALUES ('433', '1', '2020-10-11')")
    c.execute("INSERT INTO subscription VALUES ('434', '0', '2020-11-08')")
    c.execute("INSERT INTO subscription VALUES ('434', '1', '2020-11-15')")
    c.execute("INSERT INTO subscription VALUES ('434', '2', '2021-02-02')")
    c.execute("INSERT INTO subscription VALUES ('435', '0', '2020-01-09')")
    c.execute("INSERT INTO subscription VALUES ('435', '2', '2020-01-16')")
    c.execute("INSERT INTO subscription VALUES ('435', '4', '2020-03-08')")
    c.execute("INSERT INTO subscription VALUES ('436', '0', '2020-12-27')")
    c.execute("INSERT INTO subscription VALUES ('436', '1', '2021-01-03')")
    c.execute("INSERT INTO subscription VALUES ('437', '0', '2020-05-09')")
    c.execute("INSERT INTO subscription VALUES ('437', '4', '2020-05-16')")
    c.execute("INSERT INTO subscription VALUES ('438', '0', '2020-01-31')")
    c.execute("INSERT INTO subscription VALUES ('438', '1', '2020-02-07')")
    c.execute("INSERT INTO subscription VALUES ('438', '2', '2020-04-16')")
    c.execute("INSERT INTO subscription VALUES ('439', '0', '2020-01-09')")
    c.execute("INSERT INTO subscription VALUES ('439', '1', '2020-01-16')")
    c.execute("INSERT INTO subscription VALUES ('439', '4', '2020-05-04')")
    c.execute("INSERT INTO subscription VALUES ('440', '0', '2020-03-14')")
    c.execute("INSERT INTO subscription VALUES ('440', '2', '2020-03-21')")
    c.execute("INSERT INTO subscription VALUES ('440', '4', '2020-04-28')")
    c.execute("INSERT INTO subscription VALUES ('441', '0', '2020-09-27')")
    c.execute("INSERT INTO subscription VALUES ('441', '4', '2020-10-04')")
    c.execute("INSERT INTO subscription VALUES ('442', '0', '2020-01-28')")
    c.execute("INSERT INTO subscription VALUES ('442', '1', '2020-02-04')")
    c.execute("INSERT INTO subscription VALUES ('442', '3', '2020-03-11')")
    c.execute("INSERT INTO subscription VALUES ('443', '0', '2020-11-28')")
    c.execute("INSERT INTO subscription VALUES ('443', '2', '2020-12-05')")
    c.execute("INSERT INTO subscription VALUES ('443', '4', '2021-03-16')")
    c.execute("INSERT INTO subscription VALUES ('444', '0', '2020-10-14')")
    c.execute("INSERT INTO subscription VALUES ('444', '4', '2020-10-21')")
    c.execute("INSERT INTO subscription VALUES ('445', '0', '2020-02-13')")
    c.execute("INSERT INTO subscription VALUES ('445', '4', '2020-02-20')")
    c.execute("INSERT INTO subscription VALUES ('446', '0', '2020-02-20')")
    c.execute("INSERT INTO subscription VALUES ('446', '2', '2020-02-27')")
    c.execute("INSERT INTO subscription VALUES ('446', '3', '2020-08-27')")
    c.execute("INSERT INTO subscription VALUES ('447', '0', '2020-04-02')")
    c.execute("INSERT INTO subscription VALUES ('447', '4', '2020-04-09')")
    c.execute("INSERT INTO subscription VALUES ('448', '0', '2020-08-30')")
    c.execute("INSERT INTO subscription VALUES ('448', '1', '2020-09-06')")
    c.execute("INSERT INTO subscription VALUES ('448', '3', '2020-10-30')")
    c.execute("INSERT INTO subscription VALUES ('449', '0', '2020-01-06')")
    c.execute("INSERT INTO subscription VALUES ('449', '1', '2020-01-13')")
    c.execute("INSERT INTO subscription VALUES ('449', '2', '2020-05-07')")
    c.execute("INSERT INTO subscription VALUES ('450', '0', '2020-09-29')")
    c.execute("INSERT INTO subscription VALUES ('450', '1', '2020-10-06')")
    c.execute("INSERT INTO subscription VALUES ('450', '3', '2021-01-08')")
    c.execute("INSERT INTO subscription VALUES ('451', '0', '2020-08-31')")
    c.execute("INSERT INTO subscription VALUES ('451', '2', '2020-09-07')")
    c.execute("INSERT INTO subscription VALUES ('452', '0', '2020-05-11')")
    c.execute("INSERT INTO subscription VALUES ('452', '1', '2020-05-18')")
    c.execute("INSERT INTO subscription VALUES ('452', '4', '2020-06-22')")
    c.execute("INSERT INTO subscription VALUES ('453', '0', '2020-02-15')")
    c.execute("INSERT INTO subscription VALUES ('453', '2', '2020-02-22')")
    c.execute("INSERT INTO subscription VALUES ('454', '0', '2020-06-15')")
    c.execute("INSERT INTO subscription VALUES ('454', '2', '2020-06-22')")
    c.execute("INSERT INTO subscription VALUES ('455', '0', '2020-08-13')")
    c.execute("INSERT INTO subscription VALUES ('455', '1', '2020-08-20')")
    c.execute("INSERT INTO subscription VALUES ('456', '0', '2020-02-21')")
    c.execute("INSERT INTO subscription VALUES ('456', '4', '2020-02-28')")
    c.execute("INSERT INTO subscription VALUES ('457', '0', '2020-11-19')")
    c.execute("INSERT INTO subscription VALUES ('457', '1', '2020-11-26')")
    c.execute("INSERT INTO subscription VALUES ('457', '2', '2021-03-12')")
    c.execute("INSERT INTO subscription VALUES ('458', '0', '2020-04-25')")
    c.execute("INSERT INTO subscription VALUES ('458', '4', '2020-05-02')")
    c.execute("INSERT INTO subscription VALUES ('459', '0', '2020-12-07')")
    c.execute("INSERT INTO subscription VALUES ('459', '2', '2020-12-14')")
    c.execute("INSERT INTO subscription VALUES ('459', '3', '2021-03-14')")
    c.execute("INSERT INTO subscription VALUES ('460', '0', '2020-12-09')")
    c.execute("INSERT INTO subscription VALUES ('460', '1', '2020-12-16')")
    c.execute("INSERT INTO subscription VALUES ('460', '2', '2021-04-16')")
    c.execute("INSERT INTO subscription VALUES ('461', '0', '2020-02-21')")
    c.execute("INSERT INTO subscription VALUES ('461', '1', '2020-02-28')")
    c.execute("INSERT INTO subscription VALUES ('461', '4', '2020-07-30')")
    c.execute("INSERT INTO subscription VALUES ('462', '0', '2020-05-05')")
    c.execute("INSERT INTO subscription VALUES ('462', '1', '2020-05-12')")
    c.execute("INSERT INTO subscription VALUES ('462', '2', '2020-09-15')")
    c.execute("INSERT INTO subscription VALUES ('463', '0', '2020-11-27')")
    c.execute("INSERT INTO subscription VALUES ('463', '1', '2020-12-04')")
    c.execute("INSERT INTO subscription VALUES ('463', '2', '2021-01-23')")
    c.execute("INSERT INTO subscription VALUES ('463', '4', '2021-04-24')")
    c.execute("INSERT INTO subscription VALUES ('464', '0', '2020-01-11')")
    c.execute("INSERT INTO subscription VALUES ('464', '1', '2020-01-18')")
    c.execute("INSERT INTO subscription VALUES ('465', '0', '2020-10-24')")
    c.execute("INSERT INTO subscription VALUES ('465', '1', '2020-10-31')")
    c.execute("INSERT INTO subscription VALUES ('465', '4', '2021-01-03')")
    c.execute("INSERT INTO subscription VALUES ('466', '0', '2020-03-13')")
    c.execute("INSERT INTO subscription VALUES ('466', '4', '2020-03-20')")
    c.execute("INSERT INTO subscription VALUES ('467', '0', '2020-06-21')")
    c.execute("INSERT INTO subscription VALUES ('467', '4', '2020-06-28')")
    c.execute("INSERT INTO subscription VALUES ('468', '0', '2020-04-21')")
    c.execute("INSERT INTO subscription VALUES ('468', '1', '2020-04-28')")
    c.execute("INSERT INTO subscription VALUES ('468', '3', '2020-05-01')")
    c.execute("INSERT INTO subscription VALUES ('469', '0', '2020-06-17')")
    c.execute("INSERT INTO subscription VALUES ('469', '2', '2020-06-24')")
    c.execute("INSERT INTO subscription VALUES ('469', '3', '2020-11-24')")
    c.execute("INSERT INTO subscription VALUES ('470', '0', '2020-04-28')")
    c.execute("INSERT INTO subscription VALUES ('470', '2', '2020-05-05')")
    c.execute("INSERT INTO subscription VALUES ('470', '3', '2020-08-05')")
    c.execute("INSERT INTO subscription VALUES ('471', '0', '2020-01-31')")
    c.execute("INSERT INTO subscription VALUES ('471', '2', '2020-02-07')")
    c.execute("INSERT INTO subscription VALUES ('472', '0', '2020-12-23')")
    c.execute("INSERT INTO subscription VALUES ('472', '2', '2020-12-30')")
    c.execute("INSERT INTO subscription VALUES ('472', '3', '2021-04-30')")
    c.execute("INSERT INTO subscription VALUES ('473', '0', '2020-03-18')")
    c.execute("INSERT INTO subscription VALUES ('473', '1', '2020-03-25')")
    c.execute("INSERT INTO subscription VALUES ('473', '3', '2020-04-17')")
    c.execute("INSERT INTO subscription VALUES ('474', '0', '2020-09-01')")
    c.execute("INSERT INTO subscription VALUES ('474', '2', '2020-09-08')")
    c.execute("INSERT INTO subscription VALUES ('474', '3', '2021-02-08')")
    c.execute("INSERT INTO subscription VALUES ('475', '0', '2020-07-24')")
    c.execute("INSERT INTO subscription VALUES ('475', '1', '2020-07-31')")
    c.execute("INSERT INTO subscription VALUES ('475', '3', '2020-12-17')")
    c.execute("INSERT INTO subscription VALUES ('476', '0', '2020-08-22')")
    c.execute("INSERT INTO subscription VALUES ('476', '2', '2020-08-29')")
    c.execute("INSERT INTO subscription VALUES ('477', '0', '2020-01-28')")
    c.execute("INSERT INTO subscription VALUES ('477', '4', '2020-02-04')")
    c.execute("INSERT INTO subscription VALUES ('478', '0', '2020-10-23')")
    c.execute("INSERT INTO subscription VALUES ('478', '1', '2020-10-30')")
    c.execute("INSERT INTO subscription VALUES ('478', '2', '2021-01-19')")
    c.execute("INSERT INTO subscription VALUES ('479', '0', '2020-10-01')")
    c.execute("INSERT INTO subscription VALUES ('479', '1', '2020-10-08')")
    c.execute("INSERT INTO subscription VALUES ('479', '2', '2021-01-24')")
    c.execute("INSERT INTO subscription VALUES ('480', '0', '2020-10-05')")
    c.execute("INSERT INTO subscription VALUES ('480', '1', '2020-10-12')")
    c.execute("INSERT INTO subscription VALUES ('480', '3', '2021-02-10')")
    c.execute("INSERT INTO subscription VALUES ('481', '0', '2020-07-08')")
    c.execute("INSERT INTO subscription VALUES ('481', '4', '2020-07-15')")
    c.execute("INSERT INTO subscription VALUES ('482', '0', '2020-06-25')")
    c.execute("INSERT INTO subscription VALUES ('482', '2', '2020-07-02')")
    c.execute("INSERT INTO subscription VALUES ('483', '0', '2020-01-12')")
    c.execute("INSERT INTO subscription VALUES ('483', '1', '2020-01-19')")
    c.execute("INSERT INTO subscription VALUES ('483', '2', '2020-07-10')")
    c.execute("INSERT INTO subscription VALUES ('484', '0', '2020-09-17')")
    c.execute("INSERT INTO subscription VALUES ('484', '1', '2020-09-24')")
    c.execute("INSERT INTO subscription VALUES ('484', '3', '2021-01-15')")
    c.execute("INSERT INTO subscription VALUES ('485', '0', '2020-05-24')")
    c.execute("INSERT INTO subscription VALUES ('485', '2', '2020-05-31')")
    c.execute("INSERT INTO subscription VALUES ('485', '3', '2020-07-31')")
    c.execute("INSERT INTO subscription VALUES ('486', '0', '2020-06-27')")
    c.execute("INSERT INTO subscription VALUES ('486', '1', '2020-07-04')")
    c.execute("INSERT INTO subscription VALUES ('486', '4', '2020-10-10')")
    c.execute("INSERT INTO subscription VALUES ('487', '0', '2020-12-07')")
    c.execute("INSERT INTO subscription VALUES ('487', '1', '2020-12-14')")
    c.execute("INSERT INTO subscription VALUES ('487', '3', '2021-01-14')")
    c.execute("INSERT INTO subscription VALUES ('488', '0', '2020-02-15')")
    c.execute("INSERT INTO subscription VALUES ('488', '2', '2020-02-22')")
    c.execute("INSERT INTO subscription VALUES ('488', '3', '2020-06-22')")
    c.execute("INSERT INTO subscription VALUES ('489', '0', '2020-08-25')")
    c.execute("INSERT INTO subscription VALUES ('489', '4', '2020-09-01')")
    c.execute("INSERT INTO subscription VALUES ('490', '0', '2020-04-22')")
    c.execute("INSERT INTO subscription VALUES ('490', '1', '2020-04-29')")
    c.execute("INSERT INTO subscription VALUES ('490', '2', '2020-06-26')")
    c.execute("INSERT INTO subscription VALUES ('490', '4', '2020-07-01')")
    c.execute("INSERT INTO subscription VALUES ('491', '0', '2020-07-02')")
    c.execute("INSERT INTO subscription VALUES ('491', '2', '2020-07-09')")
    c.execute("INSERT INTO subscription VALUES ('492', '0', '2020-02-27')")
    c.execute("INSERT INTO subscription VALUES ('492', '1', '2020-03-05')")
    c.execute("INSERT INTO subscription VALUES ('493', '0', '2020-07-14')")
    c.execute("INSERT INTO subscription VALUES ('493', '1', '2020-07-21')")
    c.execute("INSERT INTO subscription VALUES ('493', '2', '2020-08-19')")
    c.execute("INSERT INTO subscription VALUES ('494', '0', '2020-07-18')")
    c.execute("INSERT INTO subscription VALUES ('494', '2', '2020-07-25')")
    c.execute("INSERT INTO subscription VALUES ('494', '4', '2021-01-06')")
    c.execute("INSERT INTO subscription VALUES ('495', '0', '2020-01-04')")
    c.execute("INSERT INTO subscription VALUES ('495', '2', '2020-01-11')")
    c.execute("INSERT INTO subscription VALUES ('496', '0', '2020-02-08')")
    c.execute("INSERT INTO subscription VALUES ('496', '1', '2020-02-15')")
    c.execute("INSERT INTO subscription VALUES ('496', '3', '2020-07-05')")
    c.execute("INSERT INTO subscription VALUES ('497', '0', '2020-04-08')")
    c.execute("INSERT INTO subscription VALUES ('497', '1', '2020-04-15')")
    c.execute("INSERT INTO subscription VALUES ('497', '2', '2020-07-18')")
    c.execute("INSERT INTO subscription VALUES ('497', '3', '2021-01-18')")
    c.execute("INSERT INTO subscription VALUES ('498', '0', '2020-11-13')")
    c.execute("INSERT INTO subscription VALUES ('498', '1', '2020-11-20')")
    c.execute("INSERT INTO subscription VALUES ('498', '4', '2021-03-08')")
    c.execute("INSERT INTO subscription VALUES ('499', '0', '2020-02-17')")
    c.execute("INSERT INTO subscription VALUES ('499', '2', '2020-02-24')")
    c.execute("INSERT INTO subscription VALUES ('500', '0', '2020-09-16')")
    c.execute("INSERT INTO subscription VALUES ('500', '1', '2020-09-23')")
    c.execute("INSERT INTO subscription VALUES ('500', '3', '2020-12-21')")
    c.execute("INSERT INTO subscription VALUES ('501', '0', '2020-10-15')")
    c.execute("INSERT INTO subscription VALUES ('501', '4', '2020-10-22')")
    c.execute("INSERT INTO subscription VALUES ('502', '0', '2020-01-25')")
    c.execute("INSERT INTO subscription VALUES ('502', '1', '2020-02-01')")
    c.execute("INSERT INTO subscription VALUES ('502', '3', '2020-06-25')")
    c.execute("INSERT INTO subscription VALUES ('503', '0', '2020-09-08')")
    c.execute("INSERT INTO subscription VALUES ('503', '2', '2020-09-15')")
    c.execute("INSERT INTO subscription VALUES ('504', '0', '2020-05-19')")
    c.execute("INSERT INTO subscription VALUES ('504', '2', '2020-05-26')")
    c.execute("INSERT INTO subscription VALUES ('505', '0', '2020-11-17')")
    c.execute("INSERT INTO subscription VALUES ('505', '1', '2020-11-24')")
    c.execute("INSERT INTO subscription VALUES ('505', '3', '2021-01-25')")
    c.execute("INSERT INTO subscription VALUES ('506', '0', '2020-07-11')")
    c.execute("INSERT INTO subscription VALUES ('506', '1', '2020-07-18')")
    c.execute("INSERT INTO subscription VALUES ('506', '2', '2020-07-26')")
    c.execute("INSERT INTO subscription VALUES ('507', '0', '2020-07-16')")
    c.execute("INSERT INTO subscription VALUES ('507', '1', '2020-07-23')")
    c.execute("INSERT INTO subscription VALUES ('507', '4', '2020-11-22')")
    c.execute("INSERT INTO subscription VALUES ('508', '0', '2020-12-20')")
    c.execute("INSERT INTO subscription VALUES ('508', '4', '2020-12-27')")
    c.execute("INSERT INTO subscription VALUES ('509', '0', '2020-09-23')")
    c.execute("INSERT INTO subscription VALUES ('509', '1', '2020-09-30')")
    c.execute("INSERT INTO subscription VALUES ('509', '4', '2020-10-14')")
    c.execute("INSERT INTO subscription VALUES ('510', '0', '2020-02-19')")
    c.execute("INSERT INTO subscription VALUES ('510', '1', '2020-02-26')")
    c.execute("INSERT INTO subscription VALUES ('510', '2', '2020-04-19')")
    c.execute("INSERT INTO subscription VALUES ('510', '3', '2020-06-19')")
    c.execute("INSERT INTO subscription VALUES ('511', '0', '2020-11-11')")
    c.execute("INSERT INTO subscription VALUES ('511', '3', '2020-11-18')")
    c.execute("INSERT INTO subscription VALUES ('512', '0', '2020-12-23')")
    c.execute("INSERT INTO subscription VALUES ('512', '1', '2020-12-30')")
    c.execute("INSERT INTO subscription VALUES ('512', '2', '2021-04-12')")
    c.execute("INSERT INTO subscription VALUES ('513', '0', '2020-07-27')")
    c.execute("INSERT INTO subscription VALUES ('513', '2', '2020-08-03')")
    c.execute("INSERT INTO subscription VALUES ('514', '0', '2020-01-29')")
    c.execute("INSERT INTO subscription VALUES ('514', '1', '2020-02-05')")
    c.execute("INSERT INTO subscription VALUES ('514', '2', '2020-03-11')")
    c.execute("INSERT INTO subscription VALUES ('515', '0', '2020-05-15')")
    c.execute("INSERT INTO subscription VALUES ('515', '1', '2020-05-22')")
    c.execute("INSERT INTO subscription VALUES ('515', '2', '2020-07-06')")
    c.execute("INSERT INTO subscription VALUES ('516', '0', '2020-12-21')")
    c.execute("INSERT INTO subscription VALUES ('516', '1', '2020-12-28')")
    c.execute("INSERT INTO subscription VALUES ('516', '2', '2021-03-20')")
    c.execute("INSERT INTO subscription VALUES ('517', '0', '2020-07-24')")
    c.execute("INSERT INTO subscription VALUES ('517', '1', '2020-07-31')")
    c.execute("INSERT INTO subscription VALUES ('517', '2', '2020-11-21')")
    c.execute("INSERT INTO subscription VALUES ('518', '0', '2020-10-06')")
    c.execute("INSERT INTO subscription VALUES ('518', '4', '2020-10-13')")
    c.execute("INSERT INTO subscription VALUES ('519', '0', '2020-01-22')")
    c.execute("INSERT INTO subscription VALUES ('519', '1', '2020-01-29')")
    c.execute("INSERT INTO subscription VALUES ('520', '0', '2020-08-16')")
    c.execute("INSERT INTO subscription VALUES ('520', '1', '2020-08-23')")
    c.execute("INSERT INTO subscription VALUES ('520', '2', '2021-02-16')")
    c.execute("INSERT INTO subscription VALUES ('521', '0', '2020-06-17')")
    c.execute("INSERT INTO subscription VALUES ('521', '2', '2020-06-24')")
    c.execute("INSERT INTO subscription VALUES ('521', '4', '2020-11-07')")
    c.execute("INSERT INTO subscription VALUES ('522', '0', '2020-08-26')")
    c.execute("INSERT INTO subscription VALUES ('522', '1', '2020-09-02')")
    c.execute("INSERT INTO subscription VALUES ('522', '2', '2020-09-26')")
    c.execute("INSERT INTO subscription VALUES ('523', '0', '2020-04-21')")
    c.execute("INSERT INTO subscription VALUES ('523', '4', '2020-04-28')")
    c.execute("INSERT INTO subscription VALUES ('524', '0', '2020-08-09')")
    c.execute("INSERT INTO subscription VALUES ('524', '1', '2020-08-16')")
    c.execute("INSERT INTO subscription VALUES ('524', '3', '2020-08-31')")
    c.execute("INSERT INTO subscription VALUES ('525', '0', '2020-08-31')")
    c.execute("INSERT INTO subscription VALUES ('525', '1', '2020-09-07')")
    c.execute("INSERT INTO subscription VALUES ('526', '0', '2020-05-20')")
    c.execute("INSERT INTO subscription VALUES ('526', '1', '2020-05-27')")
    c.execute("INSERT INTO subscription VALUES ('526', '3', '2020-09-23')")
    c.execute("INSERT INTO subscription VALUES ('527', '0', '2020-04-20')")
    c.execute("INSERT INTO subscription VALUES ('527', '2', '2020-04-27')")
    c.execute("INSERT INTO subscription VALUES ('527', '3', '2020-08-27')")
    c.execute("INSERT INTO subscription VALUES ('528', '0', '2020-08-06')")
    c.execute("INSERT INTO subscription VALUES ('528', '2', '2020-08-13')")
    c.execute("INSERT INTO subscription VALUES ('529', '0', '2020-03-30')")
    c.execute("INSERT INTO subscription VALUES ('529', '1', '2020-04-06')")
    c.execute("INSERT INTO subscription VALUES ('529', '2', '2020-09-13')")
    c.execute("INSERT INTO subscription VALUES ('530', '0', '2020-02-23')")
    c.execute("INSERT INTO subscription VALUES ('530', '1', '2020-03-01')")
    c.execute("INSERT INTO subscription VALUES ('530', '2', '2020-08-21')")
    c.execute("INSERT INTO subscription VALUES ('530', '3', '2020-10-21')")
    c.execute("INSERT INTO subscription VALUES ('531', '0', '2020-04-24')")
    c.execute("INSERT INTO subscription VALUES ('531', '1', '2020-05-01')")
    c.execute("INSERT INTO subscription VALUES ('531', '2', '2020-08-25')")
    c.execute("INSERT INTO subscription VALUES ('532', '0', '2020-03-28')")
    c.execute("INSERT INTO subscription VALUES ('532', '1', '2020-04-04')")
    c.execute("INSERT INTO subscription VALUES ('532', '2', '2020-05-24')")
    c.execute("INSERT INTO subscription VALUES ('532', '3', '2020-09-24')")
    c.execute("INSERT INTO subscription VALUES ('533', '0', '2020-02-01')")
    c.execute("INSERT INTO subscription VALUES ('533', '1', '2020-02-08')")
    c.execute("INSERT INTO subscription VALUES ('533', '4', '2020-03-05')")
    c.execute("INSERT INTO subscription VALUES ('534', '0', '2020-05-25')")
    c.execute("INSERT INTO subscription VALUES ('534', '1', '2020-06-01')")
    c.execute("INSERT INTO subscription VALUES ('534', '3', '2020-08-15')")
    c.execute("INSERT INTO subscription VALUES ('535', '0', '2020-03-26')")
    c.execute("INSERT INTO subscription VALUES ('535', '2', '2020-04-02')")
    c.execute("INSERT INTO subscription VALUES ('536', '0', '2020-09-07')")
    c.execute("INSERT INTO subscription VALUES ('536', '2', '2020-09-14')")
    c.execute("INSERT INTO subscription VALUES ('537', '0', '2020-12-21')")
    c.execute("INSERT INTO subscription VALUES ('537', '1', '2020-12-28')")
    c.execute("INSERT INTO subscription VALUES ('538', '0', '2020-10-12')")
    c.execute("INSERT INTO subscription VALUES ('538', '1', '2020-10-19')")
    c.execute("INSERT INTO subscription VALUES ('538', '4', '2021-01-22')")
    c.execute("INSERT INTO subscription VALUES ('539', '0', '2020-04-13')")
    c.execute("INSERT INTO subscription VALUES ('539', '2', '2020-04-20')")
    c.execute("INSERT INTO subscription VALUES ('540', '0', '2020-08-16')")
    c.execute("INSERT INTO subscription VALUES ('540', '1', '2020-08-23')")
    c.execute("INSERT INTO subscription VALUES ('540', '2', '2021-01-28')")
    c.execute("INSERT INTO subscription VALUES ('540', '4', '2021-03-09')")
    c.execute("INSERT INTO subscription VALUES ('541', '0', '2020-07-04')")
    c.execute("INSERT INTO subscription VALUES ('541', '3', '2020-07-11')")
    c.execute("INSERT INTO subscription VALUES ('542', '0', '2020-04-07')")
    c.execute("INSERT INTO subscription VALUES ('542', '3', '2020-04-14')")
    c.execute("INSERT INTO subscription VALUES ('542', '4', '2021-04-14')")
    c.execute("INSERT INTO subscription VALUES ('543', '0', '2020-05-05')")
    c.execute("INSERT INTO subscription VALUES ('543', '1', '2020-05-12')")
    c.execute("INSERT INTO subscription VALUES ('543', '3', '2020-07-03')")
    c.execute("INSERT INTO subscription VALUES ('544', '0', '2020-03-08')")
    c.execute("INSERT INTO subscription VALUES ('544', '2', '2020-03-15')")
    c.execute("INSERT INTO subscription VALUES ('545', '0', '2020-03-05')")
    c.execute("INSERT INTO subscription VALUES ('545', '1', '2020-03-12')")
    c.execute("INSERT INTO subscription VALUES ('545', '2', '2020-04-21')")
    c.execute("INSERT INTO subscription VALUES ('546', '0', '2020-06-02')")
    c.execute("INSERT INTO subscription VALUES ('546', '1', '2020-06-09')")
    c.execute("INSERT INTO subscription VALUES ('547', '0', '2020-03-05')")
    c.execute("INSERT INTO subscription VALUES ('547', '1', '2020-03-12')")
    c.execute("INSERT INTO subscription VALUES ('547', '3', '2020-08-24')")
    c.execute("INSERT INTO subscription VALUES ('548', '0', '2020-03-24')")
    c.execute("INSERT INTO subscription VALUES ('548', '1', '2020-03-31')")
    c.execute("INSERT INTO subscription VALUES ('549', '0', '2020-10-07')")
    c.execute("INSERT INTO subscription VALUES ('549', '1', '2020-10-14')")
    c.execute("INSERT INTO subscription VALUES ('549', '2', '2021-01-12')")
    c.execute("INSERT INTO subscription VALUES ('550', '0', '2020-09-24')")
    c.execute("INSERT INTO subscription VALUES ('550', '1', '2020-10-01')")
    c.execute("INSERT INTO subscription VALUES ('550', '4', '2021-03-22')")
    c.execute("INSERT INTO subscription VALUES ('551', '0', '2020-05-07')")
    c.execute("INSERT INTO subscription VALUES ('551', '1', '2020-05-14')")
    c.execute("INSERT INTO subscription VALUES ('552', '0', '2020-07-27')")
    c.execute("INSERT INTO subscription VALUES ('552', '2', '2020-08-03')")
    c.execute("INSERT INTO subscription VALUES ('552', '3', '2021-01-03')")
    c.execute("INSERT INTO subscription VALUES ('553', '0', '2020-09-30')")
    c.execute("INSERT INTO subscription VALUES ('553', '2', '2020-10-07')")
    c.execute("INSERT INTO subscription VALUES ('554', '0', '2020-09-27')")
    c.execute("INSERT INTO subscription VALUES ('554', '2', '2020-10-04')")
    c.execute("INSERT INTO subscription VALUES ('555', '0', '2020-04-24')")
    c.execute("INSERT INTO subscription VALUES ('555', '1', '2020-05-01')")
    c.execute("INSERT INTO subscription VALUES ('555', '2', '2020-09-24')")
    c.execute("INSERT INTO subscription VALUES ('556', '0', '2020-08-08')")
    c.execute("INSERT INTO subscription VALUES ('556', '1', '2020-08-15')")
    c.execute("INSERT INTO subscription VALUES ('556', '3', '2020-10-10')")
    c.execute("INSERT INTO subscription VALUES ('557', '0', '2020-03-02')")
    c.execute("INSERT INTO subscription VALUES ('557', '1', '2020-03-09')")
    c.execute("INSERT INTO subscription VALUES ('557', '3', '2020-04-24')")
    c.execute("INSERT INTO subscription VALUES ('558', '0', '2020-12-15')")
    c.execute("INSERT INTO subscription VALUES ('558', '2', '2020-12-22')")
    c.execute("INSERT INTO subscription VALUES ('559', '0', '2020-11-06')")
    c.execute("INSERT INTO subscription VALUES ('559', '1', '2020-11-13')")
    c.execute("INSERT INTO subscription VALUES ('560', '0', '2020-06-25')")
    c.execute("INSERT INTO subscription VALUES ('560', '1', '2020-07-02')")
    c.execute("INSERT INTO subscription VALUES ('560', '4', '2020-09-07')")
    c.execute("INSERT INTO subscription VALUES ('561', '0', '2020-06-18')")
    c.execute("INSERT INTO subscription VALUES ('561', '1', '2020-06-25')")
    c.execute("INSERT INTO subscription VALUES ('562', '0', '2020-08-06')")
    c.execute("INSERT INTO subscription VALUES ('562', '1', '2020-08-13')")
    c.execute("INSERT INTO subscription VALUES ('562', '2', '2020-10-23')")
    c.execute("INSERT INTO subscription VALUES ('563', '0', '2020-06-19')")
    c.execute("INSERT INTO subscription VALUES ('563', '1', '2020-06-26')")
    c.execute("INSERT INTO subscription VALUES ('563', '4', '2020-07-19')")
    c.execute("INSERT INTO subscription VALUES ('564', '0', '2020-06-19')")
    c.execute("INSERT INTO subscription VALUES ('564', '4', '2020-06-26')")
    c.execute("INSERT INTO subscription VALUES ('565', '0', '2020-01-02')")
    c.execute("INSERT INTO subscription VALUES ('565', '2', '2020-01-09')")
    c.execute("INSERT INTO subscription VALUES ('566', '0', '2020-11-26')")
    c.execute("INSERT INTO subscription VALUES ('566', '2', '2020-12-03')")
    c.execute("INSERT INTO subscription VALUES ('567', '0', '2020-07-12')")
    c.execute("INSERT INTO subscription VALUES ('567', '4', '2020-07-19')")
    c.execute("INSERT INTO subscription VALUES ('568', '0', '2020-04-02')")
    c.execute("INSERT INTO subscription VALUES ('568', '1', '2020-04-09')")
    c.execute("INSERT INTO subscription VALUES ('569', '0', '2020-12-12')")
    c.execute("INSERT INTO subscription VALUES ('569', '1', '2020-12-19')")
    c.execute("INSERT INTO subscription VALUES ('569', '2', '2021-03-31')")
    c.execute("INSERT INTO subscription VALUES ('570', '0', '2020-10-22')")
    c.execute("INSERT INTO subscription VALUES ('570', '1', '2020-10-29')")
    c.execute("INSERT INTO subscription VALUES ('570', '4', '2021-03-16')")
    c.execute("INSERT INTO subscription VALUES ('571', '0', '2020-12-15')")
    c.execute("INSERT INTO subscription VALUES ('571', '1', '2020-12-22')")
    c.execute("INSERT INTO subscription VALUES ('572', '0', '2020-03-28')")
    c.execute("INSERT INTO subscription VALUES ('572', '1', '2020-04-04')")
    c.execute("INSERT INTO subscription VALUES ('572', '4', '2020-09-08')")
    c.execute("INSERT INTO subscription VALUES ('573', '0', '2020-07-02')")
    c.execute("INSERT INTO subscription VALUES ('573', '1', '2020-07-09')")
    c.execute("INSERT INTO subscription VALUES ('573', '2', '2020-11-23')")
    c.execute("INSERT INTO subscription VALUES ('573', '3', '2021-01-23')")
    c.execute("INSERT INTO subscription VALUES ('574', '0', '2020-10-02')")
    c.execute("INSERT INTO subscription VALUES ('574', '1', '2020-10-09')")
    c.execute("INSERT INTO subscription VALUES ('574', '2', '2021-01-30')")
    c.execute("INSERT INTO subscription VALUES ('575', '0', '2020-06-16')")
    c.execute("INSERT INTO subscription VALUES ('575', '1', '2020-06-23')")
    c.execute("INSERT INTO subscription VALUES ('575', '2', '2020-10-31')")
    c.execute("INSERT INTO subscription VALUES ('576', '0', '2020-12-27')")
    c.execute("INSERT INTO subscription VALUES ('576', '2', '2021-01-03')")
    c.execute("INSERT INTO subscription VALUES ('577', '0', '2020-12-07')")
    c.execute("INSERT INTO subscription VALUES ('577', '1', '2020-12-14')")
    c.execute("INSERT INTO subscription VALUES ('578', '0', '2020-01-30')")
    c.execute("INSERT INTO subscription VALUES ('578', '1', '2020-02-06')")
    c.execute("INSERT INTO subscription VALUES ('579', '0', '2020-01-13')")
    c.execute("INSERT INTO subscription VALUES ('579', '2', '2020-01-20')")
    c.execute("INSERT INTO subscription VALUES ('580', '0', '2020-10-11')")
    c.execute("INSERT INTO subscription VALUES ('580', '2', '2020-10-18')")
    c.execute("INSERT INTO subscription VALUES ('580', '3', '2021-03-18')")
    c.execute("INSERT INTO subscription VALUES ('581', '0', '2020-01-05')")
    c.execute("INSERT INTO subscription VALUES ('581', '1', '2020-01-12')")
    c.execute("INSERT INTO subscription VALUES ('581', '3', '2020-06-01')")
    c.execute("INSERT INTO subscription VALUES ('582', '0', '2020-11-29')")
    c.execute("INSERT INTO subscription VALUES ('582', '1', '2020-12-06')")
    c.execute("INSERT INTO subscription VALUES ('583', '0', '2020-02-20')")
    c.execute("INSERT INTO subscription VALUES ('583', '1', '2020-02-27')")
    c.execute("INSERT INTO subscription VALUES ('583', '3', '2020-03-04')")
    c.execute("INSERT INTO subscription VALUES ('584', '0', '2020-08-22')")
    c.execute("INSERT INTO subscription VALUES ('584', '2', '2020-08-29')")
    c.execute("INSERT INTO subscription VALUES ('585', '0', '2020-01-22')")
    c.execute("INSERT INTO subscription VALUES ('585', '2', '2020-01-29')")
    c.execute("INSERT INTO subscription VALUES ('586', '0', '2020-01-12')")
    c.execute("INSERT INTO subscription VALUES ('586', '1', '2020-01-19')")
    c.execute("INSERT INTO subscription VALUES ('587', '0', '2020-06-21')")
    c.execute("INSERT INTO subscription VALUES ('587', '2', '2020-06-28')")
    c.execute("INSERT INTO subscription VALUES ('587', '3', '2020-07-28')")
    c.execute("INSERT INTO subscription VALUES ('588', '0', '2020-12-12')")
    c.execute("INSERT INTO subscription VALUES ('588', '2', '2020-12-19')")
    c.execute("INSERT INTO subscription VALUES ('588', '3', '2021-04-19')")
    c.execute("INSERT INTO subscription VALUES ('589', '0', '2020-09-14')")
    c.execute("INSERT INTO subscription VALUES ('589', '1', '2020-09-21')")
    c.execute("INSERT INTO subscription VALUES ('589', '2', '2020-10-01')")
    c.execute("INSERT INTO subscription VALUES ('590', '0', '2020-02-08')")
    c.execute("INSERT INTO subscription VALUES ('590', '1', '2020-02-15')")
    c.execute("INSERT INTO subscription VALUES ('591', '0', '2020-05-14')")
    c.execute("INSERT INTO subscription VALUES ('591', '1', '2020-05-21')")
    c.execute("INSERT INTO subscription VALUES ('591', '2', '2020-08-26')")
    c.execute("INSERT INTO subscription VALUES ('591', '4', '2020-12-08')")
    c.execute("INSERT INTO subscription VALUES ('592', '0', '2020-02-01')")
    c.execute("INSERT INTO subscription VALUES ('592', '3', '2020-02-08')")
    c.execute("INSERT INTO subscription VALUES ('593', '0', '2020-03-04')")
    c.execute("INSERT INTO subscription VALUES ('593', '1', '2020-03-11')")
    c.execute("INSERT INTO subscription VALUES ('594', '0', '2020-01-15')")
    c.execute("INSERT INTO subscription VALUES ('594', '2', '2020-01-22')")
    c.execute("INSERT INTO subscription VALUES ('594', '4', '2020-03-14')")
    c.execute("INSERT INTO subscription VALUES ('595', '0', '2020-06-04')")
    c.execute("INSERT INTO subscription VALUES ('595', '1', '2020-06-11')")
    c.execute("INSERT INTO subscription VALUES ('595', '2', '2020-11-18')")
    c.execute("INSERT INTO subscription VALUES ('596', '0', '2020-05-18')")
    c.execute("INSERT INTO subscription VALUES ('596', '1', '2020-05-25')")
    c.execute("INSERT INTO subscription VALUES ('597', '0', '2020-03-27')")
    c.execute("INSERT INTO subscription VALUES ('597', '2', '2020-04-03')")
    c.execute("INSERT INTO subscription VALUES ('598', '0', '2020-12-28')")
    c.execute("INSERT INTO subscription VALUES ('598', '2', '2021-01-04')")
    c.execute("INSERT INTO subscription VALUES ('599', '0', '2020-02-08')")
    c.execute("INSERT INTO subscription VALUES ('599', '1', '2020-02-15')")
    c.execute("INSERT INTO subscription VALUES ('599', '3', '2020-05-01')")
    c.execute("INSERT INTO subscription VALUES ('600', '0', '2020-06-20')")
    c.execute("INSERT INTO subscription VALUES ('600', '1', '2020-06-27')")
    c.execute("INSERT INTO subscription VALUES ('600', '3', '2020-11-09')")
    c.execute("INSERT INTO subscription VALUES ('601', '0', '2020-01-11')")
    c.execute("INSERT INTO subscription VALUES ('601', '1', '2020-01-18')")
    c.execute("INSERT INTO subscription VALUES ('602', '0', '2020-03-25')")
    c.execute("INSERT INTO subscription VALUES ('602', '1', '2020-04-01')")
    c.execute("INSERT INTO subscription VALUES ('602', '4', '2020-05-09')")
    c.execute("INSERT INTO subscription VALUES ('603', '0', '2020-04-20')")
    c.execute("INSERT INTO subscription VALUES ('603', '2', '2020-04-27')")
    c.execute("INSERT INTO subscription VALUES ('604', '0', '2020-07-21')")
    c.execute("INSERT INTO subscription VALUES ('604', '1', '2020-07-28')")
    c.execute("INSERT INTO subscription VALUES ('605', '0', '2020-09-23')")
    c.execute("INSERT INTO subscription VALUES ('605', '3', '2020-09-30')")
    c.execute("INSERT INTO subscription VALUES ('606', '0', '2020-01-27')")
    c.execute("INSERT INTO subscription VALUES ('606', '4', '2020-02-03')")
    c.execute("INSERT INTO subscription VALUES ('607', '0', '2020-01-02')")
    c.execute("INSERT INTO subscription VALUES ('607', '1', '2020-01-09')")
    c.execute("INSERT INTO subscription VALUES ('607', '4', '2020-04-03')")
    c.execute("INSERT INTO subscription VALUES ('608', '0', '2020-06-23')")
    c.execute("INSERT INTO subscription VALUES ('608', '1', '2020-06-30')")
    c.execute("INSERT INTO subscription VALUES ('608', '4', '2020-11-29')")
    c.execute("INSERT INTO subscription VALUES ('609', '0', '2020-06-12')")
    c.execute("INSERT INTO subscription VALUES ('609', '2', '2020-06-19')")
    c.execute("INSERT INTO subscription VALUES ('609', '4', '2020-12-01')")
    c.execute("INSERT INTO subscription VALUES ('610', '0', '2020-12-13')")
    c.execute("INSERT INTO subscription VALUES ('610', '1', '2020-12-20')")
    c.execute("INSERT INTO subscription VALUES ('610', '2', '2021-03-27')")
    c.execute("INSERT INTO subscription VALUES ('611', '0', '2020-07-31')")
    c.execute("INSERT INTO subscription VALUES ('611', '2', '2020-08-07')")
    c.execute("INSERT INTO subscription VALUES ('612', '0', '2020-11-14')")
    c.execute("INSERT INTO subscription VALUES ('612', '4', '2020-11-21')")
    c.execute("INSERT INTO subscription VALUES ('613', '0', '2020-04-26')")
    c.execute("INSERT INTO subscription VALUES ('613', '4', '2020-05-03')")
    c.execute("INSERT INTO subscription VALUES ('614', '0', '2020-11-07')")
    c.execute("INSERT INTO subscription VALUES ('614', '1', '2020-11-14')")
    c.execute("INSERT INTO subscription VALUES ('614', '4', '2021-02-14')")
    c.execute("INSERT INTO subscription VALUES ('615', '0', '2020-06-27')")
    c.execute("INSERT INTO subscription VALUES ('615', '2', '2020-07-04')")
    c.execute("INSERT INTO subscription VALUES ('616', '0', '2020-03-20')")
    c.execute("INSERT INTO subscription VALUES ('616', '1', '2020-03-27')")
    c.execute("INSERT INTO subscription VALUES ('616', '4', '2020-03-31')")
    c.execute("INSERT INTO subscription VALUES ('617', '0', '2020-08-30')")
    c.execute("INSERT INTO subscription VALUES ('617', '3', '2020-09-06')")
    c.execute("INSERT INTO subscription VALUES ('618', '0', '2020-01-16')")
    c.execute("INSERT INTO subscription VALUES ('618', '1', '2020-01-23')")
    c.execute("INSERT INTO subscription VALUES ('618', '2', '2020-05-08')")
    c.execute("INSERT INTO subscription VALUES ('618', '4', '2020-08-27')")
    c.execute("INSERT INTO subscription VALUES ('619', '0', '2020-04-21')")
    c.execute("INSERT INTO subscription VALUES ('619', '2', '2020-04-28')")
    c.execute("INSERT INTO subscription VALUES ('620', '0', '2020-12-06')")
    c.execute("INSERT INTO subscription VALUES ('620', '1', '2020-12-13')")
    c.execute("INSERT INTO subscription VALUES ('621', '0', '2020-11-06')")
    c.execute("INSERT INTO subscription VALUES ('621', '1', '2020-11-13')")
    c.execute("INSERT INTO subscription VALUES ('622', '0', '2020-11-30')")
    c.execute("INSERT INTO subscription VALUES ('622', '1', '2020-12-07')")
    c.execute("INSERT INTO subscription VALUES ('623', '0', '2020-10-14')")
    c.execute("INSERT INTO subscription VALUES ('623', '2', '2020-10-21')")
    c.execute("INSERT INTO subscription VALUES ('624', '0', '2020-08-24')")
    c.execute("INSERT INTO subscription VALUES ('624', '2', '2020-08-31')")
    c.execute("INSERT INTO subscription VALUES ('625', '0', '2020-03-21')")
    c.execute("INSERT INTO subscription VALUES ('625', '2', '2020-03-28')")
    c.execute("INSERT INTO subscription VALUES ('626', '0', '2020-07-08')")
    c.execute("INSERT INTO subscription VALUES ('626', '1', '2020-07-15')")
    c.execute("INSERT INTO subscription VALUES ('627', '0', '2020-03-09')")
    c.execute("INSERT INTO subscription VALUES ('627', '2', '2020-03-16')")
    c.execute("INSERT INTO subscription VALUES ('628', '0', '2020-08-01')")
    c.execute("INSERT INTO subscription VALUES ('628', '2', '2020-08-08')")
    c.execute("INSERT INTO subscription VALUES ('628', '3', '2021-02-08')")
    c.execute("INSERT INTO subscription VALUES ('629', '0', '2020-11-04')")
    c.execute("INSERT INTO subscription VALUES ('629', '4', '2020-11-11')")
    c.execute("INSERT INTO subscription VALUES ('630', '0', '2020-01-26')")
    c.execute("INSERT INTO subscription VALUES ('630', '2', '2020-02-02')")
    c.execute("INSERT INTO subscription VALUES ('630', '4', '2020-06-02')")
    c.execute("INSERT INTO subscription VALUES ('631', '0', '2020-08-03')")
    c.execute("INSERT INTO subscription VALUES ('631', '1', '2020-08-10')")
    c.execute("INSERT INTO subscription VALUES ('631', '3', '2020-10-22')")
    c.execute("INSERT INTO subscription VALUES ('632', '0', '2020-04-24')")
    c.execute("INSERT INTO subscription VALUES ('632', '1', '2020-05-01')")
    c.execute("INSERT INTO subscription VALUES ('632', '2', '2020-08-17')")
    c.execute("INSERT INTO subscription VALUES ('633', '0', '2020-12-27')")
    c.execute("INSERT INTO subscription VALUES ('633', '4', '2021-01-03')")
    c.execute("INSERT INTO subscription VALUES ('634', '0', '2020-07-15')")
    c.execute("INSERT INTO subscription VALUES ('634', '4', '2020-07-22')")
    c.execute("INSERT INTO subscription VALUES ('635', '0', '2020-02-17')")
    c.execute("INSERT INTO subscription VALUES ('635', '1', '2020-02-24')")
    c.execute("INSERT INTO subscription VALUES ('635', '3', '2020-05-27')")
    c.execute("INSERT INTO subscription VALUES ('636', '0', '2020-09-25')")
    c.execute("INSERT INTO subscription VALUES ('636', '1', '2020-10-02')")
    c.execute("INSERT INTO subscription VALUES ('637', '0', '2020-09-20')")
    c.execute("INSERT INTO subscription VALUES ('637', '1', '2020-09-27')")
    c.execute("INSERT INTO subscription VALUES ('638', '0', '2020-09-03')")
    c.execute("INSERT INTO subscription VALUES ('638', '4', '2020-09-10')")
    c.execute("INSERT INTO subscription VALUES ('639', '0', '2020-07-20')")
    c.execute("INSERT INTO subscription VALUES ('639', '3', '2020-07-27')")
    c.execute("INSERT INTO subscription VALUES ('640', '0', '2020-03-17')")
    c.execute("INSERT INTO subscription VALUES ('640', '1', '2020-03-24')")
    c.execute("INSERT INTO subscription VALUES ('640', '2', '2020-08-13')")
    c.execute("INSERT INTO subscription VALUES ('641', '0', '2020-02-25')")
    c.execute("INSERT INTO subscription VALUES ('641', '2', '2020-03-03')")
    c.execute("INSERT INTO subscription VALUES ('641', '4', '2020-06-06')")
    c.execute("INSERT INTO subscription VALUES ('642', '0', '2020-03-18')")
    c.execute("INSERT INTO subscription VALUES ('642', '1', '2020-03-25')")
    c.execute("INSERT INTO subscription VALUES ('642', '4', '2020-05-08')")
    c.execute("INSERT INTO subscription VALUES ('643', '0', '2020-04-03')")
    c.execute("INSERT INTO subscription VALUES ('643', '1', '2020-04-10')")
    c.execute("INSERT INTO subscription VALUES ('643', '2', '2020-09-17')")
    c.execute("INSERT INTO subscription VALUES ('644', '0', '2020-01-03')")
    c.execute("INSERT INTO subscription VALUES ('644', '1', '2020-01-10')")
    c.execute("INSERT INTO subscription VALUES ('645', '0', '2020-05-07')")
    c.execute("INSERT INTO subscription VALUES ('645', '2', '2020-05-14')")
    c.execute("INSERT INTO subscription VALUES ('645', '4', '2020-05-20')")
    c.execute("INSERT INTO subscription VALUES ('646', '0', '2020-02-28')")
    c.execute("INSERT INTO subscription VALUES ('646', '1', '2020-03-06')")
    c.execute("INSERT INTO subscription VALUES ('647', '0', '2020-05-01')")
    c.execute("INSERT INTO subscription VALUES ('647', '1', '2020-05-08')")
    c.execute("INSERT INTO subscription VALUES ('647', '2', '2020-08-06')")
    c.execute("INSERT INTO subscription VALUES ('647', '4', '2020-12-05')")
    c.execute("INSERT INTO subscription VALUES ('648', '0', '2020-03-16')")
    c.execute("INSERT INTO subscription VALUES ('648', '1', '2020-03-23')")
    c.execute("INSERT INTO subscription VALUES ('648', '3', '2020-05-30')")
    c.execute("INSERT INTO subscription VALUES ('649', '0', '2020-09-02')")
    c.execute("INSERT INTO subscription VALUES ('649', '2', '2020-09-09')")
    c.execute("INSERT INTO subscription VALUES ('649', '4', '2021-01-21')")
    c.execute("INSERT INTO subscription VALUES ('650', '0', '2020-04-16')")
    c.execute("INSERT INTO subscription VALUES ('650', '4', '2020-04-23')")
    c.execute("INSERT INTO subscription VALUES ('651', '0', '2020-06-12')")
    c.execute("INSERT INTO subscription VALUES ('651', '1', '2020-06-19')")
    c.execute("INSERT INTO subscription VALUES ('651', '2', '2020-09-02')")
    c.execute("INSERT INTO subscription VALUES ('651', '4', '2020-10-31')")
    c.execute("INSERT INTO subscription VALUES ('652', '0', '2020-07-20')")
    c.execute("INSERT INTO subscription VALUES ('652', '1', '2020-07-27')")
    c.execute("INSERT INTO subscription VALUES ('652', '3', '2020-09-25')")
    c.execute("INSERT INTO subscription VALUES ('653', '0', '2020-06-30')")
    c.execute("INSERT INTO subscription VALUES ('653', '2', '2020-07-07')")
    c.execute("INSERT INTO subscription VALUES ('653', '4', '2020-07-22')")
    c.execute("INSERT INTO subscription VALUES ('654', '0', '2020-12-01')")
    c.execute("INSERT INTO subscription VALUES ('654', '1', '2020-12-08')")
    c.execute("INSERT INTO subscription VALUES ('654', '4', '2021-03-10')")
    c.execute("INSERT INTO subscription VALUES ('655', '0', '2020-04-22')")
    c.execute("INSERT INTO subscription VALUES ('655', '1', '2020-04-29')")
    c.execute("INSERT INTO subscription VALUES ('655', '2', '2020-05-16')")
    c.execute("INSERT INTO subscription VALUES ('656', '0', '2020-05-22')")
    c.execute("INSERT INTO subscription VALUES ('656', '2', '2020-05-29')")
    c.execute("INSERT INTO subscription VALUES ('657', '0', '2020-09-25')")
    c.execute("INSERT INTO subscription VALUES ('657', '4', '2020-10-02')")
    c.execute("INSERT INTO subscription VALUES ('658', '0', '2020-11-14')")
    c.execute("INSERT INTO subscription VALUES ('658', '1', '2020-11-21')")
    c.execute("INSERT INTO subscription VALUES ('658', '2', '2021-01-27')")
    c.execute("INSERT INTO subscription VALUES ('659', '0', '2020-09-30')")
    c.execute("INSERT INTO subscription VALUES ('659', '2', '2020-10-07')")
    c.execute("INSERT INTO subscription VALUES ('660', '0', '2020-05-02')")
    c.execute("INSERT INTO subscription VALUES ('660', '4', '2020-05-09')")
    c.execute("INSERT INTO subscription VALUES ('661', '0', '2020-04-13')")
    c.execute("INSERT INTO subscription VALUES ('661', '1', '2020-04-20')")
    c.execute("INSERT INTO subscription VALUES ('661', '2', '2020-07-09')")
    c.execute("INSERT INTO subscription VALUES ('661', '3', '2020-10-09')")
    c.execute("INSERT INTO subscription VALUES ('662', '0', '2020-01-28')")
    c.execute("INSERT INTO subscription VALUES ('662', '2', '2020-02-04')")
    c.execute("INSERT INTO subscription VALUES ('663', '0', '2020-09-13')")
    c.execute("INSERT INTO subscription VALUES ('663', '2', '2020-09-20')")
    c.execute("INSERT INTO subscription VALUES ('664', '0', '2020-01-30')")
    c.execute("INSERT INTO subscription VALUES ('664', '1', '2020-02-06')")
    c.execute("INSERT INTO subscription VALUES ('664', '3', '2020-04-20')")
    c.execute("INSERT INTO subscription VALUES ('664', '4', '2021-04-20')")
    c.execute("INSERT INTO subscription VALUES ('665', '0', '2020-09-24')")
    c.execute("INSERT INTO subscription VALUES ('665', '1', '2020-10-01')")
    c.execute("INSERT INTO subscription VALUES ('666', '0', '2020-12-10')")
    c.execute("INSERT INTO subscription VALUES ('666', '2', '2020-12-17')")
    c.execute("INSERT INTO subscription VALUES ('667', '0', '2020-12-25')")
    c.execute("INSERT INTO subscription VALUES ('667', '2', '2021-01-01')")
    c.execute("INSERT INTO subscription VALUES ('668', '0', '2020-02-13')")
    c.execute("INSERT INTO subscription VALUES ('668', '1', '2020-02-20')")
    c.execute("INSERT INTO subscription VALUES ('668', '3', '2020-06-14')")
    c.execute("INSERT INTO subscription VALUES ('669', '0', '2020-11-28')")
    c.execute("INSERT INTO subscription VALUES ('669', '1', '2020-12-05')")
    c.execute("INSERT INTO subscription VALUES ('669', '2', '2021-04-24')")
    c.execute("INSERT INTO subscription VALUES ('670', '0', '2020-01-03')")
    c.execute("INSERT INTO subscription VALUES ('670', '2', '2020-01-10')")
    c.execute("INSERT INTO subscription VALUES ('670', '4', '2020-02-18')")
    c.execute("INSERT INTO subscription VALUES ('671', '0', '2020-06-01')")
    c.execute("INSERT INTO subscription VALUES ('671', '3', '2020-06-08')")
    c.execute("INSERT INTO subscription VALUES ('672', '0', '2020-12-29')")
    c.execute("INSERT INTO subscription VALUES ('672', '2', '2021-01-05')")
    c.execute("INSERT INTO subscription VALUES ('672', '4', '2021-03-01')")
    c.execute("INSERT INTO subscription VALUES ('673', '0', '2020-01-01')")
    c.execute("INSERT INTO subscription VALUES ('673', '1', '2020-01-08')")
    c.execute("INSERT INTO subscription VALUES ('674', '0', '2020-02-03')")
    c.execute("INSERT INTO subscription VALUES ('674', '1', '2020-02-10')")
    c.execute("INSERT INTO subscription VALUES ('674', '4', '2020-04-12')")
    c.execute("INSERT INTO subscription VALUES ('675', '0', '2020-04-25')")
    c.execute("INSERT INTO subscription VALUES ('675', '2', '2020-05-02')")
    c.execute("INSERT INTO subscription VALUES ('676', '0', '2020-04-22')")
    c.execute("INSERT INTO subscription VALUES ('676', '1', '2020-04-29')")
    c.execute("INSERT INTO subscription VALUES ('676', '2', '2020-06-08')")
    c.execute("INSERT INTO subscription VALUES ('677', '0', '2020-12-15')")
    c.execute("INSERT INTO subscription VALUES ('677', '1', '2020-12-22')")
    c.execute("INSERT INTO subscription VALUES ('678', '0', '2020-03-05')")
    c.execute("INSERT INTO subscription VALUES ('678', '1', '2020-03-12')")
    c.execute("INSERT INTO subscription VALUES ('679', '0', '2020-06-10')")
    c.execute("INSERT INTO subscription VALUES ('679', '2', '2020-06-17')")
    c.execute("INSERT INTO subscription VALUES ('679', '4', '2020-11-30')")
    c.execute("INSERT INTO subscription VALUES ('680', '0', '2020-04-11')")
    c.execute("INSERT INTO subscription VALUES ('680', '1', '2020-04-18')")
    c.execute("INSERT INTO subscription VALUES ('681', '0', '2020-02-23')")
    c.execute("INSERT INTO subscription VALUES ('681', '2', '2020-03-01')")
    c.execute("INSERT INTO subscription VALUES ('682', '0', '2020-08-21')")
    c.execute("INSERT INTO subscription VALUES ('682', '1', '2020-08-28')")
    c.execute("INSERT INTO subscription VALUES ('682', '2', '2020-10-15')")
    c.execute("INSERT INTO subscription VALUES ('683', '0', '2020-07-19')")
    c.execute("INSERT INTO subscription VALUES ('683', '1', '2020-07-26')")
    c.execute("INSERT INTO subscription VALUES ('683', '4', '2020-08-06')")
    c.execute("INSERT INTO subscription VALUES ('684', '0', '2020-06-09')")
    c.execute("INSERT INTO subscription VALUES ('684', '1', '2020-06-16')")
    c.execute("INSERT INTO subscription VALUES ('684', '2', '2020-11-16')")
    c.execute("INSERT INTO subscription VALUES ('684', '3', '2020-12-16')")
    c.execute("INSERT INTO subscription VALUES ('685', '0', '2020-05-09')")
    c.execute("INSERT INTO subscription VALUES ('685', '1', '2020-05-16')")
    c.execute("INSERT INTO subscription VALUES ('685', '2', '2020-11-09')")
    c.execute("INSERT INTO subscription VALUES ('685', '4', '2021-02-09')")
    c.execute("INSERT INTO subscription VALUES ('686', '0', '2020-07-24')")
    c.execute("INSERT INTO subscription VALUES ('686', '1', '2020-07-31')")
    c.execute("INSERT INTO subscription VALUES ('686', '2', '2020-10-11')")
    c.execute("INSERT INTO subscription VALUES ('686', '4', '2020-11-02')")
    c.execute("INSERT INTO subscription VALUES ('687', '0', '2020-05-23')")
    c.execute("INSERT INTO subscription VALUES ('687', '1', '2020-05-30')")
    c.execute("INSERT INTO subscription VALUES ('688', '0', '2020-08-13')")
    c.execute("INSERT INTO subscription VALUES ('688', '1', '2020-08-20')")
    c.execute("INSERT INTO subscription VALUES ('688', '3', '2020-09-20')")
    c.execute("INSERT INTO subscription VALUES ('689', '0', '2020-12-09')")
    c.execute("INSERT INTO subscription VALUES ('689', '2', '2020-12-16')")
    c.execute("INSERT INTO subscription VALUES ('690', '0', '2020-04-28')")
    c.execute("INSERT INTO subscription VALUES ('690', '1', '2020-05-05')")
    c.execute("INSERT INTO subscription VALUES ('690', '2', '2020-06-13')")
    c.execute("INSERT INTO subscription VALUES ('691', '0', '2020-06-15')")
    c.execute("INSERT INTO subscription VALUES ('691', '2', '2020-06-22')")
    c.execute("INSERT INTO subscription VALUES ('691', '3', '2020-11-22')")
    c.execute("INSERT INTO subscription VALUES ('692', '0', '2020-11-23')")
    c.execute("INSERT INTO subscription VALUES ('692', '1', '2020-11-30')")
    c.execute("INSERT INTO subscription VALUES ('693', '0', '2020-08-13')")
    c.execute("INSERT INTO subscription VALUES ('693', '2', '2020-08-20')")
    c.execute("INSERT INTO subscription VALUES ('693', '3', '2020-09-20')")
    c.execute("INSERT INTO subscription VALUES ('694', '0', '2020-11-26')")
    c.execute("INSERT INTO subscription VALUES ('694', '1', '2020-12-03')")
    c.execute("INSERT INTO subscription VALUES ('695', '0', '2020-05-04')")
    c.execute("INSERT INTO subscription VALUES ('695', '2', '2020-05-11')")
    c.execute("INSERT INTO subscription VALUES ('696', '0', '2020-09-27')")
    c.execute("INSERT INTO subscription VALUES ('696', '1', '2020-10-04')")
    c.execute("INSERT INTO subscription VALUES ('697', '0', '2020-01-23')")
    c.execute("INSERT INTO subscription VALUES ('697', '1', '2020-01-30')")
    c.execute("INSERT INTO subscription VALUES ('698', '0', '2020-11-12')")
    c.execute("INSERT INTO subscription VALUES ('698', '1', '2020-11-19')")
    c.execute("INSERT INTO subscription VALUES ('698', '2', '2021-01-28')")
    c.execute("INSERT INTO subscription VALUES ('699', '0', '2020-06-19')")
    c.execute("INSERT INTO subscription VALUES ('699', '2', '2020-06-26')")
    c.execute("INSERT INTO subscription VALUES ('700', '0', '2020-12-06')")
    c.execute("INSERT INTO subscription VALUES ('700', '2', '2020-12-13')")
    c.execute("INSERT INTO subscription VALUES ('700', '3', '2021-03-13')")
    c.execute("INSERT INTO subscription VALUES ('701', '0', '2020-05-10')")
    c.execute("INSERT INTO subscription VALUES ('701', '1', '2020-05-17')")
    c.execute("INSERT INTO subscription VALUES ('701', '4', '2020-11-07')")
    c.execute("INSERT INTO subscription VALUES ('702', '0', '2020-01-08')")
    c.execute("INSERT INTO subscription VALUES ('702', '2', '2020-01-15')")
    c.execute("INSERT INTO subscription VALUES ('702', '4', '2020-02-27')")
    c.execute("INSERT INTO subscription VALUES ('703', '0', '2020-11-02')")
    c.execute("INSERT INTO subscription VALUES ('703', '1', '2020-11-09')")
    c.execute("INSERT INTO subscription VALUES ('703', '4', '2020-12-04')")
    c.execute("INSERT INTO subscription VALUES ('704', '0', '2020-12-06')")
    c.execute("INSERT INTO subscription VALUES ('704', '1', '2020-12-13')")
    c.execute("INSERT INTO subscription VALUES ('704', '4', '2021-01-19')")
    c.execute("INSERT INTO subscription VALUES ('705', '0', '2020-07-15')")
    c.execute("INSERT INTO subscription VALUES ('705', '1', '2020-07-22')")
    c.execute("INSERT INTO subscription VALUES ('705', '2', '2020-12-14')")
    c.execute("INSERT INTO subscription VALUES ('705', '4', '2021-02-06')")
    c.execute("INSERT INTO subscription VALUES ('706', '0', '2020-12-07')")
    c.execute("INSERT INTO subscription VALUES ('706', '1', '2020-12-14')")
    c.execute("INSERT INTO subscription VALUES ('706', '4', '2021-01-24')")
    c.execute("INSERT INTO subscription VALUES ('707', '0', '2020-08-30')")
    c.execute("INSERT INTO subscription VALUES ('707', '1', '2020-09-06')")
    c.execute("INSERT INTO subscription VALUES ('707', '2', '2021-02-28')")
    c.execute("INSERT INTO subscription VALUES ('708', '0', '2020-07-05')")
    c.execute("INSERT INTO subscription VALUES ('708', '4', '2020-07-12')")
    c.execute("INSERT INTO subscription VALUES ('709', '0', '2020-03-11')")
    c.execute("INSERT INTO subscription VALUES ('709', '1', '2020-03-18')")
    c.execute("INSERT INTO subscription VALUES ('709', '4', '2020-03-30')")
    c.execute("INSERT INTO subscription VALUES ('710', '0', '2020-09-29')")
    c.execute("INSERT INTO subscription VALUES ('710', '1', '2020-10-06')")
    c.execute("INSERT INTO subscription VALUES ('710', '4', '2020-12-24')")
    c.execute("INSERT INTO subscription VALUES ('711', '0', '2020-10-02')")
    c.execute("INSERT INTO subscription VALUES ('711', '1', '2020-10-09')")
    c.execute("INSERT INTO subscription VALUES ('711', '2', '2020-11-16')")
    c.execute("INSERT INTO subscription VALUES ('711', '4', '2020-12-31')")
    c.execute("INSERT INTO subscription VALUES ('712', '0', '2020-12-26')")
    c.execute("INSERT INTO subscription VALUES ('712', '1', '2021-01-02')")
    c.execute("INSERT INTO subscription VALUES ('713', '0', '2020-09-15')")
    c.execute("INSERT INTO subscription VALUES ('713', '2', '2020-09-22')")
    c.execute("INSERT INTO subscription VALUES ('714', '0', '2020-07-28')")
    c.execute("INSERT INTO subscription VALUES ('714', '2', '2020-08-04')")
    c.execute("INSERT INTO subscription VALUES ('715', '0', '2020-02-21')")
    c.execute("INSERT INTO subscription VALUES ('715', '3', '2020-02-28')")
    c.execute("INSERT INTO subscription VALUES ('716', '0', '2020-12-23')")
    c.execute("INSERT INTO subscription VALUES ('716', '1', '2020-12-30')")
    c.execute("INSERT INTO subscription VALUES ('716', '4', '2021-02-16')")
    c.execute("INSERT INTO subscription VALUES ('717', '0', '2020-01-08')")
    c.execute("INSERT INTO subscription VALUES ('717', '2', '2020-01-15')")
    c.execute("INSERT INTO subscription VALUES ('717', '3', '2020-06-15')")
    c.execute("INSERT INTO subscription VALUES ('718', '0', '2020-05-24')")
    c.execute("INSERT INTO subscription VALUES ('718', '1', '2020-05-31')")
    c.execute("INSERT INTO subscription VALUES ('719', '0', '2020-04-11')")
    c.execute("INSERT INTO subscription VALUES ('719', '1', '2020-04-18')")
    c.execute("INSERT INTO subscription VALUES ('720', '0', '2020-04-27')")
    c.execute("INSERT INTO subscription VALUES ('720', '2', '2020-05-04')")
    c.execute("INSERT INTO subscription VALUES ('721', '0', '2020-08-12')")
    c.execute("INSERT INTO subscription VALUES ('721', '1', '2020-08-19')")
    c.execute("INSERT INTO subscription VALUES ('722', '0', '2020-08-21')")
    c.execute("INSERT INTO subscription VALUES ('722', '1', '2020-08-28')")
    c.execute("INSERT INTO subscription VALUES ('722', '4', '2021-01-31')")
    c.execute("INSERT INTO subscription VALUES ('723', '0', '2020-05-26')")
    c.execute("INSERT INTO subscription VALUES ('723', '2', '2020-06-02')")
    c.execute("INSERT INTO subscription VALUES ('724', '0', '2020-10-03')")
    c.execute("INSERT INTO subscription VALUES ('724', '2', '2020-10-10')")
    c.execute("INSERT INTO subscription VALUES ('724', '4', '2020-11-06')")
    c.execute("INSERT INTO subscription VALUES ('725', '0', '2020-05-30')")
    c.execute("INSERT INTO subscription VALUES ('725', '2', '2020-06-06')")
    c.execute("INSERT INTO subscription VALUES ('725', '3', '2020-07-06')")
    c.execute("INSERT INTO subscription VALUES ('726', '0', '2020-03-02')")
    c.execute("INSERT INTO subscription VALUES ('726', '4', '2020-03-09')")
    c.execute("INSERT INTO subscription VALUES ('727', '0', '2020-04-05')")
    c.execute("INSERT INTO subscription VALUES ('727', '2', '2020-04-12')")
    c.execute("INSERT INTO subscription VALUES ('728', '0', '2020-06-17')")
    c.execute("INSERT INTO subscription VALUES ('728', '1', '2020-06-24')")
    c.execute("INSERT INTO subscription VALUES ('729', '0', '2020-04-03')")
    c.execute("INSERT INTO subscription VALUES ('729', '1', '2020-04-10')")
    c.execute("INSERT INTO subscription VALUES ('729', '2', '2020-08-17')")
    c.execute("INSERT INTO subscription VALUES ('730', '0', '2020-08-15')")
    c.execute("INSERT INTO subscription VALUES ('730', '1', '2020-08-22')")
    c.execute("INSERT INTO subscription VALUES ('730', '3', '2020-10-27')")
    c.execute("INSERT INTO subscription VALUES ('731', '0', '2020-09-13')")
    c.execute("INSERT INTO subscription VALUES ('731', '1', '2020-09-20')")
    c.execute("INSERT INTO subscription VALUES ('731', '2', '2020-09-29')")
    c.execute("INSERT INTO subscription VALUES ('731', '4', '2021-03-07')")
    c.execute("INSERT INTO subscription VALUES ('732', '0', '2020-06-16')")
    c.execute("INSERT INTO subscription VALUES ('732', '4', '2020-06-23')")
    c.execute("INSERT INTO subscription VALUES ('733', '0', '2020-04-11')")
    c.execute("INSERT INTO subscription VALUES ('733', '1', '2020-04-18')")
    c.execute("INSERT INTO subscription VALUES ('733', '4', '2020-04-24')")
    c.execute("INSERT INTO subscription VALUES ('734', '0', '2020-09-05')")
    c.execute("INSERT INTO subscription VALUES ('734', '2', '2020-09-12')")
    c.execute("INSERT INTO subscription VALUES ('735', '0', '2020-11-23')")
    c.execute("INSERT INTO subscription VALUES ('735', '1', '2020-11-30')")
    c.execute("INSERT INTO subscription VALUES ('735', '4', '2021-04-04')")
    c.execute("INSERT INTO subscription VALUES ('736', '0', '2020-03-19')")
    c.execute("INSERT INTO subscription VALUES ('736', '1', '2020-03-26')")
    c.execute("INSERT INTO subscription VALUES ('736', '2', '2020-04-07')")
    c.execute("INSERT INTO subscription VALUES ('736', '4', '2020-06-04')")
    c.execute("INSERT INTO subscription VALUES ('737', '0', '2020-11-04')")
    c.execute("INSERT INTO subscription VALUES ('737', '1', '2020-11-11')")
    c.execute("INSERT INTO subscription VALUES ('738', '0', '2020-01-22')")
    c.execute("INSERT INTO subscription VALUES ('738', '3', '2020-01-29')")
    c.execute("INSERT INTO subscription VALUES ('739', '0', '2020-12-06')")
    c.execute("INSERT INTO subscription VALUES ('739', '2', '2020-12-13')")
    c.execute("INSERT INTO subscription VALUES ('740', '0', '2020-12-30')")
    c.execute("INSERT INTO subscription VALUES ('740', '1', '2021-01-06')")
    c.execute("INSERT INTO subscription VALUES ('740', '4', '2021-04-06')")
    c.execute("INSERT INTO subscription VALUES ('741', '0', '2020-03-24')")
    c.execute("INSERT INTO subscription VALUES ('741', '2', '2020-03-31')")
    c.execute("INSERT INTO subscription VALUES ('742', '0', '2020-08-13')")
    c.execute("INSERT INTO subscription VALUES ('742', '1', '2020-08-20')")
    c.execute("INSERT INTO subscription VALUES ('742', '3', '2020-11-22')")
    c.execute("INSERT INTO subscription VALUES ('743', '0', '2020-07-14')")
    c.execute("INSERT INTO subscription VALUES ('743', '3', '2020-07-21')")
    c.execute("INSERT INTO subscription VALUES ('744', '0', '2020-04-15')")
    c.execute("INSERT INTO subscription VALUES ('744', '2', '2020-04-22')")
    c.execute("INSERT INTO subscription VALUES ('744', '4', '2020-09-11')")
    c.execute("INSERT INTO subscription VALUES ('745', '0', '2020-03-05')")
    c.execute("INSERT INTO subscription VALUES ('745', '1', '2020-03-12')")
    c.execute("INSERT INTO subscription VALUES ('745', '3', '2020-08-25')")
    c.execute("INSERT INTO subscription VALUES ('746', '0', '2020-11-28')")
    c.execute("INSERT INTO subscription VALUES ('746', '1', '2020-12-05')")
    c.execute("INSERT INTO subscription VALUES ('746', '2', '2021-02-23')")
    c.execute("INSERT INTO subscription VALUES ('746', '3', '2021-04-23')")
    c.execute("INSERT INTO subscription VALUES ('747', '0', '2020-11-10')")
    c.execute("INSERT INTO subscription VALUES ('747', '2', '2020-11-17')")
    c.execute("INSERT INTO subscription VALUES ('748', '0', '2020-02-29')")
    c.execute("INSERT INTO subscription VALUES ('748', '2', '2020-03-07')")
    c.execute("INSERT INTO subscription VALUES ('748', '4', '2020-07-10')")
    c.execute("INSERT INTO subscription VALUES ('749', '0', '2020-02-02')")
    c.execute("INSERT INTO subscription VALUES ('749', '2', '2020-02-09')")
    c.execute("INSERT INTO subscription VALUES ('750', '0', '2020-07-03')")
    c.execute("INSERT INTO subscription VALUES ('750', '4', '2020-07-10')")
    c.execute("INSERT INTO subscription VALUES ('751', '0', '2020-05-31')")
    c.execute("INSERT INTO subscription VALUES ('751', '1', '2020-06-07')")
    c.execute("INSERT INTO subscription VALUES ('752', '0', '2020-10-28')")
    c.execute("INSERT INTO subscription VALUES ('752', '4', '2020-11-04')")
    c.execute("INSERT INTO subscription VALUES ('753', '0', '2020-08-26')")
    c.execute("INSERT INTO subscription VALUES ('753', '1', '2020-09-02')")
    c.execute("INSERT INTO subscription VALUES ('753', '2', '2021-01-23')")
    c.execute("INSERT INTO subscription VALUES ('754', '0', '2020-04-26')")
    c.execute("INSERT INTO subscription VALUES ('754', '1', '2020-05-03')")
    c.execute("INSERT INTO subscription VALUES ('754', '4', '2020-05-09')")
    c.execute("INSERT INTO subscription VALUES ('755', '0', '2020-05-09')")
    c.execute("INSERT INTO subscription VALUES ('755', '1', '2020-05-16')")
    c.execute("INSERT INTO subscription VALUES ('755', '3', '2020-10-22')")
    c.execute("INSERT INTO subscription VALUES ('756', '0', '2020-02-19')")
    c.execute("INSERT INTO subscription VALUES ('756', '4', '2020-02-26')")
    c.execute("INSERT INTO subscription VALUES ('757', '0', '2020-11-05')")
    c.execute("INSERT INTO subscription VALUES ('757', '4', '2020-11-12')")
    c.execute("INSERT INTO subscription VALUES ('758', '0', '2020-10-28')")
    c.execute("INSERT INTO subscription VALUES ('758', '1', '2020-11-04')")
    c.execute("INSERT INTO subscription VALUES ('758', '2', '2020-12-30')")
    c.execute("INSERT INTO subscription VALUES ('759', '0', '2020-11-11')")
    c.execute("INSERT INTO subscription VALUES ('759', '2', '2020-11-18')")
    c.execute("INSERT INTO subscription VALUES ('760', '0', '2020-09-27')")
    c.execute("INSERT INTO subscription VALUES ('760', '4', '2020-10-04')")
    c.execute("INSERT INTO subscription VALUES ('761', '0', '2020-11-18')")
    c.execute("INSERT INTO subscription VALUES ('761', '1', '2020-11-25')")
    c.execute("INSERT INTO subscription VALUES ('761', '2', '2021-01-19')")
    c.execute("INSERT INTO subscription VALUES ('761', '3', '2021-02-19')")
    c.execute("INSERT INTO subscription VALUES ('762', '0', '2020-10-07')")
    c.execute("INSERT INTO subscription VALUES ('762', '2', '2020-10-14')")
    c.execute("INSERT INTO subscription VALUES ('763', '0', '2020-07-02')")
    c.execute("INSERT INTO subscription VALUES ('763', '2', '2020-07-09')")
    c.execute("INSERT INTO subscription VALUES ('764', '0', '2020-03-04')")
    c.execute("INSERT INTO subscription VALUES ('764', '2', '2020-03-11')")
    c.execute("INSERT INTO subscription VALUES ('765', '0', '2020-11-17')")
    c.execute("INSERT INTO subscription VALUES ('765', '1', '2020-11-24')")
    c.execute("INSERT INTO subscription VALUES ('765', '4', '2021-03-12')")
    c.execute("INSERT INTO subscription VALUES ('766', '0', '2020-12-14')")
    c.execute("INSERT INTO subscription VALUES ('766', '1', '2020-12-21')")
    c.execute("INSERT INTO subscription VALUES ('766', '2', '2021-03-02')")
    c.execute("INSERT INTO subscription VALUES ('766', '4', '2021-04-05')")
    c.execute("INSERT INTO subscription VALUES ('767', '0', '2020-08-21')")
    c.execute("INSERT INTO subscription VALUES ('767', '1', '2020-08-28')")
    c.execute("INSERT INTO subscription VALUES ('767', '3', '2020-12-26')")
    c.execute("INSERT INTO subscription VALUES ('768', '0', '2020-03-23')")
    c.execute("INSERT INTO subscription VALUES ('768', '1', '2020-03-30')")
    c.execute("INSERT INTO subscription VALUES ('768', '4', '2020-06-01')")
    c.execute("INSERT INTO subscription VALUES ('769', '0', '2020-11-10')")
    c.execute("INSERT INTO subscription VALUES ('769', '1', '2020-11-17')")
    c.execute("INSERT INTO subscription VALUES ('769', '4', '2021-02-26')")
    c.execute("INSERT INTO subscription VALUES ('770', '0', '2020-12-03')")
    c.execute("INSERT INTO subscription VALUES ('770', '1', '2020-12-10')")
    c.execute("INSERT INTO subscription VALUES ('771', '0', '2020-05-20')")
    c.execute("INSERT INTO subscription VALUES ('771', '4', '2020-05-27')")
    c.execute("INSERT INTO subscription VALUES ('772', '0', '2020-06-11')")
    c.execute("INSERT INTO subscription VALUES ('772', '1', '2020-06-18')")
    c.execute("INSERT INTO subscription VALUES ('772', '4', '2020-08-20')")
    c.execute("INSERT INTO subscription VALUES ('773', '0', '2020-09-29')")
    c.execute("INSERT INTO subscription VALUES ('773', '2', '2020-10-06')")
    c.execute("INSERT INTO subscription VALUES ('773', '4', '2021-01-21')")
    c.execute("INSERT INTO subscription VALUES ('774', '0', '2020-12-04')")
    c.execute("INSERT INTO subscription VALUES ('774', '2', '2020-12-11')")
    c.execute("INSERT INTO subscription VALUES ('775', '0', '2020-11-24')")
    c.execute("INSERT INTO subscription VALUES ('775', '1', '2020-12-01')")
    c.execute("INSERT INTO subscription VALUES ('775', '2', '2020-12-03')")
    c.execute("INSERT INTO subscription VALUES ('776', '0', '2020-12-14')")
    c.execute("INSERT INTO subscription VALUES ('776', '1', '2020-12-21')")
    c.execute("INSERT INTO subscription VALUES ('776', '3', '2021-04-29')")
    c.execute("INSERT INTO subscription VALUES ('777', '0', '2020-09-06')")
    c.execute("INSERT INTO subscription VALUES ('777', '2', '2020-09-13')")
    c.execute("INSERT INTO subscription VALUES ('777', '4', '2020-10-07')")
    c.execute("INSERT INTO subscription VALUES ('778', '0', '2020-06-02')")
    c.execute("INSERT INTO subscription VALUES ('778', '2', '2020-06-09')")
    c.execute("INSERT INTO subscription VALUES ('778', '3', '2020-11-09')")
    c.execute("INSERT INTO subscription VALUES ('779', '0', '2020-08-16')")
    c.execute("INSERT INTO subscription VALUES ('779', '1', '2020-08-23')")
    c.execute("INSERT INTO subscription VALUES ('779', '2', '2020-11-14')")
    c.execute("INSERT INTO subscription VALUES ('780', '0', '2020-08-13')")
    c.execute("INSERT INTO subscription VALUES ('780', '1', '2020-08-20')")
    c.execute("INSERT INTO subscription VALUES ('780', '2', '2020-12-27')")
    c.execute("INSERT INTO subscription VALUES ('780', '3', '2021-04-27')")
    c.execute("INSERT INTO subscription VALUES ('781', '0', '2020-11-10')")
    c.execute("INSERT INTO subscription VALUES ('781', '1', '2020-11-17')")
    c.execute("INSERT INTO subscription VALUES ('782', '0', '2020-09-08')")
    c.execute("INSERT INTO subscription VALUES ('782', '2', '2020-09-15')")
    c.execute("INSERT INTO subscription VALUES ('783', '0', '2020-05-28')")
    c.execute("INSERT INTO subscription VALUES ('783', '3', '2020-06-04')")
    c.execute("INSERT INTO subscription VALUES ('784', '0', '2020-12-02')")
    c.execute("INSERT INTO subscription VALUES ('784', '4', '2020-12-09')")
    c.execute("INSERT INTO subscription VALUES ('785', '0', '2020-04-12')")
    c.execute("INSERT INTO subscription VALUES ('785', '2', '2020-04-19')")
    c.execute("INSERT INTO subscription VALUES ('786', '0', '2020-05-10')")
    c.execute("INSERT INTO subscription VALUES ('786', '4', '2020-05-17')")
    c.execute("INSERT INTO subscription VALUES ('787', '0', '2020-09-20')")
    c.execute("INSERT INTO subscription VALUES ('787', '2', '2020-09-27')")
    c.execute("INSERT INTO subscription VALUES ('788', '0', '2020-05-11')")
    c.execute("INSERT INTO subscription VALUES ('788', '1', '2020-05-18')")
    c.execute("INSERT INTO subscription VALUES ('788', '2', '2020-06-23')")
    c.execute("INSERT INTO subscription VALUES ('789', '0', '2020-06-28')")
    c.execute("INSERT INTO subscription VALUES ('789', '1', '2020-07-05')")
    c.execute("INSERT INTO subscription VALUES ('790', '0', '2020-03-10')")
    c.execute("INSERT INTO subscription VALUES ('790', '1', '2020-03-17')")
    c.execute("INSERT INTO subscription VALUES ('791', '0', '2020-07-24')")
    c.execute("INSERT INTO subscription VALUES ('791', '4', '2020-07-31')")
    c.execute("INSERT INTO subscription VALUES ('792', '0', '2020-09-19')")
    c.execute("INSERT INTO subscription VALUES ('792', '1', '2020-09-26')")
    c.execute("INSERT INTO subscription VALUES ('792', '2', '2020-12-27')")
    c.execute("INSERT INTO subscription VALUES ('793', '0', '2020-05-07')")
    c.execute("INSERT INTO subscription VALUES ('793', '1', '2020-05-14')")
    c.execute("INSERT INTO subscription VALUES ('793', '4', '2020-10-19')")
    c.execute("INSERT INTO subscription VALUES ('794', '0', '2020-08-22')")
    c.execute("INSERT INTO subscription VALUES ('794', '2', '2020-08-29')")
    c.execute("INSERT INTO subscription VALUES ('795', '0', '2020-08-22')")
    c.execute("INSERT INTO subscription VALUES ('795', '1', '2020-08-29')")
    c.execute("INSERT INTO subscription VALUES ('795', '3', '2020-12-13')")
    c.execute("INSERT INTO subscription VALUES ('796', '0', '2020-04-28')")
    c.execute("INSERT INTO subscription VALUES ('796', '2', '2020-05-05')")
    c.execute("INSERT INTO subscription VALUES ('796', '4', '2020-06-07')")
    c.execute("INSERT INTO subscription VALUES ('797', '0', '2020-01-17')")
    c.execute("INSERT INTO subscription VALUES ('797', '2', '2020-01-24')")
    c.execute("INSERT INTO subscription VALUES ('798', '0', '2020-10-11')")
    c.execute("INSERT INTO subscription VALUES ('798', '1', '2020-10-18')")
    c.execute("INSERT INTO subscription VALUES ('798', '2', '2020-12-05')")
    c.execute("INSERT INTO subscription VALUES ('798', '3', '2021-03-05')")
    c.execute("INSERT INTO subscription VALUES ('799', '0', '2020-12-12')")
    c.execute("INSERT INTO subscription VALUES ('799', '2', '2020-12-19')")
    c.execute("INSERT INTO subscription VALUES ('800', '0', '2020-05-12')")
    c.execute("INSERT INTO subscription VALUES ('800', '4', '2020-05-19')")
    c.execute("INSERT INTO subscription VALUES ('801', '0', '2020-08-11')")
    c.execute("INSERT INTO subscription VALUES ('801', '2', '2020-08-18')")
    c.execute("INSERT INTO subscription VALUES ('802', '0', '2020-02-05')")
    c.execute("INSERT INTO subscription VALUES ('802', '3', '2020-02-12')")
    c.execute("INSERT INTO subscription VALUES ('803', '0', '2020-01-23')")
    c.execute("INSERT INTO subscription VALUES ('803', '4', '2020-01-30')")
    c.execute("INSERT INTO subscription VALUES ('804', '0', '2020-07-12')")
    c.execute("INSERT INTO subscription VALUES ('804', '1', '2020-07-19')")
    c.execute("INSERT INTO subscription VALUES ('804', '2', '2020-11-13')")
    c.execute("INSERT INTO subscription VALUES ('804', '4', '2020-11-27')")
    c.execute("INSERT INTO subscription VALUES ('805', '0', '2020-04-02')")
    c.execute("INSERT INTO subscription VALUES ('805', '1', '2020-04-09')")
    c.execute("INSERT INTO subscription VALUES ('805', '2', '2020-09-02')")
    c.execute("INSERT INTO subscription VALUES ('806', '0', '2020-05-02')")
    c.execute("INSERT INTO subscription VALUES ('806', '1', '2020-05-09')")
    c.execute("INSERT INTO subscription VALUES ('806', '2', '2020-05-13')")
    c.execute("INSERT INTO subscription VALUES ('806', '3', '2020-06-13')")
    c.execute("INSERT INTO subscription VALUES ('807', '0', '2020-03-05')")
    c.execute("INSERT INTO subscription VALUES ('807', '1', '2020-03-12')")
    c.execute("INSERT INTO subscription VALUES ('807', '3', '2020-07-28')")
    c.execute("INSERT INTO subscription VALUES ('808', '0', '2020-05-17')")
    c.execute("INSERT INTO subscription VALUES ('808', '1', '2020-05-24')")
    c.execute("INSERT INTO subscription VALUES ('809', '0', '2020-10-20')")
    c.execute("INSERT INTO subscription VALUES ('809', '1', '2020-10-27')")
    c.execute("INSERT INTO subscription VALUES ('810', '0', '2020-11-22')")
    c.execute("INSERT INTO subscription VALUES ('810', '1', '2020-11-29')")
    c.execute("INSERT INTO subscription VALUES ('810', '4', '2020-12-02')")
    c.execute("INSERT INTO subscription VALUES ('811', '0', '2020-03-07')")
    c.execute("INSERT INTO subscription VALUES ('811', '1', '2020-03-14')")
    c.execute("INSERT INTO subscription VALUES ('811', '4', '2020-07-04')")
    c.execute("INSERT INTO subscription VALUES ('812', '0', '2020-05-13')")
    c.execute("INSERT INTO subscription VALUES ('812', '2', '2020-05-20')")
    c.execute("INSERT INTO subscription VALUES ('812', '4', '2020-11-15')")
    c.execute("INSERT INTO subscription VALUES ('813', '0', '2020-02-01')")
    c.execute("INSERT INTO subscription VALUES ('813', '2', '2020-02-08')")
    c.execute("INSERT INTO subscription VALUES ('814', '0', '2020-11-11')")
    c.execute("INSERT INTO subscription VALUES ('814', '1', '2020-11-18')")
    c.execute("INSERT INTO subscription VALUES ('814', '4', '2021-04-02')")
    c.execute("INSERT INTO subscription VALUES ('815', '0', '2020-12-02')")
    c.execute("INSERT INTO subscription VALUES ('815', '2', '2020-12-09')")
    c.execute("INSERT INTO subscription VALUES ('815', '3', '2021-01-09')")
    c.execute("INSERT INTO subscription VALUES ('816', '0', '2020-01-19')")
    c.execute("INSERT INTO subscription VALUES ('816', '4', '2020-01-26')")
    c.execute("INSERT INTO subscription VALUES ('817', '0', '2020-05-21')")
    c.execute("INSERT INTO subscription VALUES ('817', '2', '2020-05-28')")
    c.execute("INSERT INTO subscription VALUES ('817', '3', '2020-08-28')")
    c.execute("INSERT INTO subscription VALUES ('818', '0', '2020-01-16')")
    c.execute("INSERT INTO subscription VALUES ('818', '1', '2020-01-23')")
    c.execute("INSERT INTO subscription VALUES ('818', '2', '2020-06-25')")
    c.execute("INSERT INTO subscription VALUES ('819', '0', '2020-01-18')")
    c.execute("INSERT INTO subscription VALUES ('819', '1', '2020-01-25')")
    c.execute("INSERT INTO subscription VALUES ('819', '3', '2020-06-01')")
    c.execute("INSERT INTO subscription VALUES ('820', '0', '2020-07-22')")
    c.execute("INSERT INTO subscription VALUES ('820', '1', '2020-07-29')")
    c.execute("INSERT INTO subscription VALUES ('821', '0', '2020-04-15')")
    c.execute("INSERT INTO subscription VALUES ('821', '1', '2020-04-22')")
    c.execute("INSERT INTO subscription VALUES ('821', '2', '2020-10-06')")
    c.execute("INSERT INTO subscription VALUES ('822', '0', '2020-10-10')")
    c.execute("INSERT INTO subscription VALUES ('822', '1', '2020-10-17')")
    c.execute("INSERT INTO subscription VALUES ('822', '3', '2021-03-15')")
    c.execute("INSERT INTO subscription VALUES ('823', '0', '2020-04-07')")
    c.execute("INSERT INTO subscription VALUES ('823', '2', '2020-04-14')")
    c.execute("INSERT INTO subscription VALUES ('824', '0', '2020-02-14')")
    c.execute("INSERT INTO subscription VALUES ('824', '2', '2020-02-21')")
    c.execute("INSERT INTO subscription VALUES ('825', '0', '2020-09-27')")
    c.execute("INSERT INTO subscription VALUES ('825', '1', '2020-10-04')")
    c.execute("INSERT INTO subscription VALUES ('825', '2', '2020-11-10')")
    c.execute("INSERT INTO subscription VALUES ('826', '0', '2020-07-25')")
    c.execute("INSERT INTO subscription VALUES ('826', '1', '2020-08-01')")
    c.execute("INSERT INTO subscription VALUES ('827', '0', '2020-11-03')")
    c.execute("INSERT INTO subscription VALUES ('827', '1', '2020-11-10')")
    c.execute("INSERT INTO subscription VALUES ('828', '0', '2020-06-22')")
    c.execute("INSERT INTO subscription VALUES ('828', '1', '2020-06-29')")
    c.execute("INSERT INTO subscription VALUES ('828', '3', '2020-12-24')")
    c.execute("INSERT INTO subscription VALUES ('829', '0', '2020-04-13')")
    c.execute("INSERT INTO subscription VALUES ('829', '1', '2020-04-20')")
    c.execute("INSERT INTO subscription VALUES ('829', '4', '2020-09-23')")
    c.execute("INSERT INTO subscription VALUES ('830', '0', '2020-07-19')")
    c.execute("INSERT INTO subscription VALUES ('830', '1', '2020-07-26')")
    c.execute("INSERT INTO subscription VALUES ('830', '2', '2020-12-26')")
    c.execute("INSERT INTO subscription VALUES ('831', '0', '2020-08-10')")
    c.execute("INSERT INTO subscription VALUES ('831', '1', '2020-08-17')")
    c.execute("INSERT INTO subscription VALUES ('831', '2', '2020-11-13')")
    c.execute("INSERT INTO subscription VALUES ('831', '4', '2021-01-15')")
    c.execute("INSERT INTO subscription VALUES ('832', '0', '2020-03-07')")
    c.execute("INSERT INTO subscription VALUES ('832', '1', '2020-03-14')")
    c.execute("INSERT INTO subscription VALUES ('832', '2', '2020-07-13')")
    c.execute("INSERT INTO subscription VALUES ('833', '0', '2020-10-08')")
    c.execute("INSERT INTO subscription VALUES ('833', '2', '2020-10-15')")
    c.execute("INSERT INTO subscription VALUES ('833', '4', '2020-10-22')")
    c.execute("INSERT INTO subscription VALUES ('834', '0', '2020-07-05')")
    c.execute("INSERT INTO subscription VALUES ('834', '2', '2020-07-12')")
    c.execute("INSERT INTO subscription VALUES ('834', '3', '2020-11-12')")
    c.execute("INSERT INTO subscription VALUES ('835', '0', '2020-10-04')")
    c.execute("INSERT INTO subscription VALUES ('835', '1', '2020-10-11')")
    c.execute("INSERT INTO subscription VALUES ('835', '4', '2020-11-28')")
    c.execute("INSERT INTO subscription VALUES ('836', '0', '2020-03-24')")
    c.execute("INSERT INTO subscription VALUES ('836', '1', '2020-03-31')")
    c.execute("INSERT INTO subscription VALUES ('836', '3', '2020-04-16')")
    c.execute("INSERT INTO subscription VALUES ('837', '0', '2020-11-05')")
    c.execute("INSERT INTO subscription VALUES ('837', '2', '2020-11-12')")
    c.execute("INSERT INTO subscription VALUES ('838', '0', '2020-03-26')")
    c.execute("INSERT INTO subscription VALUES ('838', '1', '2020-04-02')")
    c.execute("INSERT INTO subscription VALUES ('838', '2', '2020-07-18')")
    c.execute("INSERT INTO subscription VALUES ('838', '3', '2020-10-18')")
    c.execute("INSERT INTO subscription VALUES ('839', '0', '2020-08-13')")
    c.execute("INSERT INTO subscription VALUES ('839', '4', '2020-08-20')")
    c.execute("INSERT INTO subscription VALUES ('840', '0', '2020-04-11')")
    c.execute("INSERT INTO subscription VALUES ('840', '2', '2020-04-18')")
    c.execute("INSERT INTO subscription VALUES ('840', '3', '2020-05-18')")
    c.execute("INSERT INTO subscription VALUES ('841', '0', '2020-03-12')")
    c.execute("INSERT INTO subscription VALUES ('841', '2', '2020-03-19')")
    c.execute("INSERT INTO subscription VALUES ('842', '0', '2020-02-11')")
    c.execute("INSERT INTO subscription VALUES ('842', '2', '2020-02-18')")
    c.execute("INSERT INTO subscription VALUES ('842', '4', '2020-08-14')")
    c.execute("INSERT INTO subscription VALUES ('843', '0', '2020-08-11')")
    c.execute("INSERT INTO subscription VALUES ('843', '1', '2020-08-18')")
    c.execute("INSERT INTO subscription VALUES ('843', '2', '2021-02-04')")
    c.execute("INSERT INTO subscription VALUES ('844', '0', '2020-10-14')")
    c.execute("INSERT INTO subscription VALUES ('844', '4', '2020-10-21')")
    c.execute("INSERT INTO subscription VALUES ('845', '0', '2020-04-21')")
    c.execute("INSERT INTO subscription VALUES ('845', '2', '2020-04-28')")
    c.execute("INSERT INTO subscription VALUES ('845', '3', '2020-09-28')")
    c.execute("INSERT INTO subscription VALUES ('846', '0', '2020-03-18')")
    c.execute("INSERT INTO subscription VALUES ('846', '2', '2020-03-25')")
    c.execute("INSERT INTO subscription VALUES ('846', '3', '2020-09-25')")
    c.execute("INSERT INTO subscription VALUES ('847', '0', '2020-01-20')")
    c.execute("INSERT INTO subscription VALUES ('847', '2', '2020-01-27')")
    c.execute("INSERT INTO subscription VALUES ('847', '3', '2020-05-27')")
    c.execute("INSERT INTO subscription VALUES ('848', '0', '2020-12-30')")
    c.execute("INSERT INTO subscription VALUES ('848', '2', '2021-01-06')")
    c.execute("INSERT INTO subscription VALUES ('849', '0', '2020-06-24')")
    c.execute("INSERT INTO subscription VALUES ('849', '1', '2020-07-01')")
    c.execute("INSERT INTO subscription VALUES ('849', '4', '2020-10-11')")
    c.execute("INSERT INTO subscription VALUES ('850', '0', '2020-04-22')")
    c.execute("INSERT INTO subscription VALUES ('850', '1', '2020-04-29')")
    c.execute("INSERT INTO subscription VALUES ('850', '2', '2020-07-03')")
    c.execute("INSERT INTO subscription VALUES ('850', '4', '2020-10-26')")
    c.execute("INSERT INTO subscription VALUES ('851', '0', '2020-07-18')")
    c.execute("INSERT INTO subscription VALUES ('851', '1', '2020-07-25')")
    c.execute("INSERT INTO subscription VALUES ('851', '4', '2020-12-06')")
    c.execute("INSERT INTO subscription VALUES ('852', '0', '2020-03-03')")
    c.execute("INSERT INTO subscription VALUES ('852', '1', '2020-03-10')")
    c.execute("INSERT INTO subscription VALUES ('853', '0', '2020-03-22')")
    c.execute("INSERT INTO subscription VALUES ('853', '2', '2020-03-29')")
    c.execute("INSERT INTO subscription VALUES ('854', '0', '2020-07-15')")
    c.execute("INSERT INTO subscription VALUES ('854', '2', '2020-07-22')")
    c.execute("INSERT INTO subscription VALUES ('854', '3', '2020-09-22')")
    c.execute("INSERT INTO subscription VALUES ('855', '0', '2020-06-17')")
    c.execute("INSERT INTO subscription VALUES ('855', '1', '2020-06-24')")
    c.execute("INSERT INTO subscription VALUES ('856', '0', '2020-05-02')")
    c.execute("INSERT INTO subscription VALUES ('856', '1', '2020-05-09')")
    c.execute("INSERT INTO subscription VALUES ('857', '0', '2020-05-16')")
    c.execute("INSERT INTO subscription VALUES ('857', '1', '2020-05-23')")
    c.execute("INSERT INTO subscription VALUES ('857', '2', '2020-09-01')")
    c.execute("INSERT INTO subscription VALUES ('857', '4', '2020-12-01')")
    c.execute("INSERT INTO subscription VALUES ('858', '0', '2020-03-22')")
    c.execute("INSERT INTO subscription VALUES ('858', '2', '2020-03-29')")
    c.execute("INSERT INTO subscription VALUES ('858', '3', '2020-05-29')")
    c.execute("INSERT INTO subscription VALUES ('859', '0', '2020-11-15')")
    c.execute("INSERT INTO subscription VALUES ('859', '4', '2020-11-22')")
    c.execute("INSERT INTO subscription VALUES ('860', '0', '2020-07-01')")
    c.execute("INSERT INTO subscription VALUES ('860', '2', '2020-07-08')")
    c.execute("INSERT INTO subscription VALUES ('860', '3', '2020-11-08')")
    c.execute("INSERT INTO subscription VALUES ('861', '0', '2020-07-22')")
    c.execute("INSERT INTO subscription VALUES ('861', '1', '2020-07-29')")
    c.execute("INSERT INTO subscription VALUES ('862', '0', '2020-07-18')")
    c.execute("INSERT INTO subscription VALUES ('862', '4', '2020-07-25')")
    c.execute("INSERT INTO subscription VALUES ('863', '0', '2020-02-11')")
    c.execute("INSERT INTO subscription VALUES ('863', '2', '2020-02-18')")
    c.execute("INSERT INTO subscription VALUES ('863', '4', '2020-04-20')")
    c.execute("INSERT INTO subscription VALUES ('864', '0', '2020-04-08')")
    c.execute("INSERT INTO subscription VALUES ('864', '3', '2020-04-15')")
    c.execute("INSERT INTO subscription VALUES ('865', '0', '2020-02-21')")
    c.execute("INSERT INTO subscription VALUES ('865', '1', '2020-02-28')")
    c.execute("INSERT INTO subscription VALUES ('865', '2', '2020-04-03')")
    c.execute("INSERT INTO subscription VALUES ('865', '4', '2020-07-20')")
    c.execute("INSERT INTO subscription VALUES ('866', '0', '2020-07-15')")
    c.execute("INSERT INTO subscription VALUES ('866', '1', '2020-07-22')")
    c.execute("INSERT INTO subscription VALUES ('866', '2', '2020-12-21')")
    c.execute("INSERT INTO subscription VALUES ('866', '4', '2021-03-25')")
    c.execute("INSERT INTO subscription VALUES ('867', '0', '2020-04-02')")
    c.execute("INSERT INTO subscription VALUES ('867', '2', '2020-04-09')")
    c.execute("INSERT INTO subscription VALUES ('868', '0', '2020-03-14')")
    c.execute("INSERT INTO subscription VALUES ('868', '3', '2020-03-21')")
    c.execute("INSERT INTO subscription VALUES ('869', '0', '2020-12-02')")
    c.execute("INSERT INTO subscription VALUES ('869', '1', '2020-12-09')")
    c.execute("INSERT INTO subscription VALUES ('870', '0', '2020-08-11')")
    c.execute("INSERT INTO subscription VALUES ('870', '1', '2020-08-18')")
    c.execute("INSERT INTO subscription VALUES ('870', '3', '2020-08-23')")
    c.execute("INSERT INTO subscription VALUES ('871', '0', '2020-12-18')")
    c.execute("INSERT INTO subscription VALUES ('871', '1', '2020-12-25')")
    c.execute("INSERT INTO subscription VALUES ('871', '2', '2021-03-07')")
    c.execute("INSERT INTO subscription VALUES ('872', '0', '2020-10-18')")
    c.execute("INSERT INTO subscription VALUES ('872', '1', '2020-10-25')")
    c.execute("INSERT INTO subscription VALUES ('872', '4', '2021-03-12')")
    c.execute("INSERT INTO subscription VALUES ('873', '0', '2020-03-24')")
    c.execute("INSERT INTO subscription VALUES ('873', '2', '2020-03-31')")
    c.execute("INSERT INTO subscription VALUES ('873', '3', '2020-06-30')")
    c.execute("INSERT INTO subscription VALUES ('874', '0', '2020-04-08')")
    c.execute("INSERT INTO subscription VALUES ('874', '1', '2020-04-15')")
    c.execute("INSERT INTO subscription VALUES ('875', '0', '2020-03-13')")
    c.execute("INSERT INTO subscription VALUES ('875', '1', '2020-03-20')")
    c.execute("INSERT INTO subscription VALUES ('875', '2', '2020-08-04')")
    c.execute("INSERT INTO subscription VALUES ('875', '3', '2020-12-04')")
    c.execute("INSERT INTO subscription VALUES ('876', '0', '2020-04-09')")
    c.execute("INSERT INTO subscription VALUES ('876', '1', '2020-04-16')")
    c.execute("INSERT INTO subscription VALUES ('876', '2', '2020-07-19')")
    c.execute("INSERT INTO subscription VALUES ('877', '0', '2020-03-23')")
    c.execute("INSERT INTO subscription VALUES ('877', '1', '2020-03-30')")
    c.execute("INSERT INTO subscription VALUES ('878', '0', '2020-07-27')")
    c.execute("INSERT INTO subscription VALUES ('878', '1', '2020-08-03')")
    c.execute("INSERT INTO subscription VALUES ('878', '2', '2020-11-23')")
    c.execute("INSERT INTO subscription VALUES ('879', '0', '2020-09-10')")
    c.execute("INSERT INTO subscription VALUES ('879', '1', '2020-09-17')")
    c.execute("INSERT INTO subscription VALUES ('880', '0', '2020-08-05')")
    c.execute("INSERT INTO subscription VALUES ('880', '1', '2020-08-12')")
    c.execute("INSERT INTO subscription VALUES ('880', '3', '2021-01-10')")
    c.execute("INSERT INTO subscription VALUES ('881', '0', '2020-10-17')")
    c.execute("INSERT INTO subscription VALUES ('881', '2', '2020-10-24')")
    c.execute("INSERT INTO subscription VALUES ('881', '4', '2020-11-25')")
    c.execute("INSERT INTO subscription VALUES ('882', '0', '2020-02-22')")
    c.execute("INSERT INTO subscription VALUES ('882', '1', '2020-02-29')")
    c.execute("INSERT INTO subscription VALUES ('883', '0', '2020-03-05')")
    c.execute("INSERT INTO subscription VALUES ('883', '1', '2020-03-12')")
    c.execute("INSERT INTO subscription VALUES ('883', '2', '2020-07-19')")
    c.execute("INSERT INTO subscription VALUES ('884', '0', '2020-11-01')")
    c.execute("INSERT INTO subscription VALUES ('884', '1', '2020-11-08')")
    c.execute("INSERT INTO subscription VALUES ('884', '2', '2020-11-25')")
    c.execute("INSERT INTO subscription VALUES ('885', '0', '2020-03-08')")
    c.execute("INSERT INTO subscription VALUES ('885', '1', '2020-03-15')")
    c.execute("INSERT INTO subscription VALUES ('885', '2', '2020-06-22')")
    c.execute("INSERT INTO subscription VALUES ('886', '0', '2020-12-09')")
    c.execute("INSERT INTO subscription VALUES ('886', '2', '2020-12-16')")
    c.execute("INSERT INTO subscription VALUES ('887', '0', '2020-05-12')")
    c.execute("INSERT INTO subscription VALUES ('887', '2', '2020-05-19')")
    c.execute("INSERT INTO subscription VALUES ('887', '4', '2020-09-25')")
    c.execute("INSERT INTO subscription VALUES ('888', '0', '2020-02-25')")
    c.execute("INSERT INTO subscription VALUES ('888', '2', '2020-03-03')")
    c.execute("INSERT INTO subscription VALUES ('888', '3', '2020-05-03')")
    c.execute("INSERT INTO subscription VALUES ('889', '0', '2020-08-20')")
    c.execute("INSERT INTO subscription VALUES ('889', '1', '2020-08-27')")
    c.execute("INSERT INTO subscription VALUES ('889', '2', '2020-09-13')")
    c.execute("INSERT INTO subscription VALUES ('889', '4', '2021-03-03')")
    c.execute("INSERT INTO subscription VALUES ('890', '0', '2020-09-22')")
    c.execute("INSERT INTO subscription VALUES ('890', '2', '2020-09-29')")
    c.execute("INSERT INTO subscription VALUES ('891', '0', '2020-05-07')")
    c.execute("INSERT INTO subscription VALUES ('891', '1', '2020-05-14')")
    c.execute("INSERT INTO subscription VALUES ('891', '2', '2020-08-12')")
    c.execute("INSERT INTO subscription VALUES ('891', '4', '2021-02-02')")
    c.execute("INSERT INTO subscription VALUES ('892', '0', '2020-07-20')")
    c.execute("INSERT INTO subscription VALUES ('892', '4', '2020-07-27')")
    c.execute("INSERT INTO subscription VALUES ('893', '0', '2020-05-16')")
    c.execute("INSERT INTO subscription VALUES ('893', '1', '2020-05-23')")
    c.execute("INSERT INTO subscription VALUES ('893', '3', '2020-10-15')")
    c.execute("INSERT INTO subscription VALUES ('894', '0', '2020-11-26')")
    c.execute("INSERT INTO subscription VALUES ('894', '2', '2020-12-03')")
    c.execute("INSERT INTO subscription VALUES ('895', '0', '2020-09-07')")
    c.execute("INSERT INTO subscription VALUES ('895', '1', '2020-09-14')")
    c.execute("INSERT INTO subscription VALUES ('895', '3', '2021-02-15')")
    c.execute("INSERT INTO subscription VALUES ('896', '0', '2020-05-31')")
    c.execute("INSERT INTO subscription VALUES ('896', '1', '2020-06-07')")
    c.execute("INSERT INTO subscription VALUES ('896', '2', '2020-08-16')")
    c.execute("INSERT INTO subscription VALUES ('897', '0', '2020-06-24')")
    c.execute("INSERT INTO subscription VALUES ('897', '1', '2020-07-01')")
    c.execute("INSERT INTO subscription VALUES ('897', '2', '2020-08-12')")
    c.execute("INSERT INTO subscription VALUES ('897', '4', '2020-12-30')")
    c.execute("INSERT INTO subscription VALUES ('898', '0', '2020-05-10')")
    c.execute("INSERT INTO subscription VALUES ('898', '4', '2020-05-17')")
    c.execute("INSERT INTO subscription VALUES ('899', '0', '2020-04-27')")
    c.execute("INSERT INTO subscription VALUES ('899', '1', '2020-05-04')")
    c.execute("INSERT INTO subscription VALUES ('899', '4', '2020-07-14')")
    c.execute("INSERT INTO subscription VALUES ('900', '0', '2020-09-27')")
    c.execute("INSERT INTO subscription VALUES ('900', '2', '2020-10-04')")
    c.execute("INSERT INTO subscription VALUES ('901', '0', '2020-04-21')")
    c.execute("INSERT INTO subscription VALUES ('901', '1', '2020-04-28')")
    c.execute("INSERT INTO subscription VALUES ('901', '2', '2020-05-22')")
    c.execute("INSERT INTO subscription VALUES ('902', '0', '2020-12-29')")
    c.execute("INSERT INTO subscription VALUES ('902', '1', '2021-01-05')")
    c.execute("INSERT INTO subscription VALUES ('903', '0', '2020-05-09')")
    c.execute("INSERT INTO subscription VALUES ('903', '1', '2020-05-16')")
    c.execute("INSERT INTO subscription VALUES ('903', '4', '2020-06-17')")
    c.execute("INSERT INTO subscription VALUES ('904', '0', '2020-06-29')")
    c.execute("INSERT INTO subscription VALUES ('904', '4', '2020-07-06')")
    c.execute("INSERT INTO subscription VALUES ('905', '0', '2020-02-19')")
    c.execute("INSERT INTO subscription VALUES ('905', '2', '2020-02-26')")
    c.execute("INSERT INTO subscription VALUES ('906', '0', '2020-04-14')")
    c.execute("INSERT INTO subscription VALUES ('906', '1', '2020-04-21')")
    c.execute("INSERT INTO subscription VALUES ('906', '2', '2020-04-29')")
    c.execute("INSERT INTO subscription VALUES ('907', '0', '2020-03-24')")
    c.execute("INSERT INTO subscription VALUES ('907', '1', '2020-03-31')")
    c.execute("INSERT INTO subscription VALUES ('907', '2', '2020-06-26')")
    c.execute("INSERT INTO subscription VALUES ('907', '4', '2020-10-20')")
    c.execute("INSERT INTO subscription VALUES ('908', '0', '2020-02-09')")
    c.execute("INSERT INTO subscription VALUES ('908', '2', '2020-02-16')")
    c.execute("INSERT INTO subscription VALUES ('909', '0', '2020-09-09')")
    c.execute("INSERT INTO subscription VALUES ('909', '1', '2020-09-16')")
    c.execute("INSERT INTO subscription VALUES ('909', '3', '2021-01-18')")
    c.execute("INSERT INTO subscription VALUES ('910', '0', '2020-07-23')")
    c.execute("INSERT INTO subscription VALUES ('910', '2', '2020-07-30')")
    c.execute("INSERT INTO subscription VALUES ('911', '0', '2020-05-01')")
    c.execute("INSERT INTO subscription VALUES ('911', '1', '2020-05-08')")
    c.execute("INSERT INTO subscription VALUES ('911', '2', '2020-06-05')")
    c.execute("INSERT INTO subscription VALUES ('912', '0', '2020-12-16')")
    c.execute("INSERT INTO subscription VALUES ('912', '2', '2020-12-23')")
    c.execute("INSERT INTO subscription VALUES ('912', '3', '2021-02-23')")
    c.execute("INSERT INTO subscription VALUES ('913', '0', '2020-12-27')")
    c.execute("INSERT INTO subscription VALUES ('913', '2', '2021-01-03')")
    c.execute("INSERT INTO subscription VALUES ('914', '0', '2020-07-18')")
    c.execute("INSERT INTO subscription VALUES ('914', '1', '2020-07-25')")
    c.execute("INSERT INTO subscription VALUES ('914', '2', '2020-07-30')")
    c.execute("INSERT INTO subscription VALUES ('914', '4', '2020-10-05')")
    c.execute("INSERT INTO subscription VALUES ('915', '0', '2020-09-28')")
    c.execute("INSERT INTO subscription VALUES ('915', '2', '2020-10-05')")
    c.execute("INSERT INTO subscription VALUES ('916', '0', '2020-01-19')")
    c.execute("INSERT INTO subscription VALUES ('916', '2', '2020-01-26')")
    c.execute("INSERT INTO subscription VALUES ('916', '3', '2020-02-26')")
    c.execute("INSERT INTO subscription VALUES ('917', '0', '2020-07-07')")
    c.execute("INSERT INTO subscription VALUES ('917', '1', '2020-07-14')")
    c.execute("INSERT INTO subscription VALUES ('917', '3', '2020-10-10')")
    c.execute("INSERT INTO subscription VALUES ('918', '0', '2020-06-03')")
    c.execute("INSERT INTO subscription VALUES ('918', '1', '2020-06-10')")
    c.execute("INSERT INTO subscription VALUES ('918', '2', '2020-09-01')")
    c.execute("INSERT INTO subscription VALUES ('918', '3', '2020-12-01')")
    c.execute("INSERT INTO subscription VALUES ('919', '0', '2020-09-12')")
    c.execute("INSERT INTO subscription VALUES ('919', '4', '2020-09-19')")
    c.execute("INSERT INTO subscription VALUES ('920', '0', '2020-08-19')")
    c.execute("INSERT INTO subscription VALUES ('920', '2', '2020-08-26')")
    c.execute("INSERT INTO subscription VALUES ('921', '0', '2020-07-26')")
    c.execute("INSERT INTO subscription VALUES ('921', '1', '2020-08-02')")
    c.execute("INSERT INTO subscription VALUES ('921', '2', '2020-11-20')")
    c.execute("INSERT INTO subscription VALUES ('922', '0', '2020-11-02')")
    c.execute("INSERT INTO subscription VALUES ('922', '2', '2020-11-09')")
    c.execute("INSERT INTO subscription VALUES ('922', '3', '2021-02-09')")
    c.execute("INSERT INTO subscription VALUES ('923', '0', '2020-08-28')")
    c.execute("INSERT INTO subscription VALUES ('923', '2', '2020-09-04')")
    c.execute("INSERT INTO subscription VALUES ('923', '4', '2020-11-04')")
    c.execute("INSERT INTO subscription VALUES ('924', '0', '2020-06-19')")
    c.execute("INSERT INTO subscription VALUES ('924', '1', '2020-06-26')")
    c.execute("INSERT INTO subscription VALUES ('924', '2', '2020-12-02')")
    c.execute("INSERT INTO subscription VALUES ('925', '0', '2020-09-21')")
    c.execute("INSERT INTO subscription VALUES ('925', '1', '2020-09-28')")
    c.execute("INSERT INTO subscription VALUES ('925', '2', '2021-02-04')")
    c.execute("INSERT INTO subscription VALUES ('926', '0', '2020-07-12')")
    c.execute("INSERT INTO subscription VALUES ('926', '1', '2020-07-19')")
    c.execute("INSERT INTO subscription VALUES ('926', '2', '2020-10-13')")
    c.execute("INSERT INTO subscription VALUES ('926', '3', '2021-02-13')")
    c.execute("INSERT INTO subscription VALUES ('927', '0', '2020-01-13')")
    c.execute("INSERT INTO subscription VALUES ('927', '2', '2020-01-20')")
    c.execute("INSERT INTO subscription VALUES ('928', '0', '2020-07-08')")
    c.execute("INSERT INTO subscription VALUES ('928', '4', '2020-07-15')")
    c.execute("INSERT INTO subscription VALUES ('929', '0', '2020-04-02')")
    c.execute("INSERT INTO subscription VALUES ('929', '1', '2020-04-09')")
    c.execute("INSERT INTO subscription VALUES ('929', '3', '2020-08-13')")
    c.execute("INSERT INTO subscription VALUES ('930', '0', '2020-02-14')")
    c.execute("INSERT INTO subscription VALUES ('930', '1', '2020-02-21')")
    c.execute("INSERT INTO subscription VALUES ('930', '2', '2020-03-24')")
    c.execute("INSERT INTO subscription VALUES ('931', '0', '2020-01-27')")
    c.execute("INSERT INTO subscription VALUES ('931', '1', '2020-02-03')")
    c.execute("INSERT INTO subscription VALUES ('931', '2', '2020-02-12')")
    c.execute("INSERT INTO subscription VALUES ('931', '3', '2020-04-12')")
    c.execute("INSERT INTO subscription VALUES ('932', '0', '2020-11-01')")
    c.execute("INSERT INTO subscription VALUES ('932', '3', '2020-11-08')")
    c.execute("INSERT INTO subscription VALUES ('933', '0', '2020-05-08')")
    c.execute("INSERT INTO subscription VALUES ('933', '1', '2020-05-15')")
    c.execute("INSERT INTO subscription VALUES ('933', '2', '2020-06-24')")
    c.execute("INSERT INTO subscription VALUES ('934', '0', '2020-01-07')")
    c.execute("INSERT INTO subscription VALUES ('934', '2', '2020-01-14')")
    c.execute("INSERT INTO subscription VALUES ('934', '4', '2020-04-25')")
    c.execute("INSERT INTO subscription VALUES ('935', '0', '2020-01-25')")
    c.execute("INSERT INTO subscription VALUES ('935', '4', '2020-02-01')")
    c.execute("INSERT INTO subscription VALUES ('936', '0', '2020-09-18')")
    c.execute("INSERT INTO subscription VALUES ('936', '2', '2020-09-25')")
    c.execute("INSERT INTO subscription VALUES ('937', '0', '2020-02-22')")
    c.execute("INSERT INTO subscription VALUES ('937', '2', '2020-02-29')")
    c.execute("INSERT INTO subscription VALUES ('937', '3', '2020-08-29')")
    c.execute("INSERT INTO subscription VALUES ('938', '0', '2020-08-01')")
    c.execute("INSERT INTO subscription VALUES ('938', '1', '2020-08-08')")
    c.execute("INSERT INTO subscription VALUES ('938', '3', '2020-11-08')")
    c.execute("INSERT INTO subscription VALUES ('939', '0', '2020-03-20')")
    c.execute("INSERT INTO subscription VALUES ('939', '1', '2020-03-27')")
    c.execute("INSERT INTO subscription VALUES ('939', '2', '2020-08-16')")
    c.execute("INSERT INTO subscription VALUES ('940', '0', '2020-01-17')")
    c.execute("INSERT INTO subscription VALUES ('940', '2', '2020-01-24')")
    c.execute("INSERT INTO subscription VALUES ('940', '4', '2020-03-22')")
    c.execute("INSERT INTO subscription VALUES ('941', '0', '2020-09-15')")
    c.execute("INSERT INTO subscription VALUES ('941', '2', '2020-09-22')")
    c.execute("INSERT INTO subscription VALUES ('942', '0', '2020-12-06')")
    c.execute("INSERT INTO subscription VALUES ('942', '1', '2020-12-13')")
    c.execute("INSERT INTO subscription VALUES ('942', '4', '2021-01-18')")
    c.execute("INSERT INTO subscription VALUES ('943', '0', '2020-11-13')")
    c.execute("INSERT INTO subscription VALUES ('943', '1', '2020-11-20')")
    c.execute("INSERT INTO subscription VALUES ('943', '3', '2021-01-14')")
    c.execute("INSERT INTO subscription VALUES ('944', '0', '2020-09-24')")
    c.execute("INSERT INTO subscription VALUES ('944', '1', '2020-10-01')")
    c.execute("INSERT INTO subscription VALUES ('944', '2', '2021-01-14')")
    c.execute("INSERT INTO subscription VALUES ('945', '0', '2020-01-07')")
    c.execute("INSERT INTO subscription VALUES ('945', '1', '2020-01-14')")
    c.execute("INSERT INTO subscription VALUES ('945', '3', '2020-03-25')")
    c.execute("INSERT INTO subscription VALUES ('946', '0', '2020-07-10')")
    c.execute("INSERT INTO subscription VALUES ('946', '2', '2020-07-17')")
    c.execute("INSERT INTO subscription VALUES ('946', '3', '2020-12-17')")
    c.execute("INSERT INTO subscription VALUES ('947', '0', '2020-07-13')")
    c.execute("INSERT INTO subscription VALUES ('947', '1', '2020-07-20')")
    c.execute("INSERT INTO subscription VALUES ('947', '3', '2020-09-19')")
    c.execute("INSERT INTO subscription VALUES ('948', '0', '2020-03-16')")
    c.execute("INSERT INTO subscription VALUES ('948', '1', '2020-03-23')")
    c.execute("INSERT INTO subscription VALUES ('948', '4', '2020-08-18')")
    c.execute("INSERT INTO subscription VALUES ('949', '0', '2020-10-07')")
    c.execute("INSERT INTO subscription VALUES ('949', '2', '2020-10-14')")
    c.execute("INSERT INTO subscription VALUES ('950', '0', '2020-09-13')")
    c.execute("INSERT INTO subscription VALUES ('950', '2', '2020-09-20')")
    c.execute("INSERT INTO subscription VALUES ('950', '3', '2021-01-20')")
    c.execute("INSERT INTO subscription VALUES ('951', '0', '2020-07-30')")
    c.execute("INSERT INTO subscription VALUES ('951', '2', '2020-08-06')")
    c.execute("INSERT INTO subscription VALUES ('952', '0', '2020-08-22')")
    c.execute("INSERT INTO subscription VALUES ('952', '2', '2020-08-29')")
    c.execute("INSERT INTO subscription VALUES ('953', '0', '2020-09-08')")
    c.execute("INSERT INTO subscription VALUES ('953', '1', '2020-09-15')")
    c.execute("INSERT INTO subscription VALUES ('954', '0', '2020-11-23')")
    c.execute("INSERT INTO subscription VALUES ('954', '4', '2020-11-30')")
    c.execute("INSERT INTO subscription VALUES ('955', '0', '2020-07-28')")
    c.execute("INSERT INTO subscription VALUES ('955', '2', '2020-08-04')")
    c.execute("INSERT INTO subscription VALUES ('956', '0', '2020-02-20')")
    c.execute("INSERT INTO subscription VALUES ('956', '1', '2020-02-27')")
    c.execute("INSERT INTO subscription VALUES ('956', '2', '2020-07-12')")
    c.execute("INSERT INTO subscription VALUES ('956', '3', '2021-01-12')")
    c.execute("INSERT INTO subscription VALUES ('957', '0', '2020-04-28')")
    c.execute("INSERT INTO subscription VALUES ('957', '4', '2020-05-05')")
    c.execute("INSERT INTO subscription VALUES ('958', '0', '2020-07-06')")
    c.execute("INSERT INTO subscription VALUES ('958', '1', '2020-07-13')")
    c.execute("INSERT INTO subscription VALUES ('958', '2', '2020-11-22')")
    c.execute("INSERT INTO subscription VALUES ('958', '3', '2021-01-22')")
    c.execute("INSERT INTO subscription VALUES ('959', '0', '2020-04-22')")
    c.execute("INSERT INTO subscription VALUES ('959', '1', '2020-04-29')")
    c.execute("INSERT INTO subscription VALUES ('960', '0', '2020-10-22')")
    c.execute("INSERT INTO subscription VALUES ('960', '2', '2020-10-29')")
    c.execute("INSERT INTO subscription VALUES ('960', '3', '2021-02-28')")
    c.execute("INSERT INTO subscription VALUES ('961', '0', '2020-09-12')")
    c.execute("INSERT INTO subscription VALUES ('961', '1', '2020-09-19')")
    c.execute("INSERT INTO subscription VALUES ('961', '3', '2020-11-21')")
    c.execute("INSERT INTO subscription VALUES ('962', '0', '2020-06-03')")
    c.execute("INSERT INTO subscription VALUES ('962', '1', '2020-06-10')")
    c.execute("INSERT INTO subscription VALUES ('962', '2', '2020-09-23')")
    c.execute("INSERT INTO subscription VALUES ('962', '4', '2020-11-20')")
    c.execute("INSERT INTO subscription VALUES ('963', '0', '2020-01-04')")
    c.execute("INSERT INTO subscription VALUES ('963', '2', '2020-01-11')")
    c.execute("INSERT INTO subscription VALUES ('964', '0', '2020-10-09')")
    c.execute("INSERT INTO subscription VALUES ('964', '1', '2020-10-16')")
    c.execute("INSERT INTO subscription VALUES ('964', '4', '2021-02-27')")
    c.execute("INSERT INTO subscription VALUES ('965', '0', '2020-06-19')")
    c.execute("INSERT INTO subscription VALUES ('965', '1', '2020-06-26')")
    c.execute("INSERT INTO subscription VALUES ('966', '0', '2020-02-09')")
    c.execute("INSERT INTO subscription VALUES ('966', '1', '2020-02-16')")
    c.execute("INSERT INTO subscription VALUES ('967', '0', '2020-08-21')")
    c.execute("INSERT INTO subscription VALUES ('967', '1', '2020-08-28')")
    c.execute("INSERT INTO subscription VALUES ('967', '2', '2021-01-15')")
    c.execute("INSERT INTO subscription VALUES ('967', '3', '2021-04-15')")
    c.execute("INSERT INTO subscription VALUES ('968', '0', '2020-11-22')")
    c.execute("INSERT INTO subscription VALUES ('968', '2', '2020-11-29')")
    c.execute("INSERT INTO subscription VALUES ('969', '0', '2020-02-21')")
    c.execute("INSERT INTO subscription VALUES ('969', '2', '2020-02-28')")
    c.execute("INSERT INTO subscription VALUES ('969', '3', '2020-06-28')")
    c.execute("INSERT INTO subscription VALUES ('970', '0', '2020-10-05')")
    c.execute("INSERT INTO subscription VALUES ('970', '1', '2020-10-12')")
    c.execute("INSERT INTO subscription VALUES ('971', '0', '2020-01-02')")
    c.execute("INSERT INTO subscription VALUES ('971', '2', '2020-01-09')")
    c.execute("INSERT INTO subscription VALUES ('972', '0', '2020-02-05')")
    c.execute("INSERT INTO subscription VALUES ('972', '3', '2020-02-12')")
    c.execute("INSERT INTO subscription VALUES ('973', '0', '2020-01-08')")
    c.execute("INSERT INTO subscription VALUES ('973', '4', '2020-01-15')")
    c.execute("INSERT INTO subscription VALUES ('974', '0', '2020-09-10')")
    c.execute("INSERT INTO subscription VALUES ('974', '1', '2020-09-17')")
    c.execute("INSERT INTO subscription VALUES ('974', '3', '2020-10-16')")
    c.execute("INSERT INTO subscription VALUES ('975', '0', '2020-11-15')")
    c.execute("INSERT INTO subscription VALUES ('975', '1', '2020-11-22')")
    c.execute("INSERT INTO subscription VALUES ('975', '3', '2021-04-30')")
    c.execute("INSERT INTO subscription VALUES ('976', '0', '2020-11-11')")
    c.execute("INSERT INTO subscription VALUES ('976', '1', '2020-11-18')")
    c.execute("INSERT INTO subscription VALUES ('976', '3', '2021-02-13')")
    c.execute("INSERT INTO subscription VALUES ('977', '0', '2020-08-04')")
    c.execute("INSERT INTO subscription VALUES ('977', '1', '2020-08-11')")
    c.execute("INSERT INTO subscription VALUES ('977', '4', '2020-11-03')")
    c.execute("INSERT INTO subscription VALUES ('978', '0', '2020-08-27')")
    c.execute("INSERT INTO subscription VALUES ('978', '2', '2020-09-03')")
    c.execute("INSERT INTO subscription VALUES ('978', '3', '2020-11-03')")
    c.execute("INSERT INTO subscription VALUES ('979', '0', '2020-12-28')")
    c.execute("INSERT INTO subscription VALUES ('979', '1', '2021-01-04')")
    c.execute("INSERT INTO subscription VALUES ('980', '0', '2020-06-12')")
    c.execute("INSERT INTO subscription VALUES ('980', '2', '2020-06-19')")
    c.execute("INSERT INTO subscription VALUES ('981', '0', '2020-02-16')")
    c.execute("INSERT INTO subscription VALUES ('981', '2', '2020-02-23')")
    c.execute("INSERT INTO subscription VALUES ('982', '0', '2020-06-13')")
    c.execute("INSERT INTO subscription VALUES ('982', '1', '2020-06-20')")
    c.execute("INSERT INTO subscription VALUES ('982', '2', '2020-10-14')")
    c.execute("INSERT INTO subscription VALUES ('983', '0', '2020-12-12')")
    c.execute("INSERT INTO subscription VALUES ('983', '1', '2020-12-19')")
    c.execute("INSERT INTO subscription VALUES ('984', '0', '2020-06-30')")
    c.execute("INSERT INTO subscription VALUES ('984', '1', '2020-07-07')")
    c.execute("INSERT INTO subscription VALUES ('984', '4', '2020-09-30')")
    c.execute("INSERT INTO subscription VALUES ('985', '0', '2020-08-02')")
    c.execute("INSERT INTO subscription VALUES ('985', '4', '2020-08-09')")
    c.execute("INSERT INTO subscription VALUES ('986', '0', '2020-11-16')")
    c.execute("INSERT INTO subscription VALUES ('986', '1', '2020-11-23')")
    c.execute("INSERT INTO subscription VALUES ('986', '4', '2021-04-13')")
    c.execute("INSERT INTO subscription VALUES ('987', '0', '2020-01-05')")
    c.execute("INSERT INTO subscription VALUES ('987', '4', '2020-01-12')")
    c.execute("INSERT INTO subscription VALUES ('988', '0', '2020-05-02')")
    c.execute("INSERT INTO subscription VALUES ('988', '4', '2020-05-09')")
    c.execute("INSERT INTO subscription VALUES ('989', '0', '2020-09-03')")
    c.execute("INSERT INTO subscription VALUES ('989', '2', '2020-09-10')")
    c.execute("INSERT INTO subscription VALUES ('989', '3', '2021-01-10')")
    c.execute("INSERT INTO subscription VALUES ('990', '0', '2020-07-23')")
    c.execute("INSERT INTO subscription VALUES ('990', '1', '2020-07-30')")
    c.execute("INSERT INTO subscription VALUES ('991', '0', '2020-10-18')")
    c.execute("INSERT INTO subscription VALUES ('991', '2', '2020-10-25')")
    c.execute("INSERT INTO subscription VALUES ('992', '0', '2020-10-17')")
    c.execute("INSERT INTO subscription VALUES ('992', '2', '2020-10-24')")
    c.execute("INSERT INTO subscription VALUES ('993', '0', '2020-10-31')")
    c.execute("INSERT INTO subscription VALUES ('993', '4', '2020-11-07')")
    c.execute("INSERT INTO subscription VALUES ('994', '0', '2020-07-25')")
    c.execute("INSERT INTO subscription VALUES ('994', '1', '2020-08-01')")
    c.execute("INSERT INTO subscription VALUES ('994', '2', '2020-08-27')")
    c.execute("INSERT INTO subscription VALUES ('995', '0', '2020-06-11')")
    c.execute("INSERT INTO subscription VALUES ('995', '1', '2020-06-18')")
    c.execute("INSERT INTO subscription VALUES ('995', '2', '2020-12-06')")
    c.execute("INSERT INTO subscription VALUES ('996', '0', '2020-11-11')")
    c.execute("INSERT INTO subscription VALUES ('996', '1', '2020-11-18')")
    c.execute("INSERT INTO subscription VALUES ('996', '4', '2020-12-07')")
    c.execute("INSERT INTO subscription VALUES ('997', '0', '2020-07-27')")
    c.execute("INSERT INTO subscription VALUES ('997', '1', '2020-08-03')")
    c.execute("INSERT INTO subscription VALUES ('997', '2', '2020-08-26')")
    c.execute("INSERT INTO subscription VALUES ('997', '4', '2020-11-14')")
    c.execute("INSERT INTO subscription VALUES ('998', '0', '2020-10-12')")
    c.execute("INSERT INTO subscription VALUES ('998', '2', '2020-10-19')")
    c.execute("INSERT INTO subscription VALUES ('999', '0', '2020-10-23')")
    c.execute("INSERT INTO subscription VALUES ('999', '2', '2020-10-30')")
    c.execute("INSERT INTO subscription VALUES ('999', '4', '2020-12-01')")
    c.execute("INSERT INTO subscription VALUES ('1000', '0', '2020-03-19')")
    c.execute("INSERT INTO subscription VALUES ('1000', '2', '2020-03-26')")
    c.execute("INSERT INTO subscription VALUES ('1000', '4', '2020-06-04')")
            
        
    
    conn.commit()
    conn.close()
    
create_table()
data_entry()

#### Loading Database

In [3]:
%%capture
%load_ext sql
%sql sqlite:///foodie-fi.db

#### Checking created tables

In [4]:
%%sql
select 
* 
from plans;

 * sqlite:///foodie-fi.db
Done.

[(0, 'trial', 0.0),
 (1, 'basic monthly', 9.9),
 (2, 'pro monthly', 19.9),
 (3, 'pro annual', 199.0),
 (4, 'churn', None)]

In [5]:
%%sql
select 
* 
from subscription;

 * sqlite:///foodie-fi.db
Done.

[(1, 0, '2020-08-01'),
 (1, 1, '2020-08-08'),
 (2, 0, '2020-09-20'),
 (2, 3, '2020-09-27'),
 (3, 0, '2020-01-13'),
 (3, 1, '2020-01-20'),
 (4, 0, '2020-01-17'),
 (4, 1, '2020-01-24'),
 (4, 4, '2020-04-21'),
 (5, 0, '2020-08-03'),
 (5, 1, '2020-08-10'),
 (6, 0, '2020-12-23'),
 (6, 1, '2020-12-30'),
 (6, 4, '2021-02-26'),
 (7, 0, '2020-02-05'),
 (7, 1, '2020-02-12'),
 (7, 2, '2020-05-22'),
 (8, 0, '2020-06-11'),
 (8, 1, '2020-06-18'),
 (8, 2, '2020-08-03'),
 (9, 0, '2020-12-07'),
 (9, 3, '2020-12-14'),
 (10, 0, '2020-09-19'),
 (10, 2, '2020-09-26'),
 (11, 0, '2020-11-19'),
 (11, 4, '2020-11-26'),
 (12, 0, '2020-09-22'),
 (12, 1, '2020-09-29'),
 (13, 0, '2020-12-15'),
 (13, 1, '2020-12-22'),
 (13, 2, '2021-03-29'),
 (14, 0, '2020-09-22'),
 (14, 1, '2020-09-29'),
 (15, 0, '2020-03-17'),
 (15, 2, '2020-03-24'),
 (15, 4, '2020-04-29'),
 (16, 0, '2020-05-31'),
 (16, 1, '2020-06-07'),
 (16, 3, '2020-10-21'),
 (17, 0, '2020-07-27'),
 (17, 1, '2020-08-03'),
 (17, 3, '2020-12-11'),
 (18, 0, '2020-07-06'),
 (18, 2, '2020-07-13'),
 (19, 0, '2020-06-22'),
 (19, 2, '2020-06-29'),
 (19, 3, '2020-08-29'),
 (20, 0, '2020-04-08'),
 (20, 1, '2020-04-15'),
 (20, 3, '2020-06-05'),
 (21, 0, '2020-02-04'),
 (21, 1, '2020-02-11'),
 (21, 2, '2020-06-03'),
 (21, 4, '2020-09-27'),
 (22, 0, '2020-01-10'),
 (22, 2, '2020-01-17'),
 (23, 0, '2020-05-13'),
 (23, 3, '2020-05-20'),
 (24, 0, '2020-11-10'),
 (24, 2, '2020-11-17'),
 (24, 3, '2021-04-17'),
 (25, 0, '2020-05-10'),
 (25, 1, '2020-05-17'),
 (25, 2, '2020-06-16'),
 (26, 0, '2020-12-08'),
 (26, 2, '2020-12-15'),
 (27, 0, '2020-08-24'),
 (27, 2, '2020-08-31'),
 (28, 0, '2020-06-30'),
 (28, 3, '2020-07-07'),
 (29, 0, '2020-01-23'),
 (29, 2, '2020-01-30'),
 (30, 0, '2020-04-29'),
 (30, 1, '2020-05-06'),
 (31, 0, '2020-06-22'),
 (31, 2, '2020-06-29'),
 (31, 3, '2020-11-29'),
 (32, 0, '2020-06-12'),
 (32, 1, '2020-06-19'),
 (32, 2, '2020-07-18'),
 (33, 0, '2020-09-03'),
 (33, 2, '2020-09-10'),
 (33, 4, '2021-02-05'),
 (34, 0, '2020-12-20'),
 (34, 1, '2020-12-27'),
 (34, 2, '2021-03-26'),
 (35, 0, '2020-09-03'),
 (35, 2, '2020-09-10'),
 (36, 0, '2020-02-25'),
 (36, 2, '2020-03-03'),
 (37, 0, '2020-08-05'),
 (37, 1, '2020-08-12'),
 (37, 2, '2020-11-11'),
 (38, 0, '2020-10-02'),
 (38, 2, '2020-10-09'),
 (38, 3, '2020-11-09'),
 (39, 0, '2020-05-28'),
 (39, 1, '2020-06-04'),
 (39, 2, '2020-08-25'),
 (39, 4, '2020-09-10'),
 (40, 0, '2020-01-22'),
 (40, 1, '2020-01-29'),
 (40, 2, '2020-03-25'),
 (41, 0, '2020-05-16'),
 (41, 2, '2020-05-23'),
 (42, 0, '2020-10-27'),
 (42, 1, '2020-11-03'),
 (42, 2, '2021-04-28'),
 (43, 0, '2020-08-13'),
 (43, 1, '2020-08-20'),
 (43, 2, '2020-12-18'),
 (44, 0, '2020-03-17'),
 (44, 3, '2020-03-24'),
 (45, 0, '2020-02-11'),
 (45, 1, '2020-02-18'),
 (45, 2, '2020-08-12'),
 (46, 0, '2020-04-19'),
 (46, 1, '2020-04-26'),
 (46, 2, '2020-07-06'),
 (46, 3, '2020-08-06'),
 (47, 0, '2020-06-06'),
 (47, 1, '2020-06-13'),
 (47, 3, '2020-10-26'),
 (48, 0, '2020-01-11'),
 (48, 1, '2020-01-18'),
 (48, 4, '2020-06-01'),
 (49, 0, '2020-04-24'),
 (49, 2, '2020-05-01'),
 (49, 3, '2020-08-01'),
 (50, 0, '2020-07-21'),
 (50, 2, '2020-07-28'),
 (51, 0, '2020-01-19'),
 (51, 1, '2020-01-26'),
 (51, 3, '2020-03-09'),
 (51, 4, '2021-03-09'),
 (52, 0, '2020-05-31'),
 (52, 1, '2020-06-07'),
 (52, 4, '2020-07-05'),
 (53, 0, '2020-01-18'),
 (53, 1, '2020-01-25'),
 (54, 0, '2020-05-23'),
 (54, 2, '2020-05-30'),
 (55, 0, '2020-10-22'),
 (55, 1, '2020-10-29'),
 (55, 3, '2021-03-01'),
 (56, 0, '2020-01-03'),
 (56, 3, '2020-01-10'),
 (57, 0, '2020-03-03'),
 (57, 2, '2020-03-10'),
 (58, 0, '2020-07-04'),
 (58, 1, '2020-07-11'),
 (58, 3, '2020-09-24'),
 (59, 0, '2020-10-30'),
 (59, 1, '2020-11-06'),
 (59, 4, '2021-04-29'),
 (60, 0, '2020-06-17'),
 (60, 1, '2020-06-24'),
 (61, 0, '2020-08-31'),
 (61, 1, '2020-09-07'),
 (61, 3, '2021-02-13'),
 (62, 0, '2020-10-12'),
 (62, 1, '2020-10-19'),
 (62, 2, '2021-01-02'),
 (62, 4, '2021-02-23'),
 (63, 0, '2020-05-28'),
 (63, 1, '2020-06-04'),
 (63, 4, '2020-06-18'),
 (64, 0, '2020-03-08'),
 (64, 1, '2020-03-15'),
 (64, 2, '2020-04-03'),
 (64, 4, '2020-04-27'),
 (65, 0, '2020-05-12'),
 (65, 1, '2020-05-19'),
 (65, 2, '2020-10-09'),
 (66, 0, '2020-07-30'),
 (66, 1, '2020-08-06'),
 (66, 3, '2020-10-04'),
 (67, 0, '2020-08-14'),
 (67, 2, '2020-08-21'),
 (68, 0, '2020-04-10'),
 (68, 3, '2020-04-17'),
 (69, 0, '2020-03-07'),
 (69, 1, '2020-03-14'),
 (69, 2, '2020-04-14'),
 (70, 0, '2020-07-06'),
 (70, 1, '2020-07-13'),
 (70, 2, '2021-01-06'),
 (71, 0, '2020-07-23'),
 (71, 2, '2020-07-30'),
 (71, 4, '2020-12-08'),
 (72, 0, '2020-12-10'),
 (72, 2, '2020-12-17'),
 (72, 4, '2021-02-01'),
 (73, 0, '2020-03-24'),
 (73, 1, '2020-03-31'),
 (73, 2, '2020-05-13'),
 (73, 3, '2020-10-13'),
 (74, 0, '2020-05-24'),
 (74, 1, '2020-05-31'),
 (74, 3, '2020-10-01'),
 (75, 0, '2020-07-14'),
 (75, 1, '2020-07-21'),
 (75, 2, '2020-11-19'),
 (76, 0, '2020-08-31'),
 (76, 3, '2020-09-07'),
 (77, 0, '2020-04-18'),
 (77, 2, '2020-04-25'),
 (77, 3, '2020-10-25'),
 (78, 0, '2020-09-03'),
 (78, 2, '2020-09-10'),
 (78, 4, '2021-02-19'),
 (79, 0, '2020-07-30'),
 (79, 2, '2020-08-06'),
 (80, 0, '2020-09-23'),
 (80, 2, '2020-09-30'),
 (80, 4, '2021-01-17'),
 (81, 0, '2020-05-29'),
 (81, 2, '2020-06-05'),
 (81, 4, '2020-10-20'),
 (82, 0, '2020-05-02'),
 (82, 1, '2020-05-09'),
 (83, 0, '2020-05-18'),
 (83, 1, '2020-05-25'),
 (83, 2, '2020-10-29'),
 (83, 3, '2021-04-29'),
 (84, 0, '2020-06-14'),
 (84, 1, '2020-06-21'),
 (84, 4, '2020-07-07'),
 (85, 0, '2020-08-13'),
 (85, 1, '2020-08-20'),
 (86, 0, '2020-07-10'),
 (86, 3, '2020-07-17'),
 (87, 0, '2020-08-08'),
 (87, 2, '2020-08-15'),
 (87, 3, '2020-09-15'),
 (88, 0, '2020-12-30'),
 (88, 2, '2021-01-06'),
 (89, 0, '2020-03-05'),
 (89, 2, '2020-03-12'),
 (89, 4, '2020-09-02'),
 (90, 0, '2020-11-25'),
 (90, 1, '2020-12-02'),
 (90, 2, '2021-03-28'),
 (90, 3, '2021-04-28'),
 (91, 0, '2020-09-08'),
 (91, 2, '2020-09-15'),
 (91, 4, '2021-03-04'),
 (92, 0, '2020-11-02'),
 (92, 1, '2020-11-09'),
 (93, 0, '2020-03-14'),
 (93, 2, '2020-03-21'),
 (93, 4, '2020-08-30'),
 (94, 0, '2020-12-09'),
 (94, 2, '2020-12-16'),
 (95, 0, '2020-11-02'),
 (95, 1, '2020-11-09'),
 (95, 2, '2021-03-16'),
 (96, 0, '2020-08-22'),
 (96, 1, '2020-08-29'),
 (96, 3, '2021-01-23'),
 (97, 0, '2020-10-29'),
 (97, 1, '2020-11-05'),
 (98, 0, '2020-01-05'),
 (98, 1, '2020-01-12'),
 (98, 2, '2020-01-22'),
 (98, 4, '2020-04-05'),
 (99, 0, '2020-12-05'),
 (99, 4, '2020-12-12'),
 (100, 0, '2020-06-02'),
 (100, 1, '2020-06-09'),
 (100, 2, '2020-09-11'),
 (101, 0, '2020-06-08'),
 (101, 1, '2020-06-15'),
 (101, 3, '2020-07-20'),
 (102, 0, '2020-06-02'),
 (102, 1, '2020-06-09'),
 (102, 2, '2020-06-18'),
 (102, 4, '2020-12-01'),
 (103, 0, '2020-07-24'),
 (103, 2, '2020-07-31'),
 (103, 4, '2020-10-28'),
 (104, 0, '2020-03-29'),
 (104, 2, '2020-04-05'),
 (105, 0, '2020-09-20'),
 (105, 1, '2020-09-27'),
 (105, 3, '2020-10-22'),
 (106, 0, '2020-08-02'),
 (106, 3, '2020-08-09'),
 (107, 0, '2020-01-12'),
 (107, 1, '2020-01-19'),
 (107, 2, '2020-03-23'),
 (108, 0, '2020-09-10'),
 (108, 4, '2020-09-17'),
 (109, 0, '2020-10-12'),
 (109, 1, '2020-10-19'),
 (109, 2, '2021-03-20'),
 (110, 0, '2020-05-12'),
 (110, 2, '2020-05-19'),
 (111, 0, '2020-08-25'),
 (111, 3, '2020-09-01'),
 (112, 0, '2020-10-20'),
 (112, 2, '2020-10-27'),
 (112, 4, '2021-01-08'),
 (113, 0, '2020-04-10'),
 (113, 1, '2020-04-17'),
 (113, 2, '2020-09-13'),
 (113, 4, '2020-11-01'),
 (114, 0, '2020-06-05'),
 (114, 1, '2020-06-12'),
 (114, 3, '2020-09-13'),
 (115, 0, '2020-08-14'),
 (115, 3, '2020-08-21'),
 (116, 0, '2020-05-23'),
 (116, 1, '2020-05-30'),
 (116, 4, '2020-09-15'),
 (117, 0, '2020-05-22'),
 (117, 1, '2020-05-29'),
 (117, 3, '2020-11-14'),
 (118, 0, '2020-01-24'),
 (118, 1, '2020-01-31'),
 (118, 4, '2020-06-30'),
 (119, 0, '2020-11-09'),
 (119, 1, '2020-11-16'),
 (119, 3, '2021-02-27'),
 (120, 0, '2020-05-14'),
 (120, 2, '2020-05-21'),
 (120, 3, '2020-09-21'),
 (121, 0, '2020-06-18'),
 (121, 1, '2020-06-25'),
 (121, 3, '2020-10-07'),
 (122, 0, '2020-03-30'),
 (122, 4, '2020-04-06'),
 (123, 0, '2020-03-12'),
 (123, 1, '2020-03-19'),
 (123, 4, '2020-05-15'),
 (124, 0, '2020-03-17'),
 (124, 1, '2020-03-24'),
 (124, 3, '2020-06-20'),
 (125, 0, '2020-08-07'),
 (125, 1, '2020-08-14'),
 (125, 4, '2020-12-03'),
 (126, 0, '2020-09-15'),
 (126, 1, '2020-09-22'),
 (127, 0, '2020-05-23'),
 (127, 2, '2020-05-30'),
 (127, 4, '2020-08-11'),
 (128, 0, '2020-01-19'),
 (128, 4, '2020-01-26'),
 (129, 0, '2020-07-23'),
 (129, 1, '2020-07-30'),
 (130, 0, '2020-09-22'),
 (130, 2, '2020-09-29'),
 (131, 0, '2020-10-16'),
 (131, 3, '2020-10-23'),
 (132, 0, '2020-10-18'),
 (132, 1, '2020-10-25'),
 (132, 4, '2021-01-07'),
 (133, 0, '2020-03-29'),
 (133, 1, '2020-04-05'),
 (133, 3, '2020-07-11'),
 (134, 0, '2020-07-02'),
 (134, 2, '2020-07-09'),
 (135, 0, '2020-12-23'),
 (135, 4, '2020-12-30'),
 (136, 0, '2020-08-16'),
 (136, 4, '2020-08-23'),
 (137, 0, '2020-08-12'),
 (137, 2, '2020-08-19'),
 (138, 0, '2020-10-26'),
 (138, 1, '2020-11-02'),
 (138, 2, '2020-12-25'),
 (138, 3, '2021-01-25'),
 (139, 0, '2020-07-17'),
 (139, 2, '2020-07-24'),
 (140, 0, '2020-12-25'),
 (140, 1, '2021-01-01'),
 (141, 0, '2020-04-19'),
 (141, 1, '2020-04-26'),
 (141, 3, '2020-10-18'),
 (142, 0, '2020-05-30'),
 (142, 2, '2020-06-06'),
 (143, 0, '2020-12-20'),
 (143, 1, '2020-12-27'),
 (143, 4, '2021-03-03'),
 (144, 0, '2020-09-04'),
 (144, 1, '2020-09-11'),
 (144, 2, '2021-02-09'),
 (145, 0, '2020-01-17'),
 (145, 2, '2020-01-24'),
 (146, 0, '2020-07-05'),
 (146, 1, '2020-07-12'),
 (146, 2, '2020-10-28'),
 (146, 4, '2020-12-18'),
 (147, 0, '2020-12-18'),
 (147, 2, '2020-12-25'),
 (148, 0, '2020-03-12'),
 (148, 2, '2020-03-19'),
 (149, 0, '2020-12-19'),
 (149, 1, '2020-12-26'),
 (150, 0, '2020-02-05'),
 (150, 2, '2020-02-12'),
 (151, 0, '2020-09-07'),
 (151, 1, '2020-09-14'),
 (151, 2, '2020-09-17'),
 (152, 0, '2020-10-14'),
 (152, 1, '2020-10-21'),
 (152, 2, '2021-03-08'),
 (153, 0, '2020-11-28'),
 (153, 2, '2020-12-05'),
 (154, 0, '2020-03-18'),
 (154, 1, '2020-03-25'),
 (154, 2, '2020-05-01'),
 (155, 0, '2020-09-13'),
 (155, 4, '2020-09-20'),
 (156, 0, '2020-01-19'),
 (156, 4, '2020-01-26'),
 (157, 0, '2020-04-23'),
 (157, 1, '2020-04-30'),
 (157, 3, '2020-05-11'),
 (158, 0, '2020-03-02'),
 (158, 1, '2020-03-09'),
 (158, 2, '2020-05-09'),
 (159, 0, '2020-09-09'),
 (159, 2, '2020-09-16'),
 (160, 0, '2020-11-16'),
 (160, 1, '2020-11-23'),
 (161, 0, '2020-12-17'),
 (161, 4, '2020-12-24'),
 (162, 0, '2020-02-23'),
 (162, 4, '2020-03-01'),
 (163, 0, '2020-12-23'),
 (163, 2, '2020-12-30'),
 (164, 0, '2020-11-27'),
 (164, 2, '2020-12-04'),
 (164, 4, '2020-12-24'),
 (165, 0, '2020-10-05'),
 (165, 1, '2020-10-12'),
 (165, 3, '2020-11-08'),
 (166, 0, '2020-07-03'),
 (166, 1, '2020-07-10'),
 (166, 4, '2020-09-22'),
 (167, 0, '2020-05-07'),
 (167, 2, '2020-05-14'),
 (168, 0, '2020-03-07'),
 (168, 2, '2020-03-14'),
 (169, 0, '2020-04-07'),
 (169, 4, '2020-04-14'),
 (170, 0, '2020-04-18'),
 (170, 1, '2020-04-25'),
 (170, 2, '2020-08-28'),
 (170, 3, '2020-12-28'),
 (171, 0, '2020-11-28'),
 (171, 2, '2020-12-05'),
 (172, 0, '2020-12-05'),
 (172, 1, '2020-12-12'),
 (172, 4, '2021-02-15'),
 (173, 0, '2020-06-24'),
 (173, 2, '2020-07-01'),
 (174, 0, '2020-02-01'),
 (174, 1, '2020-02-08'),
 (174, 3, '2020-07-10'),
 (175, 0, '2020-08-15'),
 (175, 2, '2020-08-22'),
 (175, 4, '2020-11-23'),
 (176, 0, '2020-09-13'),
 (176, 1, '2020-09-20'),
 (177, 0, '2020-05-01'),
 (177, 2, '2020-05-08'),
 (177, 4, '2020-09-09'),
 (178, 0, '2020-02-22'),
 (178, 4, '2020-02-29'),
 (179, 0, '2020-06-13'),
 (179, 2, '2020-06-20'),
 (179, 4, '2020-09-25'),
 (180, 0, '2020-10-31'),
 (180, 1, '2020-11-07'),
 (180, 2, '2021-01-17'),
 (181, 0, '2020-02-11'),
 (181, 2, '2020-02-18'),
 (182, 0, '2020-09-26'),
 (182, 1, '2020-10-03'),
 (182, 4, '2021-02-25'),
 (183, 0, '2020-09-25'),
 (183, 2, '2020-10-02'),
 (184, 0, '2020-02-16'),
 (184, 1, '2020-02-23'),
 (185, 0, '2020-12-03'),
 (185, 2, '2020-12-10'),
 (186, 0, '2020-09-30'),
 (186, 2, '2020-10-07'),
 (186, 4, '2021-02-05'),
 (187, 0, '2020-09-19'),
 (187, 3, '2020-09-26'),
 (188, 0, '2020-02-22'),
 (188, 1, '2020-02-29'),
 (189, 0, '2020-12-09'),
 (189, 2, '2020-12-16'),
 (190, 0, '2020-04-20'),
 (190, 1, '2020-04-27'),
 (190, 3, '2020-09-04'),
 (191, 0, '2020-01-02'),
 (191, 2, '2020-01-09'),
 (192, 0, '2020-07-29'),
 (192, 1, '2020-08-05'),
 (193, 0, '2020-05-19'),
 (193, 1, '2020-05-26'),
 (193, 2, '2020-09-21'),
 (193, 3, '2020-10-21'),
 (194, 0, '2020-11-20'),
 (194, 2, '2020-11-27'),
 (194, 4, '2021-01-13'),
 (195, 0, '2020-02-08'),
 (195, 2, '2020-02-15'),
 (195, 3, '2020-06-15'),
 (196, 0, '2020-03-09'),
 (196, 2, '2020-03-16'),
 (197, 0, '2020-05-17'),
 (197, 2, '2020-05-24'),
 (197, 4, '2020-07-01'),
 (198, 0, '2020-11-11'),
 (198, 1, '2020-11-18'),
 (198, 4, '2021-03-16'),
 (199, 0, '2020-12-09'),
 (199, 2, '2020-12-16'),
 (200, 0, '2020-04-05'),
 (200, 2, '2020-04-12'),
 (201, 0, '2020-03-07'),
 (201, 1, '2020-03-14'),
 (202, 0, '2020-07-01'),
 (202, 2, '2020-07-08'),
 (203, 0, '2020-08-24'),
 (203, 1, '2020-08-31'),
 (203, 3, '2020-09-19'),
 (204, 0, '2020-06-10'),
 (204, 1, '2020-06-17'),
 (204, 4, '2020-10-05'),
 (205, 0, '2020-11-02'),
 (205, 1, '2020-11-09'),
 (205, 3, '2021-03-13'),
 (206, 0, '2020-03-17'),
 (206, 1, '2020-03-24'),
 (206, 3, '2020-09-02'),
 (207, 0, '2020-05-20'),
 (207, 1, '2020-05-27'),
 (208, 0, '2020-06-12'),
 (208, 2, '2020-06-19'),
 (208, 3, '2020-09-19'),
 (209, 0, '2020-08-13'),
 (209, 2, '2020-08-20'),
 (210, 0, '2020-02-09'),
 (210, 2, '2020-02-16'),
 (210, 4, '2020-06-21'),
 (211, 0, '2020-10-10'),
 (211, 1, '2020-10-17'),
 (211, 3, '2020-10-18'),
 (212, 0, '2020-03-02'),
 (212, 1, '2020-03-09'),
 (213, 0, '2020-08-07'),
 (213, 3, '2020-08-14'),
 (214, 0, '2020-02-03'),
 (214, 1, '2020-02-10'),
 (214, 2, '2020-05-07'),
 (214, 4, '2020-08-21'),
 (215, 0, '2020-04-16'),
 (215, 2, '2020-04-23'),
 (215, 3, '2020-07-23'),
 (216, 0, '2020-08-26'),
 (216, 2, '2020-09-02'),
 (217, 0, '2020-12-06'),
 (217, 2, '2020-12-13'),
 (218, 0, '2020-12-02'),
 (218, 1, '2020-12-09'),
 (218, 4, '2021-04-24'),
 (219, 0, '2020-10-22'),
 (219, 2, '2020-10-29'),
 (219, 3, '2021-04-29'),
 (220, 0, '2020-06-08'),
 (220, 4, '2020-06-15'),
 (221, 0, '2020-09-27'),
 (221, 1, '2020-10-04'),
 (221, 3, '2021-03-29'),
 (222, 0, '2020-08-29'),
 (222, 1, '2020-09-05'),
 (222, 4, '2020-12-25'),
 (223, 0, '2020-08-01'),
 (223, 1, '2020-08-08'),
 (223, 3, '2021-01-31'),
 (224, 0, '2020-01-26'),
 (224, 2, '2020-02-02'),
 (224, 3, '2020-05-02'),
 (225, 0, '2020-12-27'),
 (225, 4, '2021-01-03'),
 (226, 0, '2020-11-01'),
 (226, 1, '2020-11-08'),
 (226, 2, '2020-11-24'),
 (227, 0, '2020-03-02'),
 (227, 2, '2020-03-09'),
 (227, 3, '2020-08-09'),
 (228, 0, '2020-10-02'),
 (228, 2, '2020-10-09'),
 (228, 3, '2021-02-09'),
 (229, 0, '2020-07-24'),
 (229, 1, '2020-07-31'),
 (229, 4, '2021-01-24'),
 (230, 0, '2020-04-08'),
 (230, 4, '2020-04-15'),
 (231, 0, '2020-05-13'),
 (231, 1, '2020-05-20'),
 (231, 2, '2020-07-09'),
 (232, 0, '2020-08-26'),
 (232, 1, '2020-09-02'),
 (232, 2, '2021-02-03'),
 (233, 0, '2020-07-31'),
 (233, 1, '2020-08-07'),
 (233, 3, '2020-10-29'),
 (234, 0, '2020-01-19'),
 (234, 2, '2020-01-26'),
 (235, 0, '2020-08-20'),
 (235, 1, '2020-08-27'),
 (235, 2, '2020-10-17'),
 (236, 0, '2020-06-22'),
 (236, 1, '2020-06-29'),
 (237, 0, '2020-11-07'),
 (237, 1, '2020-11-14'),
 (237, 2, '2021-03-24'),
 (238, 0, '2020-10-27'),
 (238, 1, '2020-11-03'),
 (238, 3, '2020-12-23'),
 (239, 0, '2020-08-15'),
 (239, 1, '2020-08-22'),
 (239, 4, '2020-10-20'),
 (240, 0, '2020-01-14'),
 (240, 1, '2020-01-21'),
 (240, 3, '2020-03-03'),
 (240, 4, '2021-03-03'),
 (241, 0, '2020-10-03'),
 (241, 1, '2020-10-10'),
 (241, 3, '2020-11-11'),
 (242, 0, '2020-10-19'),
 (242, 2, '2020-10-26'),
 (243, 0, '2020-09-04'),
 (243, 1, '2020-09-11'),
 (244, 0, '2020-03-04'),
 (244, 2, '2020-03-11'),
 (245, 0, '2020-03-28'),
 (245, 4, '2020-04-04'),
 (246, 0, '2020-01-27'),
 (246, 1, '2020-02-03'),
 (247, 0, '2020-07-07'),
 (247, 1, '2020-07-14'),
 (247, 2, '2020-08-20'),
 (248, 0, '2020-11-09'),
 (248, 1, '2020-11-16'),
 (249, 0, '2020-02-18'),
 (249, 2, '2020-02-25'),
 (250, 0, '2020-06-15'),
 (250, 2, '2020-06-22'),
 (250, 3, '2020-09-22'),
 (251, 0, '2020-03-09'),
 (251, 4, '2020-03-16'),
 (252, 0, '2020-11-08'),
 (252, 1, '2020-11-15'),
 (252, 2, '2020-12-23'),
 (253, 0, '2020-05-15'),
 (253, 2, '2020-05-22'),
 (253, 4, '2020-10-12'),
 (254, 0, '2020-07-23'),
 (254, 4, '2020-07-30'),
 (255, 0, '2020-03-29'),
 (255, 2, '2020-04-05'),
 (255, 3, '2020-10-05'),
 (256, 0, '2020-07-13'),
 (256, 1, '2020-07-20'),
 (256, 2, '2020-11-23'),
 (257, 0, '2020-01-15'),
 (257, 2, '2020-01-22'),
 (257, 3, '2020-04-22'),
 (257, 4, '2021-04-22'),
 (258, 0, '2020-06-19'),
 (258, 1, '2020-06-26'),
 (258, 3, '2020-07-06'),
 (259, 0, '2020-11-09'),
 (259, 1, '2020-11-16'),
 (259, 2, '2021-02-13'),
 (260, 0, '2020-09-21'),
 (260, 2, '2020-09-28'),
 (261, 0, '2020-03-12'),
 (261, 2, '2020-03-19'),
 (261, 3, '2020-05-19'),
 (262, 0, '2020-05-14'),
 (262, 1, '2020-05-21'),
 (263, 0, '2020-07-10'),
 (263, 2, '2020-07-17'),
 (263, 4, '2020-07-20'),
 (264, 0, '2020-09-12'),
 (264, 2, '2020-09-19'),
 (264, 4, '2020-12-07'),
 (265, 0, '2020-06-13'),
 (265, 1, '2020-06-20'),
 (265, 4, '2020-07-14'),
 (266, 0, '2020-07-20'),
 (266, 1, '2020-07-27'),
 (266, 3, '2020-12-04'),
 (267, 0, '2020-09-19'),
 (267, 1, '2020-09-26'),
 (267, 3, '2020-10-10'),
 (268, 0, '2020-10-07'),
 (268, 1, '2020-10-14'),
 (268, 4, '2020-11-07'),
 (269, 0, '2020-07-29'),
 (269, 1, '2020-08-05'),
 (269, 2, '2020-12-06'),
 (270, 0, '2020-07-05'),
 (270, 2, '2020-07-12'),
 (270, 3, '2021-01-12'),
 (271, 0, '2020-08-29'),
 (271, 2, '2020-09-05'),
 (272, 0, '2020-12-19'),
 (272, 1, '2020-12-26'),
 (272, 3, '2021-01-17'),
 (273, 0, '2020-02-14'),
 (273, 1, '2020-02-21'),
 (274, 0, '2020-03-01'),
 (274, 1, '2020-03-08'),
 (275, 0, '2020-04-27'),
 (275, 1, '2020-05-04'),
 (275, 4, '2020-09-09'),
 (276, 0, '2020-12-25'),
 (276, 2, '2021-01-01'),
 (276, 3, '2021-03-01'),
 (277, 0, '2020-08-06'),
 (277, 1, '2020-08-13'),
 (278, 0, '2020-08-01'),
 (278, 2, '2020-08-08'),
 (278, 3, '2020-11-08'),
 (279, 0, '2020-03-31'),
 (279, 3, '2020-04-07'),
 (280, 0, '2020-06-17'),
 (280, 1, '2020-06-24'),
 (280, 2, '2020-10-28'),
 (280, 4, '2021-02-23'),
 (281, 0, '2020-01-01'),
 (281, 1, '2020-01-08'),
 (282, 0, '2020-06-21'),
 (282, 2, '2020-06-28'),
 (283, 0, '2020-06-11'),
 (283, 1, '2020-06-18'),
 (283, 2, '2020-09-11'),
 (283, 3, '2020-12-11'),
 (284, 0, '2020-07-27'),
 (284, 2, '2020-08-03'),
 (284, 4, '2020-11-18'),
 (285, 0, '2020-07-06'),
 (285, 4, '2020-07-13'),
 (286, 0, '2020-03-23'),
 (286, 2, '2020-03-30'),
 (287, 0, '2020-08-23'),
 (287, 1, '2020-08-30'),
 (287, 3, '2020-12-09'),
 (288, 0, '2020-11-28'),
 (288, 1, '2020-12-05'),
 (288, 4, '2020-12-06'),
 (289, 0, '2020-01-08'),
 (289, 2, '2020-01-15'),
 (290, 0, '2020-01-10'),
 (290, 1, '2020-01-17'),
 (291, 0, '2020-03-03'),
 (291, 1, '2020-03-10'),
 (291, 3, '2020-08-16'),
 (292, 0, '2020-08-14'),
 (292, 1, '2020-08-21'),
 (292, 3, '2020-10-18'),
 (293, 0, '2020-10-30'),
 (293, 1, '2020-11-06'),
 (293, 2, '2021-03-15'),
 (293, 4, '2021-03-18'),
 (294, 0, '2020-01-19'),
 (294, 4, '2020-01-26'),
 (295, 0, '2020-06-01'),
 (295, 1, '2020-06-08'),
 (295, 2, '2020-08-17'),
 (296, 0, '2020-10-17'),
 (296, 4, '2020-10-24'),
 (297, 0, '2020-08-13'),
 (297, 2, '2020-08-20'),
 (297, 3, '2020-12-20'),
 (298, 0, '2020-10-26'),
 (298, 1, '2020-11-02'),
 (298, 2, '2020-12-13'),
 (299, 0, '2020-09-13'),
 (299, 1, '2020-09-20'),
 (299, 2, '2020-10-28'),
 (299, 3, '2021-01-28'),
 (300, 0, '2020-04-06'),
 (300, 1, '2020-04-13'),
 (300, 3, '2020-10-04'),
 (301, 0, '2020-05-07'),
 (301, 1, '2020-05-14'),
 (301, 2, '2020-10-30'),
 (301, 3, '2021-01-30'),
 (302, 0, '2020-01-09'),
 (302, 2, '2020-01-16'),
 (302, 4, '2020-01-22'),
 (303, 0, '2020-02-13'),
 (303, 1, '2020-02-20'),
 (303, 4, '2020-06-15'),
 (304, 0, '2020-12-28'),
 (304, 1, '2021-01-04'),
 (304, 4, '2021-01-27'),
 (305, 0, '2020-11-16'),
 (305, 1, '2020-11-23'),

### Case Study Questions

### A. Customer Journey

#### Based off the 8 sample customers provided in the sample from the `subscriptions` table, write a brief description about each customer’s onboarding journey.

In [6]:
%%sql
CREATE VIEW temp_danny
AS

select s.*, p.plan_name, p.price
from subscription s
left join plans p
on s.plan_id = p.plan_id
where s.customer_id <= 19

 * sqlite:///foodie-fi.db
Done.

[]

In [7]:
%%sql
with data as (
select *
, lead(start_date,1,0) over (partition by customer_id order by start_date) plan_duration
from 
temp_danny
)

select customer_id, plan_id, start_date, plan_name
, cast(coalesce(julianday(date(plan_duration)) - julianday(date(start_date)),0)as  integer) plan_duration
, price
from data

 * sqlite:///foodie-fi.db
Done.

[(1, 0, '2020-08-01', 'trial', 7, 0.0),
 (1, 1, '2020-08-08', 'basic monthly', 0, 9.9),
 (2, 0, '2020-09-20', 'trial', 7, 0.0),
 (2, 3, '2020-09-27', 'pro annual', 0, 199.0),
 (3, 0, '2020-01-13', 'trial', 7, 0.0),
 (3, 1, '2020-01-20', 'basic monthly', 0, 9.9),
 (4, 0, '2020-01-17', 'trial', 7, 0.0),
 (4, 1, '2020-01-24', 'basic monthly', 88, 9.9),
 (4, 4, '2020-04-21', 'churn', 0, None),
 (5, 0, '2020-08-03', 'trial', 7, 0.0),
 (5, 1, '2020-08-10', 'basic monthly', 0, 9.9),
 (6, 0, '2020-12-23', 'trial', 7, 0.0),
 (6, 1, '2020-12-30', 'basic monthly', 58, 9.9),
 (6, 4, '2021-02-26', 'churn', 0, None),
 (7, 0, '2020-02-05', 'trial', 7, 0.0),
 (7, 1, '2020-02-12', 'basic monthly', 100, 9.9),
 (7, 2, '2020-05-22', 'pro monthly', 0, 19.9),
 (8, 0, '2020-06-11', 'trial', 7, 0.0),
 (8, 1, '2020-06-18', 'basic monthly', 46, 9.9),
 (8, 2, '2020-08-03', 'pro monthly', 0, 19.9),
 (9, 0, '2020-12-07', 'trial', 7, 0.0),
 (9, 3, '2020-12-14', 'pro annual', 0, 199.0),
 (10, 0, '2020-09-19', 'trial', 7, 0.0),
 (10, 2, '2020-09-26', 'pro monthly', 0, 19.9),
 (11, 0, '2020-11-19', 'trial', 7, 0.0),
 (11, 4, '2020-11-26', 'churn', 0, None),
 (12, 0, '2020-09-22', 'trial', 7, 0.0),
 (12, 1, '2020-09-29', 'basic monthly', 0, 9.9),
 (13, 0, '2020-12-15', 'trial', 7, 0.0),
 (13, 1, '2020-12-22', 'basic monthly', 97, 9.9),
 (13, 2, '2021-03-29', 'pro monthly', 0, 19.9),
 (14, 0, '2020-09-22', 'trial', 7, 0.0),
 (14, 1, '2020-09-29', 'basic monthly', 0, 9.9),
 (15, 0, '2020-03-17', 'trial', 7, 0.0),
 (15, 2, '2020-03-24', 'pro monthly', 36, 19.9),
 (15, 4, '2020-04-29', 'churn', 0, None),
 (16, 0, '2020-05-31', 'trial', 7, 0.0),
 (16, 1, '2020-06-07', 'basic monthly', 136, 9.9),
 (16, 3, '2020-10-21', 'pro annual', 0, 199.0),
 (17, 0, '2020-07-27', 'trial', 7, 0.0),
 (17, 1, '2020-08-03', 'basic monthly', 130, 9.9),
 (17, 3, '2020-12-11', 'pro annual', 0, 199.0),
 (18, 0, '2020-07-06', 'trial', 7, 0.0),
 (18, 2, '2020-07-13', 'pro monthly', 0, 19.9),
 (19, 0, '2020-06-22', 'trial', 7, 0.0),
 (19, 2, '2020-06-29', 'pro monthly', 61, 19.9),
 (19, 3, '2020-08-29', 'pro annual', 0, 199.0)]

- Customers `1, 3, 5, 12 & 14` opted for the `trial` and switched their plan to the `basic monthly` plan 
- Customers `2 & 9` started with the `trial` and switched to the `pro annual` plan
- Customers `4 & 6` started with the `trial`, switched to the `basic monthly` plan and further `churned`
- Customers `7, 8 & 13` opted for the `trial`, switched to the `basic monthly` and later upgraded to the `pro monthly` plan
- Customers `10 & 18` started with the `trial` and upgraded to the `pro monthly` plan
- Customer `11` opted for the `trial` and later `churned`
- Customer `15` started with the `trial`, upgraded to the `pro monthly` plan and later churned
- Customers `16 & 17` started with the `trial`, switched to the `basic monthly` and later upgraded to the `pro annual` plan
- Customer `19` started with the `trial`, switched to `pro monthly` and later upgraded to the `pro annual` plan

- Approximately, `63%` of customers subscribed to the `basic monthly` plan after their `trial`, whilst the remaining customers subscribed to a `pro` plan with the exception of `customer 11` who churned right after the trial.

### B. Data Analysis Questions

#### Question 1 - How many customers has Foodie-Fi ever had?

In [8]:
%%sql
select count(distinct(customer_id)) customer_count
from subscription

 * sqlite:///foodie-fi.db
Done.

[(1000,)]

- Foodie-fi has had `1000` customers so far.

#### Question 2 - What is the monthly distribution of trial plan start_date values for our dataset - use the start of the month as the group by value

In [9]:
%%sql
with month as (
select *, date(s.start_date,'start of month') month_start 
from subscription s
left join plans p
on s.plan_id = p.plan_id
where p.plan_name = 'trial'
)

select month_start, count(customer_id) customer_count
from month
group by month_start

 * sqlite:///foodie-fi.db
Done.

[('2020-01-01', 88),
 ('2020-02-01', 68),
 ('2020-03-01', 94),
 ('2020-04-01', 81),
 ('2020-05-01', 88),
 ('2020-06-01', 79),
 ('2020-07-01', 89),
 ('2020-08-01', 88),
 ('2020-09-01', 87),
 ('2020-10-01', 79),
 ('2020-11-01', 75),
 ('2020-12-01', 84)]

#### Question 3 - What plan start_date values occur after the year 2020 for our dataset? Show the breakdown by count of events for each plan_name

In [10]:
%%sql
with dates as (
select * 
,strftime('%Y',date(s.start_date)) date_year
from subscription s
left join plans p
on s.plan_id = p.plan_id
)

select plan_name, count(plan_name) event_count
from dates
where strftime('%Y',date(start_date)) > '2020'
group by plan_name
order by event_count

 * sqlite:///foodie-fi.db
Done.

[('basic monthly', 8), ('pro monthly', 60), ('pro annual', 63), ('churn', 71)]

#### Question 4 - What is the customer count and percentage of customers who have churned rounded to 1 decimal place?

In [11]:
%%sql
select churned, total_customers
, round((churned*1.0/total_customers)*100,1)||'%' 'churned_%'
from
(select count(case when p.plan_name = 'churn' then 1 end) churned
, count(distinct(s.customer_id)) total_customers
from subscription s
left join plans p
on s.plan_id = p.plan_id) churn

 * sqlite:///foodie-fi.db
Done.

[(307, 1000, '30.7%')]

- `307` customers have churned so far and this accounts for `30.7%` of the customer base.

#### Question 5 - How many customers have churned straight after their initial free trial - what percentage is this rounded to the nearest whole number?

In [12]:
%%sql
with switch as (
select *
, row_number() over (partition by s.customer_id order by s.start_date) rank
, lead(p.plan_name,1) over (partition by customer_id order by start_date) switch_one
from subscription s
left join plans p
on s.plan_id = p.plan_id
)

select count(case when switch_one = 'churn' and rank = 1 then 1 end) churned
, count(distinct(customer_id)) total_cust
, cast((count(case when switch_one = 'churn' and rank = 1 then 1 end)*1.0/
        count(distinct(customer_id)))*100 as int)||'%' 'churned_%'  
from switch

 * sqlite:///foodie-fi.db
Done.

[(92, 1000, '9%')]

- `92` customers churned right after their `trial` period and this accounts for `9%` of the customer base.

#### Question 6 - What is the number and percentage of customer plans after their initial free trial?

In [13]:
%%sql
with switch as (
select *
, row_number() over (partition by s.customer_id order by s.start_date) rank
, lead(p.plan_name,1) over (partition by customer_id order by start_date) switch_one
from subscription s
left join plans p
on s.plan_id = p.plan_id
)

, calc as (
select *
, count(case when switch_one != 'churn' and rank = 1 then 1 end) cplan
, round((count(case when switch_one != 'churn' and rank = 1 then 1 end)*1.0/
         (select count(distinct(customer_id)) from subscription ))*100,1)||'%' customer_perc
from switch
group by switch_one
)

select switch_one plan, cplan cust_count, customer_perc
from calc
where switch_one != 'churn'
order by cplan desc

 * sqlite:///foodie-fi.db
Done.

[('basic monthly', 546, '54.6%'),
 ('pro monthly', 325, '32.5%'),
 ('pro annual', 37, '3.7%')]

- After their initial trial,
- `546` customers subscribed to the `basic monthly` plan which accounts for `54.6%` of the customer base
- `325` customers subscribed to the `pro monthly` plan which accounts for `32.5%` of the customer base and 
- `37` customers subscribed to the `pro annual` plan which accounts for `3.7%` of the customer base.

#### Question 7 - What is the customer count and percentage breakdown of all 5 plan_name values at 2020-12-31?

In [14]:
%%sql
with rnk as (
select customer_id, start_date
, rank() over (partition by customer_id order by start_date desc) rank
from subscription
where start_date <= '2020-12-31'   
)

select p.plan_name, count(p.plan_name) customer_count
, round((count(p.plan_name)*1.0/
         (select count(distinct(customer_id)) from subscription ))*100,1) '%_breakdown'
from subscription s
left join plans p
on s.plan_id = p.plan_id
join rnk r
on s.customer_id = r.customer_id
where r.rank = 1
and s.start_date = r.start_date
and date(s.start_date) <= '2020-12-31'
group by p.plan_name

 * sqlite:///foodie-fi.db
Done.

[('basic monthly', 224, 22.4),
 ('churn', 236, 23.6),
 ('pro annual', 195, 19.5),
 ('pro monthly', 326, 32.6),
 ('trial', 19, 1.9)]

-  As at `2020-12-31`, there were:
- `1.9%` of customers on the `trial`
- `22.4%` of customers on the `basic monthly` plan
- `19.5%` of customers on the `pro annual` plan
- `32.6%` of customers on the `pro monthly` plan and 
- `23.6%` of customers had churned.

#### Question 8 - How many customers have upgraded to an annual plan in 2020?

In [15]:
%%sql
with rnk as (
select customer_id, start_date
, rank() over (partition by customer_id order by start_date asc) rank
from subscription
where strftime('%Y',date(start_date)) = '2020'   
)

select p.plan_name, count(s.customer_id) cust_count
from subscription s
left join plans p
on s.plan_id = p.plan_id
join rnk r
on s.customer_id = r.customer_id
where r.rank > 2
and s.start_date = r.start_date
and p.plan_name = 'pro annual' 
and strftime('%Y',date(s.start_date)) = '2020'
group by p.plan_name

 * sqlite:///foodie-fi.db
Done.

[('pro annual', 158)]

- `158` customers upgraded to an `annual` plan in 2020
- This is based on the assumption that an upgrade is recognised after the first plan following the trial and not immediately after the trial.

#### Question 9 - How many days on average does it take for a customer to switch to an annual plan from the day they join Foodie-Fi?

In [16]:
%%sql
select round(avg(cast((julianday(date(s2.start_date)) - 
                       julianday(date(s1.start_date)))as int))) avg_days
from subscription s1
join subscription s2
on s1.customer_id = s2.customer_id
where s1.plan_id = 0
and s2.plan_id = 3

 * sqlite:///foodie-fi.db
Done.

[(105.0,)]

- On average it took 105 days for a customer to switch to an annual plan.

#### Question 10 - Can you further breakdown this average value into 30 day periods (i.e. 0-30 days, 31-60 days etc)

In [17]:
%%sql
with average as (
select s1.customer_id
, cast((julianday(date(s2.start_date)) - julianday(date(s1.start_date)))as int) days_diff
from subscription s1
join subscription s2
on s1.customer_id = s2.customer_id
where s1.plan_id = 0
and s2.plan_id = 3

)
, avg_split as (
select *
, case when days_diff <=30 then '0-30'
when days_diff > 30 and days_diff <= 60 then '31-60'
when days_diff > 60 and days_diff <= 90 then '61-90'
when days_diff > 90 and days_diff <= 120 then '91-120'
when days_diff > 120 and days_diff <=150 then '121-150'
when days_diff > 150 and days_diff <=180 then '151-180'
when days_diff > 180 and days_diff <=210 then '181-210'
when days_diff > 210 and days_diff <=240 then '211-240'
when days_diff > 240 and days_diff <=270 then '241-270'
when days_diff > 270 and days_diff <=300 then '271-300'
when days_diff > 300 and days_diff <=330 then '301-330'
when days_diff > 330 and days_diff <=365 then '331-365'
else 'over a year'
end days_grpng
from average a
)

select cast(round(avg(days_diff),0) as int)avg_days, days_grpng
, count(customer_id) cust_cnt
from avg_split
group by days_grpng
order by avg_days

 * sqlite:///foodie-fi.db
Done.

[(10, '0-30', 49),
 (42, '31-60', 24),
 (71, '61-90', 34),
 (101, '91-120', 35),
 (133, '121-150', 42),
 (162, '151-180', 36),
 (191, '181-210', 26),
 (224, '211-240', 4),
 (257, '241-270', 5),
 (285, '271-300', 1),
 (327, '301-330', 1),
 (346, '331-365', 1)]

- On average it took `49` customers `10` days to switch to an annual plan between `0-30` days of joining Foodie-fi
- On average it took `24` customers `42` days to switch to an annual plan between `31-60` days of joining Foodie-fi
- On average it took `34` customers `71` days to switch to an annual plan between `61-90` days of joining Foodie-fi
- On average it took `35` customers `101` days to switch to an annual plan between `91-120` days of joining Foodie-fi
- On average it took `42` customers `133` days to switch to an annual plan between `121-150` days of joining Foodie-fi
- On average it took `36` customers `162` days to switch to an annual plan between `151-180` days of joining Foodie-fi
- On average it took `26` customers `191` days to switch to an annual plan between `181-210` days of joining Foodie-fi
- On average it took `4` customers `224` days to switch to an annual plan between `211-240` days of joining Foodie-fi
- On average it took `5` customers `257` days to switch to an annual plan between `241-270` days of joining Foodie-fi
- On average it took `1` customers `285` days to switch to an annual plan between `271-300` days of joining Foodie-fi
- On average it took `1` customers `327` days to switch to an annual plan between `301-330` days of joining Foodie-fi
- On average it took `1` customers `346` days to switch to an annual plan between `331-365` days of joining Foodie-fi.

#### Question 11 - How many customers downgraded from a pro monthly to a basic monthly plan in 2020?

In [18]:
%%sql
with stag as (
select *
, case when date(s2.start_date) < date(s1.start_date) then 'downgrade' 
    else 'upgrade' end plan_switch
from subscription s1
join subscription s2
on s1.customer_id = s2.customer_id
and strftime('%Y',date(s1.start_date)) = '2020'
where s1.plan_id = 1
and s2.plan_id = 2
)

select count(*) cust_count
from stag
where plan_switch = 'downgrade'

 * sqlite:///foodie-fi.db
Done.

[(0,)]

- There are no customers who downgraded from a `pro monthly` to a `basic monthly` plan.